//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>

// ---------------- Integer Types Definitions -----------------

typedef int64_t int224_t;
typedef int64_t int864_t;

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef double float64_t;
typedef long double float80_t;

// ------------------- Function Prototypes --------------------

int32_t Activate(void);
int32_t DllCanUnloadNow(void);
int32_t DllGetClassObject(void);
int32_t entry_point(int32_t a1);
int32_t function_10001000(int16_t a1, int32_t a2);
int32_t function_100010cf(void);
int32_t function_100010ef(void);
int32_t function_100010f7(void);
int32_t function_1000110b(int32_t a1);
int32_t function_1000112d(int32_t a1);
int32_t function_10001150(int16_t a1);
int32_t function_10001171(void);
int32_t function_1000117a(void);
int32_t function_100011a3(int32_t a1);
int32_t function_100011be(void);
int32_t function_100011eb(int32_t a1);
int32_t function_10001202(void);
int32_t function_1000122b(int32_t a1, int32_t a2, int32_t a3);
int32_t function_100012b9(void);
int32_t function_100012c0(int32_t result2, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10);
int32_t function_100013c6(void);
int32_t function_100013de(int32_t a1, int32_t result);
int32_t function_1000140d(void);
int32_t function_1000143d(void);
int32_t function_10001488(void);
int32_t function_100014cd(void);
int32_t function_100014e1(void);
int32_t function_10001515(void);
int32_t function_1000151a(int32_t a1, int32_t a2);
int32_t function_10001539(int16_t a1, int32_t a2);
int32_t function_100015d1(int16_t a1, int32_t a2);
int32_t function_100016df(void);
int32_t function_10001705(void);
int32_t function_1000170c(void);
int32_t function_1000171c(void);
int32_t function_1000171d(int32_t a1);
int32_t function_1000175c(void);
int32_t function_100017e1(void);
int32_t function_1000186b(void);
int32_t function_100019db(int32_t a1);
int32_t function_100019e0(unsigned char a1);
int32_t function_10001a08(int32_t a1);
int32_t function_10001a1c(int32_t a1);
int32_t function_10001a7f(void);
int32_t function_10001aa6(void);
int32_t function_1000f000(int32_t a1);
int32_t function_1000f06f(int32_t a1);
int32_t function_1000f0d6(void);
int32_t function_1000f0dc(int32_t a1, int32_t a2, int32_t result, int32_t a4);
int32_t function_1000f3d3(int16_t a1);
int32_t function_1000f479(void);
int32_t function_1000f49b(void);
int32_t function_1000f4bb(int32_t a1);
int32_t function_1000f4cf(void);
int32_t function_1000f4f3(int32_t a1);
int32_t function_1000f592(void);
int32_t function_1000f5a1(void);
int32_t function_1000f5b0(void);
int32_t function_1000f5b7(int32_t a1);
int32_t function_1000f5c7(void);
int32_t function_1000f620(int32_t a1);
int32_t function_1000f6cf(void);
int32_t function_1000f711(void);
int32_t function_1000f721(int32_t a1);
int32_t function_1000f761(void);
int32_t function_1000f763(int32_t a1);
int32_t function_1000f770(void);
int32_t function_1000f7b2(void);
int32_t function_1000f7c2(void);
int32_t function_1000f7dd(void);
int32_t function_1000f855(void);
int32_t function_1000f85e(void);
int32_t function_1000f870(void);
int32_t function_1000f87a(void);
int32_t function_1000f888(void);
int32_t function_1000f8a0(void);
int32_t function_1000f8a3(void);
int32_t function_1000f8c7(void);
int32_t function_1000f8e4(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8);
int32_t function_1000f900(int32_t a1);
int32_t function_1000f951(int32_t a1);
int32_t function_1000f963(int32_t a1);
int32_t function_1000f975(void);
int32_t function_1000f9a4(int32_t a1);
int32_t function_1000f9fb(void);
int32_t function_1000fa55(void);
int32_t function_1000fa81(void);
int32_t function_1000fa8e(int32_t a1);
int32_t function_1000faa8(int32_t a1);
int32_t function_1000fb2f(void);
int32_t function_1000fb32(void);
int32_t function_1000fb36(void);
int32_t function_1000fb43(int32_t a1);
int32_t function_1000fb63(void);
int32_t function_1000fb68(void);
int32_t function_1000fb81(void);
int32_t function_1000fb82(void);
int32_t function_1000fbb4(void);
int32_t function_1000fbc3(int32_t a1);
int32_t function_1000fc62(int32_t a1);
int32_t function_1000fc63(int32_t result);
int32_t function_1000fc89(int32_t a1);
int32_t function_1000fcbd(void);
int32_t function_1000fce9(void);
int32_t function_1000fd78(void);
int32_t function_1000fe16(void);
int32_t function_1000fe3f(void);
int32_t function_1000fe57(void);
int32_t function_1000fe62(void);
int32_t function_1000fe6b(void);
int32_t function_1000fe76(void);
int32_t function_1000fe81(void);
int32_t function_1000fe89(int32_t a1);
int32_t function_1000feb9(int32_t a1, uint32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t function_1000fff4(void);
int32_t function_1001000c(void);
int32_t function_3577b9d2(void);
int32_t function_35be468b(void);
int32_t function_3e81841d(int32_t a1);
int32_t function_455ec90c(void);
int32_t function_468a5bdf(void);
int32_t function_4756a85f(void);
int32_t function_49e96b98(void);
int32_t function_4a0580fa(void);
int32_t function_50bcab7a(void);
int32_t function_51e098b1(void);
int32_t function_5460c537(void);
int32_t function_54699785(void);
int32_t function_568d38a9(void);
int32_t function_5788a8a9(void);
int32_t function_598634dc(int32_t a1);
int32_t function_5a4a141c(void);
int32_t function_5b05bc21(void);
int32_t function_5d69d1f9(void);
int32_t function_5f4a09dc(void);
int32_t function_5f88bee1(void);
int32_t function_5fb0edc8(void);
int32_t function_5fd80b7c(void);
int32_t function_607bc505(void);
int32_t function_62f859a1(void);
int32_t function_63f45647(int32_t * a1, int32_t a2);
int32_t function_678e9999(void);
int32_t function_68140a05(void);
int32_t function_69a25772(void);
int32_t function_6f00ea5c(void);
int32_t function_70f65d9d(void);
int32_t function_7483ff02(void);
int32_t function_74942760(void);
int32_t function_78bcab7a(void);
int32_t function_7c6d2021(void);
int32_t function_7f484ade(void);
int32_t function_7f83f8d6(void);
int32_t function_80642ee6(void);
int32_t function_82065723(void);
int32_t function_83cc5381(void);
int32_t function_84221700(void);
int32_t function_8456585f(void);
int32_t function_854fda12(void);
int32_t function_855604d5(void);
int32_t function_86ea5e3b(int16_t * a1, int16_t a2);
int32_t function_8a10c8c9(void);
int32_t function_8ceb7173(void);
int32_t function_90cf608f(void);
int32_t function_91df9ff5(void);
int32_t function_92f83f53(void);
int32_t function_9305d229(void);
int32_t function_968cfd5e(int32_t a1);
int32_t function_96dcdc97(void);
int32_t function_9d2aaa2b(int16_t a1);
int32_t function_9e0ab321(int32_t * a1);
int32_t function_9e0b0681(int32_t a1);
int32_t function_a4361ed4(void);
int32_t function_a55b2c5b(void);
int32_t function_a68faf16(void);
int32_t function_a8140a07(void);
int32_t function_ae1d200c(void);
int32_t function_afe33235(void);
int32_t function_b2c580fa(void);
int32_t function_b8bcab7a(void);
int32_t function_ba7519a7(void);
int32_t function_baecd97a(void);
int32_t function_bdfaf95e(void);
int32_t function_bfd7ff92(void);
int32_t function_bfd8188e(void);
int32_t function_c0bb3cda(int16_t a1);
int32_t function_c48b5f2f(void);
int32_t function_c7b50a15(void);
int32_t function_cad7dd8e(int32_t a1);
int32_t function_cd8ecc31(void);
int32_t function_d3e9c169(int32_t a1, int32_t a2);
int32_t function_d3e9f723(int32_t a1, int32_t a2);
int32_t function_d85802ab(void);
int32_t function_da3716f9(void);
int32_t function_dbd72018(void);
int32_t function_de2cd9d5(void);
int32_t function_dfa93e7a(void);
int32_t function_dff00dd5(void);
int32_t function_e1d9ec21(void);
int32_t function_e34b5cb9(void);
int32_t function_e4bddbce(int32_t a1, int32_t a2);
int32_t function_e625bc2e(int32_t a1, int32_t a2);
int32_t function_e8c9cae1(int32_t * a1, int32_t a2, int32_t a3, int32_t a4, int16_t * a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9);
int32_t function_e9515fcc(int32_t a1);
int32_t function_e9555466(void);
int32_t function_e99dab7a(void);
int32_t function_eb3de332(int32_t a1, int32_t a2, int32_t a3);
int32_t function_eda590a9(void);
int32_t function_f236a6bf(void);
int32_t function_f2583fc2(void);
int32_t function_f52bc664(int32_t a1);
int32_t function_f9f51bf8(void);
int32_t function_fb9f6d74(void);
int32_t function_fd89f9cb(void);
int32_t function_fde8fc74(void);
int32_t function_fffff147(void);
int32_t function_fffff552(void);
int32_t HookProc(int32_t a1);
int32_t Logoff(int32_t result, int32_t a2, int32_t a3);
int32_t Logon(void);
int32_t Start(int16_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21);
int32_t unknown_3db9644a(void);
int32_t unknown_a06c3f(int32_t a1);
int32_t unknown_a6e4e307(int16_t a1, int32_t a2);
int32_t unknown_b5361f2a(void);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // 0x10006010
char g2 = 0; // 0x10006014
char * g3; // 0x1000622c
int32_t g4 = 0; // 0x10006258
int16_t * g5 = (int16_t *)0x760000bf; // 0x1000a0a9
int32_t g6;

// ------------------------ Functions -------------------------

// Address range: 0x10001000 - 0x100010ca
int32_t function_10001000(int16_t a1, int32_t a2) {
    // 0x10001000
    __asm_hlt();
    return 0x1d33e30;
}

// Address range: 0x100010cf - 0x100010d2
int32_t function_100010cf(void) {
    // 0x100010cf
    int32_t result; // 0x100010cf
    return result;
}

// Address range: 0x100010e6 - 0x100010ee
int32_t DllCanUnloadNow(void) {
    // 0x100010e6
    int32_t result; // 0x100010e6
    return result;
}

// Address range: 0x100010ef - 0x100010f7
int32_t function_100010ef(void) {
    // 0x100010ef
    int16_t v1; // 0x100010ef
    return function_10001150(v1);
}

// Address range: 0x100010f7 - 0x100010fe
int32_t function_100010f7(void) {
    // 0x100010f7
    int32_t v1; // 0x100010f7
    bool v2; // 0x100010f7
    int32_t result = v1 - (v2 ? 163 : 162) & 255 | v1 & -256; // 0x100010f7
    char * v3 = (char *)result; // 0x100010f9
    int32_t v4; // 0x100010f7
    *v3 = *v3 + (char)v4;
    return result;
}

// Address range: 0x1000110b - 0x1000110e
int32_t function_1000110b(int32_t a1) {
    // 0x1000110b
    int32_t v1; // 0x1000110b
    int32_t result; // 0x1000110b
    *(char *)result = (char)result + (char)v1;
    return result;
}

// Address range: 0x1000112d - 0x1000112e
int32_t function_1000112d(int32_t a1) {
    // 0x1000112d
    int32_t result; // 0x1000112d
    return result;
}

// Address range: 0x10001150 - 0x1000115c
int32_t function_10001150(int16_t a1) {
    // 0x10001150
    int32_t v1; // 0x10001150
    int32_t v2; // 0x10001150
    __asm_outsb((int16_t)v2 - 1, (char)v1);
    int32_t v3; // 0x10001150
    return v3 & -256 | 53;
}

// Address range: 0x10001171 - 0x10001172
int32_t function_10001171(void) {
    // 0x10001171
    int32_t result; // 0x10001171
    return result;
}

// Address range: 0x1000117a - 0x1000118e
int32_t function_1000117a(void) {
    // 0x1000117a
    int32_t v1; // 0x1000117a
    int32_t v2; // 0x1000117a
    int32_t * v3 = (int32_t *)(v2 + 2 * v1); // 0x1000117c
    bool v4; // 0x1000117a
    *v3 = *v3 - (v4 ? 0xe46f0b0 : 0xe46f0af);
    return function_80642ee6();
}

// Address range: 0x100011a3 - 0x100011a6
int32_t function_100011a3(int32_t a1) {
    // 0x100011a3
    int32_t result; // 0x100011a3
    return result;
}

// Address range: 0x100011be - 0x100011c8
int32_t function_100011be(void) {
    // 0x100011be
    int32_t result; // 0x100011be
    return result;
}

// Address range: 0x100011eb - 0x100011ee
int32_t function_100011eb(int32_t a1) {
    // 0x100011eb
    int32_t result; // 0x100011eb
    bool v1; // 0x100011eb
    if (!v1) {
        result = function_10001171();
    }
    // 0x100011ed
    return result;
}

// Address range: 0x10001202 - 0x10001203
int32_t function_10001202(void) {
    // 0x10001202
    int32_t result; // 0x10001202
    return result;
}

// Address range: 0x1000122b - 0x100012b9
int32_t function_1000122b(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = a2;
    int32_t v2; // 0x1000122b
    *(char *)v2 = -1 - (char)v2;
    *(int32_t *)0x757f1020 = *(int32_t *)0x757f1020 & 0x7a14a7db;
    int32_t v3 = *(int32_t *)0xa5ac911 + (int32_t)&v1; // 0x10001244
    char v4 = llvm_ctpop_i8((char)v3); // 0x10001244
    *(int32_t *)0xa5ac911 = v3;
    if ((v4 & 1) == 0) {
        // 0x1000124c
        int32_t v5; // 0x1000122b
        int32_t v6 = v5 | 0x160012ea; // 0x10001230
        return 0x10000 * (v6 + 35 & 63 | v6 & 0xff00) / 0x10000;
    }
    // 0x1000129c
    __asm_sti();
    __asm_hlt();
    return function_74942760();
}

// Address range: 0x100012b9 - 0x100012c0
int32_t function_100012b9(void) {
    // 0x100012b9
    return function_fd89f9cb();
}

// Address range: 0x100012c0 - 0x100013b4
int32_t function_100012c0(int32_t result2, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10) {
    int32_t v1 = a9;
    int32_t v2; // 0x100012c0
    int32_t v3; // 0x100012c0
    *(int32_t *)v2 = __asm_in((int16_t)v3);
    int32_t v4; // 0x100012c0
    if ((v4 & 0xd471) != 0) {
        int32_t result = *(int32_t *)(2 * a8 + (int32_t)&v1) | a7; // 0x100012ce
        if (result == 0) {
            // 0x100012d2
            return result;
        }
        char * v5 = (char *)result; // 0x100012d7
        *v5 = *v5 + (char)a6;
        return result;
    }
    unsigned char v6 = __readfsbyte(-0x7bd5f000); // 0x1000133c
    int32_t v7; // 0x100012c0
    char * v8 = (char *)(v7 + 40); // 0x10001349
    unsigned char v9 = *v8; // 0x10001349
    *v8 = v9 / 2 | 128 * v9;
    char * v10 = (char *)(a7 - 124); // 0x1000134c
    *v10 = *v10 ^ (char)result2;
    int32_t v11 = *(int32_t *)(a8 & -256 | (int32_t)v6); // 0x10001352
    __asm_outsd((int16_t)(a6 + 206 & 255 | a6 & 0xff00), v11);
    return result2;
}

// Address range: 0x100013b6 - 0x100013c6
int32_t DllGetClassObject(void) {
    // 0x100013b6
    int32_t result; // 0x100013b6
    return result;
}

// Address range: 0x100013c6 - 0x100013dc
int32_t function_100013c6(void) {
    // 0x100013c6
    int32_t v1; // 0x100013c6
    int32_t result = v1 | 0x62f40d89; // 0x100013d0
    char * v2 = (char *)(result - 97); // 0x100013d5
    int32_t v3; // 0x100013c6
    *v2 = *v2 | (char)v3 - 1;
    char * v4 = (char *)(result + 9); // 0x100013d9
    unsigned char v5 = *v4; // 0x100013d9
    *v4 = v5 / 128 | 2 * v5;
    return result;
}

// Address range: 0x100013de - 0x100013f5
int32_t function_100013de(int32_t a1, int32_t result) {
    // 0x100013de
    int32_t v1; // 0x100013de
    if ((llvm_ctpop_i8((char)v1 + 1) & 1) != 0) {
        // 0x100013e7
        return result;
    }
    // 0x100013eb
    int32_t v2; // 0x100013de
    int32_t v3; // 0x100013de
    *(char *)v2 = (char)v3;
    int32_t result2; // 0x100013de
    *(char *)result2 = *(char *)&result2 + (char)a1;
    return result2;
}

// Address range: 0x1000140d - 0x1000141b
int32_t function_1000140d(void) {
    // 0x1000140d
    int32_t v1; // 0x1000140d
    char * v2 = (char *)(v1 + 117); // 0x1000140d
    uint32_t v3; // 0x1000140d
    bool v4; // 0x1000140d
    *v2 = *v2 + (char)(v3 / 256) + (char)v4;
    int32_t result; // 0x1000140d
    char * v5 = (char *)(result + 0x331000a1); // 0x10001412
    uint32_t v6; // 0x1000140d
    *v5 = *v5 + (char)(v6 / 256);
    int32_t v7; // 0x1000140d
    *(char *)v1 = *(char *)&v7;
    __asm_int(75);
    return result;
}

// Address range: 0x1000143d - 0x1000143e
int32_t function_1000143d(void) {
    // 0x1000143d
    int32_t result; // 0x1000143d
    return result;
}

// Address range: 0x10001488 - 0x100014c1
int32_t function_10001488(void) {
    unsigned char v1 = *(char *)-0x5238f000 - 92 | 81; // 0x1000148f
    int32_t v2; // 0x10001488
    int32_t v3 = v2 & -256 | (int32_t)v1; // 0x1000148f
    char * v4 = (char *)v3; // 0x10001496
    char v5 = *v4; // 0x10001496
    int32_t v6; // 0x10001488
    char v7 = v6; // 0x10001496
    char v8 = v5 + v7; // 0x10001496
    *v4 = v8;
    int32_t v9; // 0x10001488
    if (((v8 ^ v5) & (v8 ^ v7)) < 0) {
        v9 = function_1000143d();
    }
    // 0x1000149d
    *(char *)v9 = v1 + v7;
    int32_t v10 = 0x10000 * v3 / 0x10000; // 0x100014a2
    int32_t v11 = v10 & -256 | (int32_t)*(char *)-0x8f4f000; // 0x100014a3
    int32_t v12; // 0x10001488
    int32_t * v13 = (int32_t *)(v11 + v12); // 0x100014ad
    *v13 = *v13 / 4;
    int32_t result = v3; // 0x100014ba
    if ((v11 + 0x5904a85d & (v10 ^ -0x80000000)) < 0) {
        result = function_bfd7ff92();
    }
    // 0x100014c0
    return result;
}

// Address range: 0x100014cd - 0x100014d9
int32_t function_100014cd(void) {
    // 0x100014cd
    __asm_hlt();
    return function_70f65d9d();
}

// Address range: 0x100014e1 - 0x100014e2
int32_t function_100014e1(void) {
    // 0x100014e1
    int32_t result; // 0x100014e1
    return result;
}

// Address range: 0x10001515 - 0x1000151a
int32_t function_10001515(void) {
    // 0x10001515
    return function_5460c537();
}

// Address range: 0x1000151a - 0x10001539
int32_t function_1000151a(int32_t a1, int32_t a2) {
    // 0x1000151a
    int32_t v1; // 0x1000151a
    if ((v1 + 1 & (v1 ^ -0x80000000)) < 0) {
        function_100014e1();
    }
    // 0x1000151d
    __asm_in_2(245);
    return function_455ec90c();
}

// Address range: 0x10001539 - 0x100015d0
int32_t function_10001539(int16_t a1, int32_t a2) {
    // 0x10001539
    int32_t v1; // 0x10001539
    uint32_t v2 = v1 - 1; // 0x10001539
    int32_t v3; // 0x10001539
    __asm_outsb((int16_t)v2, (char)v3);
    int32_t v4; // 0x10001539
    char * v5 = (char *)(v4 - 0x10eda2eb); // 0x1000153d
    *v5 = *v5 + (char)(v2 / 256);
    int32_t v6; // 0x10001539
    int32_t v7 = (v6 & 14) > 9 ? v6 + 10 : v6; // 0x10001545
    uint32_t v8 = 256 * (int32_t)((v6 & 14) > 9) + v2;
    *(char *)((v7 & 15 | v6 & -0x10000 | v8 & 0xff00) + 0x6f181000) = (char)(v8 / 256);
    if (v6 < 0) {
        // 0x10001555
        int32_t v9; // 0x10001539
        return v9 & 0xff00 & 256 * v2 | v9 & -0xff01;
    }
    // 0x100015b4
    int32_t v10; // 0x10001539
    int32_t v11 = v10 - 1; // 0x100015b7
    int32_t v12 = v4 & -0xff01 | 0x8000 * (int32_t)(v11 < 0) | 0x4000 * (int32_t)(v11 == 0) | 0x1000 * (int32_t)((v10 & 15) > 16) | 1024 * (int32_t)((llvm_ctpop_i8((char)v11) & 1) == 0) | 512; // 0x100015b8
    uint32_t v13 = *(int32_t *)(v12 + 0xa85fc48); // 0x100015be
    int32_t v14 = v12 + 0x76ddab7d + (int32_t)((v6 & 0xff00 | v2 & -0xff01) < v13) & -256; // 0x100015c9
    return v14 | (int32_t)(*(char *)(5 * (v14 | 29)) | 29);
}

// Address range: 0x100015d1 - 0x100016df
int32_t function_100015d1(int16_t a1, int32_t a2) {
    // 0x100015d1
    bool v1; // 0x100015d1
    int32_t v2 = v1 ? -1 : 1; // 0x100015d2
    unsigned char v3 = *(char *)0x48d31000; // 0x100015d3
    int32_t v4; // 0x100015d1
    int32_t v5 = v4 & -256 | (int32_t)v3; // 0x100015d3
    int32_t v6; // 0x100015d1
    int32_t v7; // 0x100015d1
    int32_t * v8 = (int32_t *)(v7 + 0x14f25028 + (int32_t)&v6); // 0x100015db
    *v8 = *v8 + 0xa317e7a + (int32_t)(v3 < 141);
    int32_t v9; // 0x100015d1
    *(int32_t *)v9 = v5;
    int32_t v10 = v7 - 1; // 0x100015ec
    int32_t v11; // 0x100015d1
    int32_t v12 = v5 | v2 + v11; // 0x100015ee
    int64_t v13 = (int64_t)*(int32_t *)v10; // 0x100015f0
    int32_t v14 = __asm_in_2(55); // 0x100015f7
    *(char *)v14 = *(char *)v12;
    if (v12 >= 0) {
        int32_t * v15 = (int32_t *)(v7 + 19); // 0x1000165b
        int32_t v16 = 0x6a160b15 * v13 != 0x6a160b1500000000 * v13 / 0x100000000 ? (int32_t)&g5 - 1 : (int32_t)&g5 - 2; // 0x1000165b
        *v15 = *v15 + v16;
        int32_t v17 = *(int32_t *)-0x15a229e9; // 0x10001660
        int32_t v18 = (v17 & 14) > 9 ? v17 + 10 : v17; // 0x10001665
        return v18 & 15 | v17 & -0x10000 | 256 * (int32_t)((v17 & 14) > 9) + v17 & 0xff00;
    }
    int32_t v19 = v1 ? -4 : 4; // 0x100015e6
    int32_t v20 = v12 + v2; // 0x100015fb
    unsigned char v21 = *(char *)0x79db1000; // 0x100015fc
    int32_t result = v19 + v9 & -256 | (int32_t)v21; // 0x100015fc
    int32_t v22; // 0x100015d1
    if (v12 <= 0) {
        if (0x6a160b15 * v13 == 0x6a160b1500000000 * v13 / 0x100000000) {
            char * v23 = (char *)(result - 0x2af09d35); // 0x100016d1
            *v23 = *v23 + v21;
            return function_1000171c();
        }
        // 0x1000166c
        *(int32_t *)((int32_t)&g5 - 6) = (int32_t)&g5 - 2;
        int32_t v24 = v2 + 1 + v14; // 0x1000166d
        *(int32_t *)v24 = *(int32_t *)v20;
        int32_t v25 = *(int32_t *)((int32_t)&g5 - 6); // 0x10001678
        *(int32_t *)-0x25b57aec = v25 & -256 | (int32_t)*(char *)0x4f541000;
        *(int32_t *)((int32_t)&g5 - 6) = v24 + v19;
        char * v26 = (char *)(v20 + v19); // 0x10001695
        *v26 = *v26 & (char)v22;
        int32_t v27 = *(int32_t *)((int32_t)&g5 + 21); // 0x1000169d
        char v28 = *(char *)*(int32_t *)((int32_t)&g5 + 9); // 0x1000169e
        bool v29 = (v27 & 14) > 9 | (v28 & 15) - ((char)v27 & 15) > 15; // 0x100016a1
        int32_t v30 = v29 ? v27 + 6 : v27; // 0x100016a1
        return v30 & 15 | v27 & -0x10000 | 256 * (int32_t)v29 + v27 & 0xff00;
    }
    if (v12 < 0 == (0x6a160b15 * v13 != 0x6a160b1500000000 * v13 / 0x100000000) != v12 != 0) {
        // 0x10001607
        *(int32_t *)((int32_t)&g5 - 6) = v20;
        return result;
    }
    char * v31 = (char *)(result - 61); // 0x10001609
    *v31 = *v31 & 119;
    char * v32 = (char *)(v20 - 0x27e6a72a); // 0x10001612
    char v33 = v22; // 0x10001612
    *v32 = *v32 + v33;
    *(char *)0xa0a095 = __readfsbyte(v20);
    char * v34 = (char *)result; // 0x1000161a
    char v35 = v10; // 0x1000161a
    *v34 = *v34 + v35;
    uint32_t v36 = __asm_bound(*(int64_t *)(result - 92)); // 0x1000161c
    unsigned char v37 = *v34; // 0x1000161f
    unsigned char v38 = v37 + v35; // 0x1000161f
    *v34 = v38;
    int32_t result2 = *(int32_t *)(v20 + v2) & -256 | (int32_t)*(char *)-0x3a44f000; // 0x1000162b
    if ((char)(v36 / 256) + v33 != (char)(v38 < v37)) {
        // 0x10001656
        return result2;
    }
    // 0x10001632
    *(int32_t *)((int32_t)&g5 - 6) = result2;
    int32_t v39 = __asm_in_2(55); // 0x10001637
    *(int16_t *)(v2 + 0xa0a093) = a1;
    int32_t * v40 = (int32_t *)v36; // 0x100016bb
    char v41 = *(char *)0x51db1000 | -22; // 0x100016b8
    uint32_t v42 = *v40; // 0x100016bb
    uint32_t v43 = v42 + (v22 & -256 | 152); // 0x100016bb
    *v40 = v43;
    v41 = v41 + 40 + (char)(v43 < v42);
    char v44 = llvm_ctpop_i8(v41); // 0x100016bd
    __asm_frstor(*(int864_t *)(4 * v39 + result2));
    while ((v44 & 1) != 0) {
        // 0x100016b9
        v42 = *v40;
        v43 = v42 + (v22 & -256 | 152);
        *v40 = v43;
        v41 = v41 + 40 + (char)(v43 < v42);
        v44 = llvm_ctpop_i8(v41);
        __asm_frstor(*(int864_t *)(4 * v39 + result2));
    }
    // 0x100016c4
    return function_e99dab7a();
}

// Address range: 0x100016df - 0x100016fd
int32_t function_100016df(void) {
    // 0x100016df
    int32_t v1; // 0x100016df
    int32_t v2 = v1 & -0xff01 | 0xa100; // 0x100016df
    char * v3 = (char *)v2; // 0x100016e1
    int32_t v4; // 0x100016df
    char v5 = v4; // 0x100016e1
    *v3 = *v3 + v5;
    int32_t v6 = __asm_bound(*(int64_t *)v2); // 0x100016e3
    *(int32_t *)(v6 - 4) = v2;
    int32_t v7; // 0x100016df
    *(int32_t *)(v6 - 8) = v7;
    *(int32_t *)(v6 - 20) = v6;
    *v3 = *v3 + v5;
    int32_t v8; // 0x100016df
    *(int64_t *)(v8 + 0x7014ffd0) = (int64_t)__asm_fbld(*(float80_t *)&v7);
    return *(int32_t *)-0x6756f000;
}

// Address range: 0x10001705 - 0x1000170b
int32_t function_10001705(void) {
    // 0x10001705
    int32_t v1; // 0x10001705
    int32_t * v2 = (int32_t *)(v1 - 118); // 0x10001708
    *v2 = *v2 | v1;
    int32_t result; // 0x10001705
    return result;
}

// Address range: 0x1000170c - 0x10001711
int32_t function_1000170c(void) {
    // 0x1000170c
    int32_t v1; // 0x1000170c
    char * v2 = (char *)(v1 + 64); // 0x1000170c
    uint32_t v3; // 0x1000170c
    *v2 = *v2 & (char)(v3 / 256);
    return function_10001705();
}

// Address range: 0x1000171c - 0x1000171d
int32_t function_1000171c(void) {
    // 0x1000171c
    int32_t result; // 0x1000171c
    return result;
}

// Address range: 0x1000171d - 0x10001759
int32_t function_1000171d(int32_t a1) {
    // 0x1000171d
    int32_t v1; // 0x1000171d
    unsigned char v2 = (char)v1; // 0x1000171d
    unsigned char v3 = v2 % 92; // 0x1000171d
    int32_t v4 = v1 & -0x10000 | (int32_t)v3 | 256 * (int32_t)(v2 / 92); // 0x1000171d
    int32_t v5; // 0x1000171d
    unsigned char v6 = v3 + (char)v5; // 0x10001726
    int32_t v7; // 0x1000171d
    int32_t v8; // 0x1000171d
    *(char *)v7 = (char)v8;
    bool v9; // 0x1000171d
    int32_t v10 = v9 ? -1 : 1; // 0x10001729
    int32_t v11 = v10 + v8; // 0x10001729
    int32_t v12 = v4 - 4; // 0x1000172e
    *(int32_t *)v12 = v11;
    unsigned char v13 = g2 + 19; // 0x10001736
    int32_t v14 = (int32_t)g2 & -256; // 0x10001736
    int32_t v15; // 0x1000171d
    int32_t v16; // 0x1000171d
    int32_t v17 = (*(int32_t *)(v15 + 0xa41c6d + 8 * v16) ^ v16) + 1; // 0x10001741
    __asm_out_3((int16_t)v17, v14 | (int32_t)v13);
    int32_t result = (v14 | (int32_t)((v13 & 14) > 9 ? g2 + 13 : v13)) & -0xfff1 | 0xa000; // 0x10001746
    char * v18 = (char *)result; // 0x10001748
    char v19 = v17; // 0x10001748
    *v18 = *v18 + v19 & -96;
    *(int32_t *)(v4 - 8) = result;
    *(int32_t *)(v4 - 12) = v5 & -0x10000 | (int32_t)v6 | (256 * v17 | v5) & 0xff00;
    *(int32_t *)(v4 - 16) = v17;
    int32_t v20; // 0x1000171d
    *(int32_t *)(v4 - 20) = v20 & -256 | (int32_t)(v6 + (char)v20);
    *(int32_t *)(v4 - 24) = v12;
    *(int32_t *)(v4 - 32) = v11;
    *(int32_t *)(v4 - 36) = v10 + v7;
    *v18 = *v18 + v19;
    g1 = result;
    return result;
}

// Address range: 0x1000175c - 0x10001780
int32_t function_1000175c(void) {
    unsigned char v1 = *(char *)-0x7fe3f000; // 0x1000175d
    int32_t v2; // 0x1000175c
    int32_t v3; // 0x1000175c
    *(char *)v2 = (char)v3;
    int32_t v4; // 0x1000175c
    char * v5 = (char *)(v4 & -256 | (int32_t)v1); // 0x10001763
    uint32_t v6; // 0x1000175c
    char v7 = v6; // 0x10001763
    char v8 = *v5 + v7; // 0x10001763
    *v5 = v8;
    int32_t result; // 0x1000175c
    if (v8 == 0) {
        result = function_1000170c();
    }
    // 0x10001768
    *(char *)result = v1 + v7;
    *(int32_t *)-0x7c57b765 = result;
    unsigned char v9 = *v5; // 0x1000176f
    unsigned char v10 = v9 + (char)result; // 0x1000176f
    *v5 = v10;
    char * v11 = (char *)(result - 0x1aefff60); // 0x10001772
    *v11 = *v11 + (char)(v6 / 256) + (char)(v10 < v9);
    return result;
}

// Address range: 0x100017c1 - 0x100017cc
int32_t Logon(void) {
    // 0x100017c1
    int32_t v1; // 0x100017c1
    int32_t v2; // 0x100017c1
    *(char *)v1 = __asm_insb((int16_t)v2);
    int32_t result; // 0x100017c1
    int32_t v3; // 0x100017c1
    if ((char)v3 >= 0) {
        result = function_1000175c();
    }
    // 0x100017cc
    return result;
}

// Address range: 0x100017cd - 0x100017e1
int32_t Logoff(int32_t result, int32_t a2, int32_t a3) {
    // 0x100017cd
    int32_t v1; // 0x100017cd
    __asm_in((int16_t)v1);
    return result;
}

// Address range: 0x100017e1 - 0x100017f8
int32_t function_100017e1(void) {
    // 0x100017e1
    int32_t v1; // 0x100017e1
    int32_t v2; // 0x100017e1
    *(int32_t *)v1 = __asm_insd((int16_t)v2);
    int32_t v3; // 0x100017e1
    *(int32_t *)0x5805ada7 = v3 & -256 | (int32_t)__asm_in_4(5);
    int32_t v4; // 0x100017e1
    int32_t v5; // 0x100017e1
    bool v6; // 0x100017e1
    return function_d3e9f723(v5, (v6 ? -4 : 4) + v4);
}

// Address range: 0x10001826 - 0x1000186b
int32_t Activate(void) {
    // 0x10001826
    int32_t v1; // 0x10001826
    int32_t v2; // 0x10001826
    *(int32_t *)v2 = v2 + v1;
    *(char *)0x69e622ec = *(char *)0x69e622ec + 1;
    int32_t v3 = __asm_int3(); // 0x1000183b
    unsigned char v4 = *(char *)-0x1b22f000; // 0x1000183c
    int32_t v5 = v3 & -256; // 0x1000183c
    *(int32_t *)((v5 | (int32_t)v4) - 50) = v2 & -0xff01 | 0xd500;
    unsigned char v6 = v4 + 86; // 0x10001846
    int32_t v7 = v5 | (int32_t)v6; // 0x10001846
    int32_t v8; // 0x10001826
    int32_t v9 = v8 + 1; // 0x10001848
    __asm_arpl(*(int16_t *)(v7 - 0x77efff30), (int16_t)v9);
    *(char *)-0x509266f6 = v6;
    int32_t v10 = __asm_int1(); // 0x10001860
    *(char *)v9 = (char)v10;
    bool v11; // 0x10001826
    *(int32_t *)((v11 ? -1 : 1) + v9) = *(int32_t *)-0x37735bd9;
    int32_t v12; // 0x10001826
    int32_t v13 = *(char *)(v7 + 0x55f6448d) > (char)v12 ? 0x426dd72b : 0x426dd72a; // 0x10001864
    return v10 + v13;
}

// Address range: 0x1000186b - 0x100018cb
int32_t function_1000186b(void) {
    unsigned char v1 = *(char *)-0x1623f000; // 0x10001881
    int32_t v2; // 0x1000186b
    int32_t v3 = __asm_bound(*(int64_t *)(v2 + 0x3eefff9f & -256 | (int32_t)v1)); // 0x10001888
    int32_t v4; // 0x1000186b
    char * v5 = (char *)(v4 + 37); // 0x1000188a
    unsigned char v6 = *v5; // 0x1000188a
    int32_t v7; // 0x1000186b
    unsigned char v8 = v6 + (char)v7; // 0x1000188a
    unsigned char v9 = v8 + (char)(v1 < 72); // 0x1000188a
    bool v10 = v1 < 72 ? v9 <= v6 : v8 < v6; // 0x1000188a
    *v5 = v9;
    int32_t v11 = __asm_bound(*(int64_t *)(v3 - 1)); // 0x1000188e
    int32_t v12; // 0x1000186b
    char * v13 = (char *)(v12 - 0x2ce9f4fb); // 0x10001890
    *v13 = *v13 + (char)v7 + (char)v10;
    char * v14 = (char *)(v11 - 0x35c9f000); // 0x10001897
    char v15 = *v14; // 0x10001897
    *v14 = 2 * v15;
    int32_t v16 = v4 + (int32_t)&g4 + (int32_t)(v15 < 0); // 0x1000189e
    int32_t v17; // 0x1000186b
    char v18 = *(char *)&v7 | (char)v17; // 0x100018a3
    *(char *)v7 = v18;
    *(char *)v11 = *(char *)0x2f076a94;
    bool v19; // 0x1000186b
    int32_t v20 = v19 ? -1 : 1; // 0x100018aa
    int32_t v21 = v20 + 0x2f076a94; // 0x100018aa
    char * v22 = (char *)(v16 + 81); // 0x100018ae
    unsigned char v23 = *v22; // 0x100018ae
    *v22 = 2 * v23;
    *(char *)(v20 + 0x2f076a7e) = (char)v16;
    if (v18 < 0 == ((v23 / 64 & 1) != v23 / 128)) {
        // 0x100018bf
        return v16 & -256 | (int32_t)*(char *)v21;
    }
    int32_t v24; // 0x1000186b
    if (v24 == 1 || v18 == 0) {
        int32_t result = v16 + 1; // 0x100018b9
        *(char *)(v11 + v20) = *(char *)v21;
        char * v25 = (char *)result; // 0x100018bb
        *v25 = *v25 + (char)v7;
        return result;
    }
    // 0x100018c1
    return unknown_a06c3f(v7);
}

// Address range: 0x100018e7 - 0x100019da
int32_t entry_point(int32_t a1) {
    int32_t v1 = a1;
    int32_t v2; // 0x100018e7
    int32_t v3; // 0x100018e7
    int32_t v4; // 0x100018e7
    int32_t v5; // 0x100018e7
    int32_t v6; // 0x100018e7
    int32_t v7; // 0x100018e7
    int32_t result; // 0x100018e7
    __asm_rdtsc(v2, v3, v4, &v1, v5, v6, v7, result);
    __asm_rdtsc_1();
    if ((int16_t)result == 736) {
        // 0x100018fe
        return result;
    }
    // 0x100018ff
    v1 += 0xd6eb;
    int32_t v8 = __readfsdword(0); // 0x1000194e
    int32_t v9 = v8; // bp-4, 0x1000195f
    __writefsdword(0, (int32_t)&v9);
    for (int32_t i = 0x10000; i > 0; i--) {
        // continue -> 0x1000199b
    }
    int32_t * v10 = (int32_t *)i; // 0x100019be
    *v10 = *v10 ^ v4;
    unsigned char v11 = *(char *)0x58e11000; // 0x100019c0
    int32_t result2 = v8 & -256 | (int32_t)v11; // 0x100019c0
    *(char *)0x6f1e1000 = v11;
    char * v12 = (char *)result2; // 0x100019d4
    unsigned char v13 = *v12; // 0x100019d4
    *v12 = v13 / 128 | 2 * v13;
    return result2;
}

// Address range: 0x100019db - 0x100019df
int32_t function_100019db(int32_t a1) {
    // 0x100019db
    int32_t v1; // 0x100019db
    __asm_in((int16_t)v1);
    return function_10001a1c((int32_t)&g6);
}

// Address range: 0x100019e0 - 0x10001a08
int32_t function_100019e0(unsigned char a1) {
    // 0x100019e0
    uint32_t v1; // 0x100019e0
    unsigned char v2 = (char)v1 & 31; // 0x100019e5
    bool v3; // 0x100019e0
    if (v2 != 0) {
        v3 = ((a1 >> 8 - v2 | a1 << v2) & 1) != 0;
    }
    int32_t v4; // 0x100019e0
    char * v5 = (char *)(v4 + 53); // 0x100019ea
    *v5 = (char)v3 - (char)(v1 / 256) + *v5;
    return *(int32_t *)0x4505c0cf;
}

// Address range: 0x10001a08 - 0x10001a0b
int32_t function_10001a08(int32_t a1) {
    // 0x10001a08
    int32_t v1; // 0x10001a08
    int32_t v2; // 0x10001a08
    *(char *)v1 = (char)v2;
    int32_t result; // 0x10001a08
    return result;
}

// Address range: 0x10001a1c - 0x10001a3f
int32_t function_10001a1c(int32_t a1) {
    // 0x10001a1c
    int32_t v1; // 0x10001a1c
    bool v2; // 0x10001a1c
    int32_t v3 = (v1 + 44 + (int32_t)v2 & 255 | v1 & -256) ^ (int32_t)&g3; // 0x10001a1e
    int32_t v4; // 0x10001a1c
    if (v3 >= 1) {
        // 0x10001a25
        v4 = *(int32_t *)v3;
    }
    char * v5 = (char *)v3; // 0x10001a28
    unsigned char v6 = *v5; // 0x10001a28
    int32_t v7; // 0x10001a1c
    char v8 = v7; // 0x10001a28
    unsigned char v9 = v6 + v8; // 0x10001a28
    *v5 = v9;
    int32_t v10 = v3; // 0x10001a2a
    if (v9 >= v6) {
        v10 = function_10001a7f();
    }
    unsigned char v11 = (char)v10; // 0x10001a30
    char v12 = (v4 & 256) != 0 ? 89 : 88; // 0x10001a30
    char v13 = (v4 & 256) != 0 ? v12 + v11 <= v11 : v11 > 167 ? 97 : 96; // 0x10001a37
    int32_t result = v10 & -256 | (int32_t)(*(char *)0x45a51000 - v13); // 0x10001a37
    char * v14 = (char *)result; // 0x10001a39
    *v14 = *v14 + v8;
    return result;
}

// Address range: 0x10001a43 - 0x10001a45
int32_t HookProc(int32_t a1) {
    // 0x10001a43
    int32_t result; // 0x10001a43
    return result;
}

// Address range: 0x10001a7f - 0x10001aa4
int32_t function_10001a7f(void) {
    // 0x10001a7f
    int32_t v1; // 0x10001a7f
    int32_t v2; // 0x10001a7f
    __asm_outsd((int16_t)v2, v1);
    *(int32_t *)-0x50db9e0b = -1 - *(int32_t *)-0x50db9e0b;
    int16_t v3; // 0x10001a7f
    return 256 * (int32_t)(*(char *)0x3e3e1000 / 74) | (int32_t)v3 & -0x10000;
}

// Address range: 0x10001aa6 - 0x10001aae
int32_t function_10001aa6(void) {
    int32_t v1 = *(int32_t *)-0x7e00f000; // 0x10001aa6
    return v1 + 192 & 255 | v1 & -256;
}

// Address range: 0x10001aae - 0x1000b7ec
int32_t Start(int16_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19, int32_t a20, int32_t a21) {
    // 0x10001aae
    uint32_t v1; // 0x10001aae
    int32_t v2 = __asm_in((int16_t)v1); // 0x10001ab0
    int32_t v3; // 0x10001aae
    uint32_t v4; // 0x10001aae
    int32_t v5; // 0x10001aae
    bool v6; // 0x10001aae
    if (v5 == -109) {
        int32_t * v7 = (int32_t *)(v3 - 63); // 0x10001af7
        *v7 = *v7 & 15;
        int32_t v8; // 0x10001aae
        char * v9 = (char *)(v8 - 16); // 0x10001afb
        *v9 = *v9 & -41;
        __asm_int1();
        uint32_t v10 = __asm_iretd(); // 0x10001b01
        char * v11 = (char *)(v1 - 23); // 0x10001b02
        *v11 = *v11 + (char)(v4 / 256);
        int32_t v12 = 171 * v10 / 256 + v10; // 0x10001b05
        int32_t v13 = v10 & -0x10000; // 0x10001b05
        int32_t v14 = v12 & 255 | v13; // 0x10001b05
        __asm_fbld(0.0L);
        char * v15 = (char *)(v4 - 23); // 0x10001b12
        *v15 = *v15 + (char)v4;
        uint32_t v16 = *(int32_t *)(v14 + 0x11000a1); // 0x10001b15
        *(int32_t *)v1 = v1 / 0x8000 | 0x40000 * v1 | 0x20000 * (int32_t)(v16 < v8 + 1);
        *(int32_t *)0xa4ece8 = v14;
        unsigned char v17 = *((v6 ? (char *)0xa4ece4 : (char *)0xa4ecec)); // 0x10001b1f
        return v12 + 42 + (int32_t)(v17 > (char)v12) & 255 | v13;
    }
    int32_t v18 = v3 - v4; // 0x10001ac0
    char v19 = llvm_ctpop_i8((char)v18); // 0x10001ac0
    *(int32_t *)v3 = v18;
    int32_t v20 = v2; // 0x10001ac2
    if ((v19 & 1) == 0) {
        v20 = function_10001aa6();
    }
    int32_t v21 = v20;
    int32_t v22; // bp-1, 0x10001aae
    int32_t v23 = &v22; // 0x10001ac5
    int32_t result2 = v21 & -256 | (int32_t)*(char *)((v21 & 255) + v4); // 0x10001ac5
    int32_t v24; // 0x10001aae
    *(int32_t *)v24 = result2;
    int32_t v25 = v23 - 8; // 0x10001ac8
    *(int32_t *)v25 = -71;
    result2 += 0x26efff9e;
    while (result2 == 0) {
        int32_t v26 = v24 + (v6 ? -4 : 4); // 0x10001ac6
        v23 -= 3;
        v24 = v26;
        if ((llvm_ctpop_i8((char)v25 + 1) & 1) != 0) {
            unsigned char v27 = *(char *)((result2 & 255) + v4); // 0x10001ade
            uint32_t v28 = *(int32_t *)v26; // 0x10001adf
            int32_t result = __asm_int1(); // 0x10001ae0
            char * v29 = (char *)(v1 - 0x332d65c); // 0x10001ae6
            char v30 = *v29; // 0x10001ae6
            *v29 = v30 + (char)v4 + (char)((result2 & -256 | (int32_t)v27) < v28);
            return result;
        }
        *(int32_t *)v24 = result2;
        v25 = v23 - 8;
        *(int32_t *)v25 = -71;
        result2 += 0x26efff9e;
    }
    // 0x260b2068
    return result2;
}

// Address range: 0x1000f000 - 0x1000f06f
int32_t function_1000f000(int32_t a1) {
    // 0x1000f000
    int32_t v1; // 0x1000f000
    *(int32_t *)(v1 + 184) = a1 + 89;
    return 0;
}

// Address range: 0x1000f06f - 0x1000f0d4
int32_t function_1000f06f(int32_t a1) {
    // 0x1000f06f
    __writefsdword(0, a1);
    int32_t v1; // 0x1000f06f
    int32_t v2; // 0x1000f06f
    int32_t v3; // 0x1000f06f
    int32_t v4; // 0x1000f06f
    return function_1000f0dc(v4, v3, v1, v2);
}

// Address range: 0x1000f0d6 - 0x1000f0dc
int32_t function_1000f0d6(void) {
    // 0x1000f0d6
    int32_t v1; // 0x1000f0d6
    int32_t result; // 0x1000f0d6
    *(int32_t *)v1 = result + v1;
    return result;
}

// Address range: 0x1000f0dc - 0x1000f3d3
int32_t function_1000f0dc(int32_t a1, int32_t a2, int32_t result, int32_t a4) {
    int32_t v1 = a1 - 28 + (int32_t)*(int16_t *)(a1 - 22); // 0x1000f13e
    uint16_t v2 = *(int16_t *)(a1 - 20); // 0x1000f16b
    int32_t v3 = *(int32_t *)(a1 - 26); // 0x1000f1c7
    int32_t v4 = 0; // 0x1000f1c7
    int32_t * v5 = (int32_t *)(4 * v4 + v1); // 0x1000f1c8
    *v5 = *v5 ^ v3;
    uint32_t v6 = v3 / 2; // 0x1000f1d8
    v4++;
    v3 = v6 & 0x7fffff00 | 0x80000000 * v3 | v6 & 255;
    while (v4 < (int32_t)(v2 / 4)) {
        // 0x1000f1c8
        v5 = (int32_t *)(4 * v4 + v1);
        *v5 = *v5 ^ v3;
        v6 = v3 / 2;
        v4++;
        v3 = v6 & 0x7fffff00 | 0x80000000 * v3 | v6 & 255;
    }
    int32_t v7; // 0x1000f0dc
    switch ((int32_t)(v2 % 4)) {
        case 1: {
            char * v8 = (char *)(4 * v4 + v1); // 0x1000f39d
            *v8 = *v8 ^ (char)v6;
        }
        case 0: {
          lab_0x1000f2c1:
            // 0x1000f2c1
            v7 = a2;
            // break -> 0x1000f2c1
            break;
        }
        case 2: {
            int16_t * v9 = (int16_t *)(4 * v4 + v1); // 0x1000f3be
            *v9 = *v9 ^ (int16_t)v3;
            // branch (via goto) -> 0x1000f2c1
            goto lab_0x1000f2c1;
        }
        default: {
            int32_t v10 = 4 * v4 + v1;
            int16_t * v11 = (int16_t *)v10; // 0x1000f293
            *v11 = *v11 ^ (int16_t)v3;
            char * v12 = (char *)(v10 + 2); // 0x1000f2b1
            *v12 = *v12 ^ (char)(v3 / 2);
            // branch (via goto) -> 0x1000f2c1
            goto lab_0x1000f2c1;
        }
    }
    while (true) {
        int32_t v13 = v7;
        int32_t v14; // 0x1000f0dc
        if (*(int16_t *)v13 == 0x5a4d) {
            int32_t v15 = v13 + 60; // 0x1000f31c
            int32_t v16 = v15 & -0x10000 | (int32_t)*(int16_t *)v15; // 0x1000f32c
            v14 = v16;
            if (*(int16_t *)v16 == 0x4550) {
                // break -> 0x1000f354
                break;
            }
        } else {
            // 0x1000f2d9
            v14 = v13 - 0x1000 & -0x10000;
        }
        // 0x1000f2c1
        v7 = v14;
    }
    // 0x1000f354
    return result;
}

// Address range: 0x1000f3d3 - 0x1000f469
int32_t function_1000f3d3(int16_t a1) {
    // 0x1000f3d3
    int32_t v1; // 0x1000f3d3
    char v2 = v1; // 0x1000f3d4
    int32_t v3; // 0x1000f3d3
    char v4 = *(char *)(v3 + 0xb09c45 + 4 * v3); // 0x1000f3d4
    unsigned char v5 = v2 - v4; // 0x1000f3d4
    int32_t v6; // 0x1000f3d3
    if ((llvm_ctpop_i8(v5) & 1) != 0) {
        // 0x1000f3ec
        int32_t v7; // 0x1000f3d3
        char * v8 = (char *)(v7 - 73); // 0x1000f3ec
        *v8 = *v8 & 66;
        int32_t * v9 = (int32_t *)((*(int32_t *)0x50ba0160 & -256) - 76); // 0x1000f40a
        *v9 = *v9 | v6;
        int16_t v10; // 0x1000f3d3
        int32_t v11 = __asm_fsetpm(41, a1, v10); // 0x1000f415
        __asm_int(160);
        *(int32_t *)0x51a1b879 = v11;
        return function_82065723();
    }
    int32_t v12 = v1 & -256 | (int32_t)v5; // 0x1000f3d4
    int32_t v13 = v3 & -256; // 0x1000f3de
    int32_t v14; // 0x1000f3d3
    int32_t result = v13 | (int32_t)*(char *)((v3 & 255) + v14); // 0x1000f3de
    int32_t * v15 = (int32_t *)v12; // 0x1000f3df
    uint32_t v16 = *v15; // 0x1000f3df
    *v15 = v16 / 4 | 0x40000000 * v16;
    if (v12 != 1 != (v5 == 0)) {
        // 0x1000f3e4
        return result | v6;
    }
    if (((v5 ^ v2) & (v4 ^ v2)) >= 0) {
        // 0x1000f45b
        return result;
    }
    // 0x1000f45c
    uint32_t v17; // 0x1000f3d3
    *(int32_t *)v17 = __asm_insd((int16_t)v6);
    int32_t v18; // 0x1000f3d3
    uint32_t result2 = v13 | (int32_t)*(char *)&v18; // 0x1000f45d
    int32_t * v19 = (int32_t *)(4 * result2 + v14); // 0x1000f462
    *v19 = *v19 + 0x5081c05b + (int32_t)(result2 < v17);
    return result2;
}

// Address range: 0x1000f479 - 0x1000f47b
int32_t function_1000f479(void) {
    // 0x1000f479
    return function_1000f4f3((int32_t)&g6);
}

// Address range: 0x1000f49b - 0x1000f4b2
int32_t function_1000f49b(void) {
    // 0x1000f49b
    int32_t v1; // 0x1000f49b
    int32_t v2; // 0x1000f49b
    *(int32_t *)v2 = v2 | v1;
    float80_t v3; // 0x1000f49b
    *(int32_t *)v1 = (int32_t)v3;
    int32_t v4; // 0x1000f49b
    return v4 & -100;
}

// Address range: 0x1000f4bb - 0x1000f4cc
int32_t function_1000f4bb(int32_t a1) {
    int32_t v1 = unknown_3db9644a(); // 0x1000f4be
    int32_t v2; // 0x1000f4bb
    *(char *)-0x7e7d02f6 = *(char *)-0x7e7d02f6 & (char)v2;
    return v1 - 1;
}

// Address range: 0x1000f4cf - 0x1000f4d4
int32_t function_1000f4cf(void) {
    // 0x1000f4cf
    return function_f2583fc2();
}

// Address range: 0x1000f4f3 - 0x1000f592
int32_t function_1000f4f3(int32_t a1) {
    // 0x1000f4f3
    uint32_t v1; // 0x1000f4f3
    *(char *)0x581595e5 = *(char *)0x581595e5 - (char)(v1 / 256);
    uint32_t v2; // 0x1000f4f3
    char * v3 = (char *)(v2 + 0x190b5828); // 0x1000f4f9
    unsigned char v4 = (char)(v2 / 256); // 0x1000f4f9
    *v3 = *v3 + v4;
    int32_t v5; // 0x1000f4f3
    int32_t v6; // 0x1000f4f3
    *(char *)v6 = *(char *)&v5;
    bool v7; // 0x1000f4f3
    int32_t v8 = (v7 ? -1 : 1) + v6; // 0x1000f4ff
    uint32_t v9 = *(int32_t *)(v2 + 0x1d600eec); // 0x1000f502
    char v10 = v2 < v9; // 0x1000f508
    unsigned char v11 = v4 - 70 + v10; // 0x1000f508
    bool v12 = v2 < v9 ? v11 <= v4 : v4 > 69; // 0x1000f508
    int32_t v13; // 0x1000f4f3
    v5 = v13 - 0x4bd7c00;
    int32_t v14 = (v4 & 15) + 10 + v10 > 15 | v12; // 0x1000f512
    int32_t v15 = 256 * v14 + v1 & 0xff00 | v1 & -0x10000; // 0x1000f512
    uint32_t v16; // 0x1000f4f3
    unsigned char v17 = __asm_insb((int16_t)v16); // 0x1000f513
    *(char *)v8 = v17;
    int32_t * v18 = (int32_t *)(v8 - 0x24ad144a); // 0x1000f516
    int32_t v19 = *v18; // 0x1000f516
    uint32_t v20 = v19 + v8 + v14; // 0x1000f516
    *v18 = v20;
    if (v20 >= 0) {
        // 0x1000f51e
        *(char *)(v8 & 0xffff) = *(char *)(v5 & 0xffff);
        int32_t v21 = v5;
        int32_t * v22 = (int32_t *)((v21 + (v7 ? 0xffff : 1) & 0xffff | v21 & -0x10000) + 0x6a880944); // 0x1000f523
        int32_t v23 = *v22; // 0x1000f523
        int32_t v24 = v23 - v16; // 0x1000f523
        *v22 = v24;
        int32_t result = v15 | (int32_t)v17; // 0x1000f529
        if (((v24 ^ v23) & (v23 ^ v16)) < 0) {
            result = function_fffff552();
        }
        // 0x1000f52c
        return result;
    }
    int32_t v25 = 256 * (int32_t)v11 | v2 & -0xff01; // 0x1000f508
    int32_t v26 = v20 + v14; // 0x1000f516
    int32_t v27 = v8 & 15; // 0x1000f516
    int32_t result2 = v15; // 0x1000f553
    while (((v26 ^ v19) & (v26 ^ v8)) < 0) {
        // 0x1000f553
        int32_t v28; // 0x1000f4f3
        int32_t v29 = v28 + 2; // 0x1000f550
        result2 = result2 & -256 | (int32_t)__asm_in_4(-93);
        v28 = v29;
        if (v25 != 0) {
            // 0x1000f557
            *(int32_t *)-0x67e67475 = v29;
            *(int32_t *)(*(int32_t *)-0x67e67475 - 4) = v8;
            return result2;
        }
    }
    // 0x1000f560
    __asm_int(128);
    *(char *)(v25 + 0x2f21b431) = (char)(v16 / 256);
    int32_t v30 = __asm_hlt(); // 0x1000f573
    char * v31 = (char *)v5; // 0x1000f574
    unsigned char v32 = *v31; // 0x1000f574
    *v31 = v32 / 2 | 128 * v32;
    char v33 = __asm_in_4(18); // 0x1000f576
    int32_t v34 = v8 - 1; // 0x1000f581
    char v35 = llvm_ctpop_i8((char)v34); // 0x1000f581
    bool v36; // 0x1000f4f3
    int32_t v37; // 0x1000f4f3
    bool v38; // 0x1000f4f3
    bool v39; // 0x1000f4f3
    *(int32_t *)(v37 - 2) = 0x4000 * (int32_t)v38 | 1024 * (int32_t)v7 | 512 * (int32_t)v39 | 256 * (int32_t)v36 | 64 * (int32_t)(v34 == 0) | 128 * (int32_t)(v34 < 0) | 2048 * (int32_t)((v8 & -v8) < 0) | 16 * (int32_t)(v27 > 16) | 4 * (int32_t)((v35 & 1) == 0) | (int32_t)((v30 & -256 | (int32_t)v33) < 0x9c59df97) | 2;
    return function_1000f5c7();
}

// Address range: 0x1000f592 - 0x1000f5a1
int32_t function_1000f592(void) {
    // 0x1000f592
    int32_t v1; // 0x1000f592
    int16_t v2 = v1; // 0x1000f596
    char v3 = __asm_in_5(v2); // 0x1000f596
    int32_t v4; // 0x1000f592
    char * v5 = (char *)v4; // 0x1000f597
    int32_t v6; // 0x1000f592
    int32_t v7; // 0x1000f592
    *v5 = (char)(v7 + v6) + (char)v4;
    *v5 = __asm_insb(v2);
    int32_t v8; // 0x1000f592
    return v8 + 1 & -256 | (int32_t)v3;
}

// Address range: 0x1000f5a1 - 0x1000f5ad
int32_t function_1000f5a1(void) {
    // 0x1000f5a1
    int32_t v1; // 0x1000f5a1
    int32_t v2; // 0x1000f5a1
    __asm_outsd((int16_t)v2, v1);
    int32_t v3; // 0x1000f5a1
    *(char *)v3 = (char)v1;
    bool v4; // 0x1000f5a1
    int32_t v5 = (v4 ? -1 : 1) + v1; // 0x1000f5a2
    int32_t * v6 = (int32_t *)(v5 + 0x69880b5d); // 0x1000f5a3
    bool v7; // 0x1000f5a1
    *v6 = (int32_t)v7 - v2 + *v6;
    int32_t result; // 0x1000f5a1
    __asm_arpl(*(int16_t *)(result + 49), (int16_t)v5);
    return result;
}

// Address range: 0x1000f5b0 - 0x1000f5b3
int32_t function_1000f5b0(void) {
    // 0x1000f5b0
    int32_t v1; // 0x1000f5b0
    bool v2; // 0x1000f5b0
    return v1 & -256 | (int32_t)v2 | 2 * v1 & 254;
}

// Address range: 0x1000f5b7 - 0x1000f5c0
int32_t function_1000f5b7(int32_t a1) {
    // 0x1000f5b7
    int32_t v1; // 0x1000f5b7
    unsigned char v2 = (char)v1;
    uint32_t v3; // 0x1000f5b7
    unsigned char v4 = (char)(v3 / 256); // 0x1000f5b7
    *(char *)v1 = v2 - v4;
    return v3 - (v2 < v4 ? 0x79e28f01 : 0x79e28f00);
}

// Address range: 0x1000f5c7 - 0x1000f5da
int32_t function_1000f5c7(void) {
    // 0x1000f5c7
    int32_t v1; // 0x1000f5c7
    int32_t v2 = v1 + 4; // 0x1000f5d0
    int32_t v3; // 0x1000f5c7
    char v4 = *(char *)((v3 & -256 | 93) + v1); // 0x1000f5d5
    return v2 & -256 | (int32_t)(v4 & (char)v2);
}

// Address range: 0x1000f620 - 0x1000f6a1
int32_t function_1000f620(int32_t a1) {
    // 0x1000f620
    uint32_t v1; // 0x1000f620
    unsigned char v2 = (char)(v1 / 256); // 0x1000f620
    int32_t v3; // 0x1000f620
    unsigned char v4 = (char)v3;
    unsigned char v5 = v2 + v4; // 0x1000f620
    uint32_t v6; // 0x1000f620
    __asm_out_6((int16_t)v6, v4);
    int32_t v7 = (256 * (int32_t)v5 | v1 & -0xff01) + 1; // 0x1000f624
    char v8 = v7; // 0x1000f625
    char v9 = v5 < v2; // 0x1000f625
    int32_t v10; // 0x1000f620
    char v11 = *(char *)(v10 + 0x50a91f0) + v9; // 0x1000f625
    int32_t v12; // 0x1000f620
    *(int32_t *)v12 = v12 / 0x8000;
    bool v13 = v4 > 153 | (v12 & 0x4000) != 0;
    int32_t v14; // 0x1000f620
    if ((v4 & 14) > 9 || (v8 & 15) + v9 - (v11 & 15) > 15) {
        v14 = (v13 ? 102 : 6) + v3 & 255 | v3 & -256;
    } else {
        v14 = (v13 ? v3 + 96 : v3) & 255 | v3 & -256;
    }
    unsigned char v15 = v8 - v11; // 0x1000f625
    int32_t v16; // 0x1000f620
    int32_t * v17 = (int32_t *)(v16 + 6); // 0x1000f638
    int32_t v18; // 0x1000f620
    *v17 = (int32_t)v13 - v18 + *v17;
    int32_t v19 = v14 ^ 95; // 0x1000f63f
    char * v20 = (char *)(v16 - 0x5ffa5a8b); // 0x1000f641
    char v21 = v14 / 256; // 0x1000f641
    *v20 = *v20 | v21;
    unsigned char v22 = v15 & 31; // 0x1000f647
    if (v22 != 0) {
        char * v23 = (char *)v19; // 0x1000f647
        unsigned char v24 = *v23; // 0x1000f647
        *v23 = v24 >> v22 | v24 << 8 - v22;
    }
    uint32_t v25 = v6 / 256; // 0x1000f649
    int32_t v26 = v19 & -16; // 0x1000f64b
    int32_t v27; // 0x1000f620
    __asm_into(v27);
    *(char *)0x5fdafbe3 = (char)v6;
    char * v28 = (char *)((v6 & -0xff01 ^ 968) + 11); // 0x1000f65c
    *v28 = *v28 - (char)v25;
    int16_t v29 = v26; // 0x1000f65f
    __asm_outsd(v29, v10);
    *(char *)v16 = (char)v10;
    bool v30; // 0x1000f620
    int32_t v31 = (v30 ? -5 : 5) + v16; // 0x1000f661
    char * v32 = (char *)(v7 & -256 | (int32_t)v15); // 0x1000f662
    *v32 = *v32 | v21;
    char * v33 = (char *)v26; // 0x1000f666
    *v33 = *v33 & v15;
    int32_t * v34 = (int32_t *)(v26 - 68); // 0x1000f675
    *v34 = *v34 + (v26 | 1);
    *(int32_t *)(v31 + 1) = __asm_insd(v29 | 2);
    return *(int32_t *)v31 ^ v25 & 255;
}

// Address range: 0x1000f6cf - 0x1000f703
int32_t function_1000f6cf(void) {
    // 0x1000f6cf
    __asm_out_7(66, (char)__asm_int1());
    int32_t v1 = unknown_b5361f2a(); // 0x1000f6d2
    int32_t v2; // 0x1000f6cf
    uint32_t v3 = v2 & 31; // 0x1000f6dd
    int32_t v4; // 0x1000f6cf
    if (v3 != 0) {
        uint32_t v5; // 0x1000f6cf
        v4 = v5 >> 32 - v3 | v5 << v3;
    }
    int32_t v6; // 0x1000f6cf
    int32_t v7 = v6 + 1; // 0x1000f6e4
    __asm_out_7(241, (char)v1);
    int32_t v8; // 0x1000f6cf
    int32_t * v9 = (int32_t *)(v8 - 4); // 0x1000f6f7
    *v9 = v1;
    int32_t v10; // 0x1000f6cf
    *(int32_t *)v7 = *(int32_t *)v10;
    bool v11; // 0x1000f6cf
    int32_t v12 = v11 ? -4 : 4; // 0x1000f6fb
    int32_t v13 = v12 + v7; // 0x1000f6fb
    int32_t result = v1 | 129; // 0x1000f6fc
    *(int32_t *)v13 = result;
    int32_t v14 = *v9; // 0x1000f6ff
    if ((char)v14 < 0) {
        // 0x1000f702
        return result;
    }
    int32_t v15; // 0x1000f6cf
    int32_t v16 = v15 + v12; // 0x1000f6fb
    int32_t v17 = (v14 & 1) != 0; // 0x1000f6ea
    int32_t v18 = *(int32_t *)v4; // 0x1000f6ef
    int32_t v19 = v4 + 4; // 0x1000f6ef
    int32_t v20 = v13 - 4 + v12; // 0x1000f6f6
    *(int32_t *)v20 = 0x1e4232f;
    int32_t * v21 = (int32_t *)(v20 - 4); // 0x1000f6f7
    *v21 = v19;
    *(int32_t *)v17 = *(int32_t *)v16;
    int32_t v22 = (v14 & 1024) == 0 ? 4 : -4; // 0x1000f6fb
    int32_t v23 = v22 + v17; // 0x1000f6fb
    int32_t result2 = v19 | 129; // 0x1000f6fc
    *(int32_t *)v23 = result2;
    int32_t v24 = *v21; // 0x1000f6ff
    while ((char)v24 >= 0) {
        int32_t v25 = v18;
        v16 += v22;
        v17 = (v24 & 1) != 0;
        v18 = *(int32_t *)v25;
        v19 = v25 + 4;
        v20 = v23 - 4 + v22;
        *(int32_t *)v20 = 0x1e4232f;
        v21 = (int32_t *)(v20 - 4);
        *v21 = v19;
        *(int32_t *)v17 = *(int32_t *)v16;
        v22 = (v24 & 1024) == 0 ? 4 : -4;
        v23 = v22 + v17;
        result2 = v19 | 129;
        *(int32_t *)v23 = result2;
        v24 = *v21;
    }
    // 0x1000f702
    return result2;
}

// Address range: 0x1000f711 - 0x1000f715
int32_t function_1000f711(void) {
    // 0x1000f711
    int32_t v1; // 0x1000f711
    *(char *)v1 = (unsigned char)(char)v1 / 2;
    return function_1000f761();
}

// Address range: 0x1000f721 - 0x1000f724
int32_t function_1000f721(int32_t a1) {
    // 0x1000f721
    int32_t result; // 0x1000f721
    return result;
}

// Address range: 0x1000f761 - 0x1000f763
int32_t function_1000f761(void) {
    // 0x1000f761
    int32_t v1; // 0x1000f761
    return &v1;
}

// Address range: 0x1000f763 - 0x1000f770
int32_t function_1000f763(int32_t a1) {
    // 0x1000f763
    int32_t v1; // 0x1000f763
    int32_t v2; // 0x1000f763
    __asm_out_6((int16_t)v2, (char)v1);
    int32_t v3; // 0x1000f763
    *(char *)v2 = (char)(v3 & v2);
    return v1 + 183 & 255 | v1 & -256;
}

// Address range: 0x1000f770 - 0x1000f7b2
int32_t function_1000f770(void) {
    // 0x1000f770
    int32_t v1; // 0x1000f770
    int32_t v2 = &v1; // 0x1000f770
    int32_t v3; // 0x1000f770
    *(char *)v3 = (char)v2;
    bool v4; // 0x1000f770
    int32_t v5 = v4 ? -1 : 1; // 0x1000f771
    char v6 = __asm_in_4(-48); // 0x1000f773
    char * v7 = (char *)(v5 + v3); // 0x1000f775
    int32_t v8; // 0x1000f770
    *v7 = (char)v8;
    char v9 = __asm_in_5((int16_t)v8); // 0x1000f777
    int32_t v10 = ((int32_t)v6 | v2) & -256 | (int32_t)v9; // 0x1000f777
    int32_t v11; // 0x1000f770
    *v7 = *(char *)&v11;
    int32_t v12 = v11 + v5; // 0x1000f779
    unsigned char v13 = *(char *)v12; // 0x1000f77f
    int32_t v14 = v10 & -256; // 0x1000f77f
    int32_t v15 = v14 | (int32_t)v13; // 0x1000f77f
    int32_t v16 = __asm_bound(*(int64_t *)(v15 - 98)); // 0x1000f784
    int32_t v17; // 0x1000f770
    *(int32_t *)v17 = v15;
    int32_t v18 = v14 | (int32_t)(*(char *)(v10 + 0x791c4f4a) | v9); // 0x1000f78d
    int32_t * v19 = (int32_t *)(v18 + 39); // 0x1000f793
    *v19 = *v19 & v16;
    __asm_out_7(59, v13);
    *(int32_t *)(v17 - 12) = v18;
    *(int32_t *)(v17 - 20) = 0x9e00 - (v10 & 0xff00) & 0xff00 | 0xc540036;
    *(int32_t *)(v17 - 24) = v17 - 4;
    *(int32_t *)(v17 - 28) = v15;
    *(int32_t *)(v17 - 32) = v12 + v5;
    *(int32_t *)(v17 - 36) = v16;
    char v20 = __asm_in_4(-125); // 0x1000f7a5
    int32_t v21; // 0x1000f770
    return ((v21 | (int32_t)v20) & -256 | (int32_t)(v20 | -17)) + 0x5a17fee7;
}

// Address range: 0x1000f7b2 - 0x1000f7c2
int32_t function_1000f7b2(void) {
    // 0x1000f7b2
    int32_t v1; // 0x1000f7b2
    int32_t v2; // 0x1000f7b2
    *(char *)v1 = (char)v2;
    return function_69a25772();
}

// Address range: 0x1000f7c2 - 0x1000f7dd
int32_t function_1000f7c2(void) {
    int32_t v1 = __asm_hlt(); // 0x1000f7c4
    uint32_t v2; // 0x1000f7c2
    int32_t v3; // 0x1000f7c2
    uint32_t v4 = v3 + v2; // 0x1000f7c5
    int32_t * v5 = (int32_t *)(v4 - 11); // 0x1000f7c7
    int32_t v6; // 0x1000f7c2
    int32_t v7 = *v5 + (int32_t)(v4 < v2) - v6; // 0x1000f7c7
    *v5 = v7;
    int32_t v8 = v1; // 0x1000f7ca
    if (v6 != 1 && v7 != 0) {
        v8 = function_1000f763((int32_t)&g6);
    }
    int32_t v9 = v8;
    int32_t v10; // 0x1000f7c2
    return v9 & -256 | (int32_t)*(char *)((v9 & 255) + v10);
}

// Address range: 0x1000f7dd - 0x1000f835
int32_t function_1000f7dd(void) {
    // 0x1000f7dd
    bool v1; // 0x1000f7dd
    int32_t v2; // 0x1000f7dd
    int32_t v3; // 0x1000f7dd
    int32_t v4 = v3 - v2 + (int32_t)v1; // 0x1000f7dd
    int32_t v5; // 0x1000f7dd
    int32_t v6; // 0x1000f7dd
    __asm_outsd((int16_t)v6, v5);
    int32_t v7; // 0x1000f7dd
    *(char *)v7 = (char)v5;
    bool v8; // 0x1000f7dd
    int32_t v9 = v8 ? -1 : 1; // 0x1000f7e0
    int32_t v10 = v8 ? -4 : 4; // 0x1000f7e1
    int32_t v11 = (v8 ? -5 : 5) + v7; // 0x1000f7e1
    int32_t v12; // 0x1000f7dd
    int32_t v13 = v12 | 0x2c5e09e9; // 0x1000f7e2
    int32_t * v14 = (int32_t *)(v13 - 5); // 0x1000f7e7
    uint32_t v15 = *v14; // 0x1000f7e7
    *v14 = v15 - 0x58298ef;
    uint32_t v16 = v6 + 1; // 0x1000f7ef
    int32_t v17; // 0x1000f7dd
    __asm_into(v17);
    *(char *)(v4 & -0xff01 | 0x6600) = (char)v4;
    __asm_out_7(96, (char)v13 - 1);
    char * v18 = (char *)(v11 + 54); // 0x1000f7fb
    unsigned char v19 = *v18; // 0x1000f7fb
    unsigned char v20 = v19 + (v15 > 0x58298ee ? 89 : 88); // 0x1000f7fb
    *v18 = v20;
    int32_t v21 = v13 + 0x5fa18a1e + (int32_t)(v15 > 0x58298ee ? v20 <= v19 : v19 > 167); // 0x1000f7ff
    int32_t v22 = v11 + v9; // 0x1000f804
    *(int32_t *)v22 = v21;
    int32_t * v23 = (int32_t *)(v21 - 32); // 0x1000f80b
    *v23 = *v23 | v16;
    char * v24 = (char *)(v6 + 0x594d3bbf); // 0x1000f814
    *v24 = *v24 / 2;
    int16_t v25; // 0x1000f7dd
    int32_t v26 = unknown_a6e4e307(v25, v21); // 0x1000f823
    *(char *)(v22 + (v10 | 1)) = __asm_insb((int16_t)v16);
    *(char *)0x200d8245 = (char)(v16 / 256);
    return v26 & -256 | (int32_t)*(char *)(v10 + v5 + 2 * v9);
}

// Address range: 0x1000f855 - 0x1000f857
int32_t function_1000f855(void) {
    // 0x1000f855
    return function_1000f8a3();
}

// Address range: 0x1000f85e - 0x1000f85f
int32_t function_1000f85e(void) {
    // 0x1000f85e
    int32_t result; // 0x1000f85e
    return result;
}

// Address range: 0x1000f870 - 0x1000f873
int32_t function_1000f870(void) {
    // 0x1000f870
    int32_t result; // 0x1000f870
    return result;
}

// Address range: 0x1000f87a - 0x1000f87c
int32_t function_1000f87a(void) {
    // 0x1000f87a
    return function_1000f8a0();
}

// Address range: 0x1000f888 - 0x1000f8a0
int32_t function_1000f888(void) {
    // 0x1000f888
    function_1000f85e();
    int32_t v1; // 0x1000f888
    return *(int32_t *)(v1 + 9);
}

// Address range: 0x1000f8a0 - 0x1000f8a1
int32_t function_1000f8a0(void) {
    // 0x1000f8a0
    int32_t result; // 0x1000f8a0
    return result;
}

// Address range: 0x1000f8a3 - 0x1000f8c7
int32_t function_1000f8a3(void) {
    // 0x1000f8a3
    int32_t v1; // 0x1000f8a3
    uint32_t v2; // 0x1000f8a3
    int32_t v3 = v1 & 255 & v2 / 256 | v1 & -256; // 0x1000f8a4
    __asm_out_6((int16_t)v3, (char)__asm_sti());
    char * v4 = (char *)v3; // 0x1000f8ad
    *v4 = 2 * *v4;
    int32_t v5; // 0x1000f8a3
    int32_t * v6 = (int32_t *)(v5 + 67); // 0x1000f8af
    *v6 = *v6 | 0x22c25448;
    int32_t result = function_1000f8e4((int32_t)&g6, (int32_t)&g6, (int32_t)&g6, (int32_t)&g6, (int32_t)&g6, (int32_t)&g6, (int32_t)&g6, (int32_t)&g6); // 0x1000f8c5
    return result;
}

// Address range: 0x1000f8c7 - 0x1000f8d1
int32_t function_1000f8c7(void) {
    // 0x1000f8c7
    int32_t result; // 0x1000f8c7
    int32_t * v1 = (int32_t *)(result - 5); // 0x1000f8c8
    *v1 = *v1 - 93;
    int32_t * v2 = (int32_t *)(result + 84); // 0x1000f8cd
    int32_t v3; // 0x1000f8c7
    *v2 = *v2 | v3;
    return result;
}

// Address range: 0x1000f8e4 - 0x1000f900
int32_t function_1000f8e4(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8) {
    // 0x1000f8e4
    uint32_t v1; // 0x1000f8e4
    char v2 = v1 / 256; // 0x1000f8e4
    *(char *)-0x60b77e1f = *(char *)-0x60b77e1f | v2;
    int32_t v3; // 0x1000f8e4
    char * v4 = (char *)(2 * v3 + 0x774ddc50); // 0x1000f8ea
    *v4 = *v4 - (char)v1;
    int32_t v5; // 0x1000f8e4
    *(char *)v5 = *(char *)&v5 + v2;
    return function_51e098b1();
}

// Address range: 0x1000f900 - 0x1000f940
int32_t function_1000f900(int32_t a1) {
    // 0x1000f900
    int32_t v1; // 0x1000f900
    int32_t v2 = v1 - 0x52016043; // 0x1000f911
    unsigned char v3 = (char)v2 & 121; // 0x1000f916
    int32_t v4 = v2 & -256 | (int32_t)v3; // 0x1000f918
    if (v3 == 0) {
        // 0x1000f91a
        float80_t v5; // 0x1000f900
        *(int32_t *)-0x2f9220e8 = (int32_t)v5;
        int32_t * v6 = (int32_t *)((a1 | 132) + 124); // 0x1000f926
        uint32_t v7 = *v6; // 0x1000f926
        *v6 = v7 - 0x3c0ab77d;
        int32_t v8; // 0x1000f900
        char * v9 = (char *)(v8 - 117); // 0x1000f92d
        *v9 = 2 * *v9 | (char)(v7 > 0x3c0ab77c);
        v4 = __asm_int1();
    }
    // 0x1000f934
    return 0x10000 * v4 / 0x10000;
}

// Address range: 0x1000f951 - 0x1000f963
int32_t function_1000f951(int32_t a1) {
    // 0x1000f951
    float80_t v1; // 0x1000f951
    __pseudo_get_significand_9(v1);
    __pseudo_get_exponent_10(v1);
    int32_t v2; // 0x1000f951
    int32_t v3 = v2 & -256 | (int32_t)__asm_in_4(-126); // 0x1000f955
    int32_t v4; // 0x1000f951
    *(int32_t *)v4 = v3;
    return v3 & 0x3e622a04;
}

// Address range: 0x1000f963 - 0x1000f9a4
int32_t function_1000f963(int32_t a1) {
    // 0x1000f963
    int32_t v1; // 0x1000f963
    int32_t v2; // 0x1000f963
    unsigned char v3 = *(char *)((v2 & 255) + v1); // 0x1000f965
    int32_t v4 = v2 & -256; // 0x1000f965
    int32_t v5; // 0x1000f963
    uint32_t v6; // 0x1000f963
    __asm_arpl((int16_t)v5, (int16_t)v6);
    float80_t v7; // 0x1000f963
    *(float32_t *)((v4 | (int32_t)v3) + 59) = (float32_t)v7;
    char v8; // 0x1000f963
    return ((v4 | (int32_t)(v3 - 79)) ^ (256 * (int32_t)(v8 | (char)(v6 / 256)) | v6 & -0xff01)) - 0x3ba0da8d;
}

// Address range: 0x1000f975 - 0x1000f976
int32_t function_1000f975(void) {
    // 0x1000f975
    int32_t result; // 0x1000f975
    return result;
}

// Address range: 0x1000f9a4 - 0x1000f9fb
int32_t function_1000f9a4(int32_t a1) {
    // 0x1000f9a4
    int32_t v1; // 0x1000f9a4
    int32_t * v2 = (int32_t *)(v1 - 0x30f2b63c); // 0x1000f9a9
    int32_t v3 = *v2 - 0x6b0b5477; // 0x1000f9a9
    *v2 = v3;
    int32_t v4; // 0x1000f9a4
    if (v3 != 0) {
        v4 = function_1000f975();
    }
    int32_t v5 = v4 | 223; // 0x1000f9bb
    uint32_t v6 = *(int32_t *)v5; // 0x1000f9c3
    unsigned char v7 = *(char *)(a1 - 110) | (char)(v6 / 256); // 0x1000f9c5
    int32_t v8; // 0x1000f9a4
    if (v8 != 1 == v7 == 0) {
        int32_t * v9 = (int32_t *)(v5 + 32); // 0x1000f9e1
        int32_t result = *v9 & -247; // 0x1000f9e8
        *v9 = result;
        *(int32_t *)-0x50d17b17 = result;
        return result;
    }
    // 0x1000f9ca
    __asm_int(13);
    int32_t v10; // 0x1000f9a4
    bool v11; // 0x1000f9a4
    char * v12 = (char *)(v10 - 0x3fbd310f + (v11 ? -4 : 4)); // 0x1000f9cd
    *v12 = *v12 | 83;
    uint32_t v13; // 0x1000f9a4
    *(char *)-0x4faeee73 = *(char *)-0x4faeee73 - (char)(v13 / 256);
    return 256 * (int32_t)v7 | v6 & -0xff01;
}

// Address range: 0x1000f9fb - 0x1000fa39
int32_t function_1000f9fb(void) {
    // 0x1000f9fb
    uint32_t v1; // 0x1000f9fb
    uint32_t v2; // 0x1000f9fb
    int32_t v3; // 0x1000f9fb
    int32_t v4 = (v3 & -0xff01 | 2304) + (v2 < v1 ? -0x3bbc7c05 : -0x3bbc7c06); // 0x1000fa01
    int32_t v5; // 0x1000f9fb
    unsigned char v6 = (char)v5 & 31; // 0x1000fa06
    if (v6 != 0) {
        char * v7 = (char *)(v4 - 29); // 0x1000fa06
        unsigned char v8 = *v7; // 0x1000fa06
        *v7 = v8 >> 8 - v6 | v8 << v6;
    }
    int32_t v9; // 0x1000f9fb
    char v10 = *(char *)(v9 + 0x59c0c305); // 0x1000fa0a
    int32_t v11 = v4 & -0x7300 | (int32_t)(v10 | (char)v4); // 0x1000fa0a
    int32_t v12; // 0x1000f9fb
    char * v13 = (char *)(v12 - 37 + v11); // 0x1000fa1c
    unsigned char v14 = *v13; // 0x1000fa1c
    int32_t v15; // 0x1000f9fb
    unsigned char v16 = v14 + ((char)v15 == 0 ? -78 : -79); // 0x1000fa1c
    bool v17 = (char)v15 == 0 ? v16 <= v14 : v14 > 78; // 0x1000fa1c
    *v13 = v16;
    *(int32_t *)-0x15209d7f = v11;
    int32_t * v18 = (int32_t *)(v11 + 0x7d7ab771); // 0x1000fa29
    uint32_t v19 = *v18; // 0x1000fa29
    int32_t v20 = !v17; // 0x1000fa29
    int32_t v21 = v19 + 0x48434e81 + v20; // 0x1000fa29
    char v22 = llvm_ctpop_i8((char)v21); // 0x1000fa29
    bool v23 = !v17 ? v21 <= v19 : v19 > 0xb7bcb17e; // 0x1000fa29
    *v18 = v21;
    return 256 * (16 * (int32_t)((v19 & 15) + 1 + v20 > 15) | (int32_t)v23 | 64 * (int32_t)(v21 == 0) | 128 * (int32_t)(v21 < 0) | 4 * (int32_t)((v22 & 1) == 0)) | 0x78e90233;
}

// Address range: 0x1000fa55 - 0x1000fa62
int32_t function_1000fa55(void) {
    // 0x1000fa55
    int32_t v1; // 0x1000fa55
    __asm_fldenv(*(int224_t *)(v1 - 43));
    return function_1000fa8e((int32_t)&g6);
}

// Address range: 0x1000fa81 - 0x1000fa89
int32_t function_1000fa81(void) {
    // 0x1000fa81
    return function_9305d229();
}

// Address range: 0x1000fa8e - 0x1000faa8
int32_t function_1000fa8e(int32_t a1) {
    // 0x1000fa8e
    int32_t v1; // 0x1000fa8e
    float80_t v2; // 0x1000fa8e
    *(int64_t *)(v1 + 0x59d1fe9f) = (int64_t)v2;
    int32_t v3; // 0x1000fa8e
    char * v4 = (char *)(v3 - 95); // 0x1000fa9c
    int32_t v5; // 0x1000fa8e
    *v4 = *v4 + 60 + (char)((char)v5 < 121);
    return function_92f83f53();
}

// Address range: 0x1000faa8 - 0x1000fb2d
int32_t function_1000faa8(int32_t a1) {
    // 0x1000faa8
    int32_t v1; // 0x1000faa8
    int32_t v2 = v1 - 0x48050586; // 0x1000faa8
    if ((v1 & 14) > 5 || (v2 & 14) > 9) {
        // 0x1000fb0c
        __asm_in_2(62);
        int32_t result = __asm_hlt(); // 0x1000fb27
        int32_t v3; // 0x1000faa8
        int32_t v4; // 0x1000faa8
        __asm_outsd((int16_t)v4 & -256 | 129, v3);
        return result;
    }
    int32_t v5 = v2 & -256 | 11; // 0x1000faba
    int32_t * v6 = (int32_t *)(v5 - 89); // 0x1000fabc
    uint32_t v7 = *v6; // 0x1000fabc
    *v6 = v7 / 2;
    return v5 + 0x1225bbc6 + (int32_t)((v7 & 1) != 0);
}

// Address range: 0x1000fb2f - 0x1000fb30
int32_t function_1000fb2f(void) {
    // 0x1000fb2f
    int32_t result; // 0x1000fb2f
    return result;
}

// Address range: 0x1000fb32 - 0x1000fb33
int32_t function_1000fb32(void) {
    // 0x1000fb32
    int32_t result; // 0x1000fb32
    return result;
}

// Address range: 0x1000fb36 - 0x1000fb43
int32_t function_1000fb36(void) {
    // 0x1000fb36
    int32_t v1; // 0x1000fb36
    *(int32_t *)v1 = v1 | 0x70f5d968;
    int32_t result; // 0x1000fb36
    return result;
}

// Address range: 0x1000fb43 - 0x1000fb63
int32_t function_1000fb43(int32_t a1) {
    // 0x1000fb43
    float80_t v1; // 0x1000fb43
    *(int16_t *)-0x749fbc7f = (int16_t)v1;
    int32_t v2; // 0x1000fb43
    __asm_out(244, v2);
    int32_t v3; // 0x1000fb43
    *(char *)v3 = (char)v3 | 19;
    int32_t v4; // 0x1000fb43
    *(char *)v4 = *(char *)&v4 - 22;
    int32_t v5; // 0x1000fb43
    bool v6; // 0x1000fb43
    int32_t v7 = v5 + (v6 ? -1 : 1); // 0x1000fb54
    int32_t v8 = *(char *)&v5 > (char)v4 ? 255 : 0; // 0x1000fb55
    uint32_t v9; // 0x1000fb43
    *(int32_t *)v7 = v8 & v9 / 256 | v4 & -256;
    int32_t v10 = v7 + (v6 ? -4 : 4); // 0x1000fb5b
    int32_t v11; // 0x1000fb43
    *(int32_t *)v11 = v10;
    char * v12 = (char *)v10; // 0x1000fb5e
    *v12 = *v12 - (char)(v4 / 256);
    return __asm_in((int16_t)a1);
}

// Address range: 0x1000fb63 - 0x1000fb68
int32_t function_1000fb63(void) {
    // 0x1000fb63
    return function_fffff147();
}

// Address range: 0x1000fb68 - 0x1000fb81
int32_t function_1000fb68(void) {
    // 0x1000fb68
    bool v1; // 0x1000fb68
    int32_t v2 = v1; // 0x1000fb6a
    int32_t v3; // 0x1000fb68
    uint32_t v4 = v3 + v2; // 0x1000fb6a
    uint32_t v5; // 0x1000fb68
    int32_t v6 = v5 - v4; // 0x1000fb6a
    int32_t v7; // 0x1000fb68
    if (v1 ? v4 != -1 || v5 < v6 - v2 : v5 < v4) {
        v7 = function_1000fb32();
    }
    uint32_t v8 = v7;
    char v9 = v8; // 0x1000fb6e
    *(char *)0x54474a5d = v9;
    char v10 = *(char *)(v6 - 0x590f1a27); // 0x1000fb75
    int32_t result = v8 & -0x10000 | (int32_t)((v10 | v9) + -21 * (char)(v8 / 256)); // 0x1000fb7c
    int32_t v11; // 0x1000fb68
    *(int32_t *)v11 = result;
    return result;
}

// Address range: 0x1000fb81 - 0x1000fb82
int32_t function_1000fb81(void) {
    // 0x1000fb81
    int32_t result; // 0x1000fb81
    return result;
}

// Address range: 0x1000fb82 - 0x1000fbb2
int32_t function_1000fb82(void) {
    // 0x1000fb82
    int32_t v1; // 0x1000fb82
    uint32_t v2 = v1 & 31; // 0x1000fb82
    bool v3; // 0x1000fb82
    uint32_t result; // 0x1000fb82
    if (v2 != 0) {
        uint32_t v4 = result << 32 - v2 | result >> v2; // 0x1000fb82
        *(int32_t *)result = v4;
        bool v5; // 0x1000fb82
        v3 = v2 == 1 ? v4 / 0x80000000 != (v4 / 0x40000000 & 1) : v5;
    }
    int32_t v6; // 0x1000fb82
    int32_t v7; // 0x1000fb82
    __asm_outsd((int16_t)v7, v6);
    if ((int16_t)result < 0 != v3) {
        // 0x1000fb8d
        int32_t v8; // 0x1000fb82
        char * v9 = (char *)(v8 + 0x40d1c244); // 0x1000fb8d
        *v9 = *v9 + 1;
        return result;
    }
    unsigned char v10 = (char)result; // 0x1000fb9d
    int32_t v11 = v10 < 233 ? result : result + 23; // 0x1000fb9d
    int32_t * v12 = (int32_t *)(v6 - 0x5050a04); // 0x1000fba6
    float80_t v13; // 0x1000fb82
    *v12 = *v12 - (v13 != v13 || 0.0L != 0.0L ? -0x747cb834 : -0x747cb835);
    int32_t v14; // 0x1000fb82
    *(int32_t *)v6 = v14 ^ v6;
    return (v11 & 255 | result & -0x10000 | 256 * (int32_t)(v10 > 232)) + 0x16805838;
}

// Address range: 0x1000fbb4 - 0x1000fbc3
int32_t function_1000fbb4(void) {
    // 0x1000fbb4
    int32_t v1; // 0x1000fbb4
    int32_t v2; // 0x1000fbb4
    bool v3; // 0x1000fbb4
    *(int32_t *)v2 = v2 - v1 + (int32_t)v3;
    int32_t result; // 0x1000fbb4
    return result;
}

// Address range: 0x1000fbc3 - 0x1000fc62
int32_t function_1000fbc3(int32_t a1) {
    // 0x1000fbc3
    int32_t v1; // 0x1000fbc3
    int32_t result; // 0x1000fbc3
    float80_t v2; // 0x1000fbc3
    *(int16_t *)(v1 - 0x6f43601a + 2 * result) = (int16_t)v2;
    bool v3; // 0x1000fbc3
    if (v3) {
        // 0x1000fc4b
        return function_5fb0edc8();
    }
    // 0x1000fbce
    uint32_t v4; // 0x1000fbc3
    *(int32_t *)v4 = v4 / 0x4000 | 0x40000 * v4;
    return result;
}

// Address range: 0x1000fc62 - 0x1000fc63
int32_t function_1000fc62(int32_t a1) {
    // 0x1000fc62
    int32_t result; // 0x1000fc62
    return result;
}

// Address range: 0x1000fc63 - 0x1000fc89
int32_t function_1000fc63(int32_t result) {
    // 0x1000fc63
    int32_t v1; // 0x1000fc63
    if (v1 != 1) {
        // 0x1000fc84
        return result;
    }
    // 0x1000fc6b
    __asm_int(204);
    int32_t result2; // 0x1000fc63
    return result2;
}

// Address range: 0x1000fc89 - 0x1000fcbd
int32_t function_1000fc89(int32_t a1) {
    // 0x1000fc89
    int32_t v1; // 0x1000fc89
    uint32_t v2 = v1 ^ 0x5740dcc9; // 0x1000fc97
    int32_t v3; // 0x1000fc89
    int32_t * v4 = (int32_t *)(v3 - 45); // 0x1000fc9c
    int32_t v5 = *v4; // 0x1000fc9c
    *v4 = v5 >> 31;
    char v6 = -111 * (char)(v2 / 256) + (char)v2; // 0x1000fca1
    int32_t v7 = v2 & -0x10000 | (int32_t)v6; // 0x1000fca1
    int32_t v8; // 0x1000fc89
    int32_t v9; // 0x1000fc89
    *(int32_t *)(v9 - 0x323cfaf6) = *(int32_t *)(v8 - 29 + v7);
    int32_t v10 = (v5 & 0x40000000) == 0 ? 0 : 255; // 0x1000fcad
    int32_t v11 = v7; // 0x1000fca7
    v11 = v11 & -256 | v10;
    while (v6 >= 0) {
        // 0x1000fcad
        v11 = v11 & -256 | v10;
    }
    // 0x1000fcb0
    int32_t v12; // 0x1000fc89
    char v13 = *(char *)&v12 & (char)v10; // 0x1000fcb3
    return v11 & -0xff01 | 0x4000 * (int32_t)(v13 == 0) | 0x8000 * (int32_t)(v13 < 0) | 1024 * (int32_t)((llvm_ctpop_i8(v13) & 1) == 0) | 512;
}

// Address range: 0x1000fcbd - 0x1000fccb
int32_t function_1000fcbd(void) {
    // 0x1000fcbd
    int32_t v1; // 0x1000fcbd
    return function_968cfd5e(v1);
}

// Address range: 0x1000fce9 - 0x1000fd6f
int32_t function_1000fce9(void) {
    // 0x1000fce9
    int32_t v1; // 0x1000fce9
    int32_t v2; // 0x1000fce9
    __asm_outsd((int16_t)v2, v1);
    int32_t result; // 0x1000fce9
    return result;
}

// Address range: 0x1000fd78 - 0x1000fe0d
int32_t function_1000fd78(void) {
    // 0x1000fd78
    int32_t v1; // 0x1000fd78
    int32_t v2; // 0x1000fd78
    bool v3; // 0x1000fd78
    if (v3) {
        unsigned char v4 = (char)v2; // 0x1000fd7f
        bool v5; // 0x1000fd78
        char v6 = v5; // 0x1000fd7f
        unsigned char v7 = v4 - 37 + v6; // 0x1000fd7f
        char v8 = llvm_ctpop_i8(v7); // 0x1000fd7f
        bool v9 = v5 ? v7 <= v4 : v4 > 36; // 0x1000fd7f
        int32_t v10; // 0x1000fd78
        float80_t v11; // 0x1000fd78
        *(int32_t *)v10 = v10 + 0x3e7ab73d + (int32_t)(v11 != v11 || 0.0L != 0.0L);
        int32_t * v12 = (int32_t *)(v1 + 67); // 0x1000fd90
        *v12 = *v12 | 0x5e6a94e9;
        return v2 & -0x10000 | (int32_t)v7 | 256 * (16 * (int32_t)((v4 & 15) + 11 + v6 > 15) | (int32_t)v9 | 64 * (int32_t)(v7 == 0) | 128 * (int32_t)(v7 < 0) | 4 * (int32_t)((v8 & 1) == 0)) | 512;
    }
    // 0x1000fdad
    uint32_t v13; // 0x1000fd78
    char * v14 = (char *)(v13 + 0x6c81a14f); // 0x1000fdbd
    int32_t v15; // 0x1000fd78
    int32_t v16 = v15 - 1; // 0x1000fdb7
    bool v17 = (char)v2 > 153;
    int32_t v18; // 0x1000fd78
    int32_t v19 = v18;
    *(int32_t *)(v19 - 4) = v19;
    uint32_t v20; // 0x1000fd78
    *v14 = *v14 - (char)(v20 / 256);
    int32_t v21 = v19 - 8; // 0x1000fdc7
    *(int32_t *)v21 = (int32_t)(v20 - v13 / 256 & 255 | v20 & -256);
    v16 |= *(int32_t *)(v1 - 0x58285f8 + 4 * v13);
    int32_t * v22 = (int32_t *)(v16 + 0x645eadfd); // 0x1000fdd0
    *v22 = *v22 + 1;
    while (v17) {
        // 0x1000fdba
        v17 = false;
        v19 = v21;
        *(int32_t *)(v19 - 4) = v19;
        *v14 = *v14 - (char)(v20 / 256);
        v21 = v19 - 8;
        *(int32_t *)v21 = (int32_t)(v20 - v13 / 256 & 255 | v20 & -256);
        v16 |= *(int32_t *)(v1 - 0x58285f8 + 4 * v13);
        v22 = (int32_t *)(v16 + 0x645eadfd);
        *v22 = *v22 + 1;
    }
    // 0x1000fdd8
    return function_4a0580fa();
}

// Address range: 0x1000fe16 - 0x1000fe17
int32_t function_1000fe16(void) {
    // 0x1000fe16
    int32_t result; // 0x1000fe16
    return result;
}

// Address range: 0x1000fe3f - 0x1000fe43
int32_t function_1000fe3f(void) {
    // 0x1000fe3f
    return function_1000fe16();
}

// Address range: 0x1000fe57 - 0x1000fe62
int32_t function_1000fe57(void) {
    // 0x1000fe57
    int32_t v1; // 0x1000fe57
    char * v2 = (char *)(v1 - 43); // 0x1000fe5d
    uint32_t v3; // 0x1000fe57
    *v2 = *v2 + (char)(v3 / 256);
    int32_t result; // 0x1000fe57
    return result;
}

// Address range: 0x1000fe62 - 0x1000fe6a
int32_t function_1000fe62(void) {
    // 0x1000fe62
    __asm_int(77);
    int32_t result; // 0x1000fe62
    return result;
}

// Address range: 0x1000fe6b - 0x1000fe6f
int32_t function_1000fe6b(void) {
    // 0x1000fe6b
    int32_t result; // 0x1000fe6b
    return result;
}

// Address range: 0x1000fe76 - 0x1000fe81
int32_t function_1000fe76(void) {
    // 0x1000fe76
    int32_t v1; // 0x1000fe76
    int32_t result; // 0x1000fe76
    bool v2; // 0x1000fe76
    *(char *)((v2 ? -1 : 1) + v1) = (char)result;
    return result;
}

// Address range: 0x1000fe81 - 0x1000fe89
int32_t function_1000fe81(void) {
    // 0x1000fe81
    int32_t v1; // 0x1000fe81
    return v1 | 0x284781d2;
}

// Address range: 0x1000fe89 - 0x1000feb9
int32_t function_1000fe89(int32_t a1) {
    // 0x1000fe89
    int32_t v1; // 0x1000fe89
    uint32_t v2 = v1 + 1 & 31; // 0x1000fe9b
    if (v2 != 0) {
        uint32_t v3 = *(int32_t *)-0x402c28a0; // 0x1000fe9b
        *(int32_t *)-0x402c28a0 = v3 >> v2 | v3 << 32 - v2;
    }
    int32_t v4; // 0x1000fe89
    int32_t v5; // 0x1000fe89
    bool v6; // 0x1000fe89
    int32_t * v7 = (int32_t *)(*(int32_t *)(v4 + 74) + v5 + (int32_t)v6 - 0x5050a5c); // 0x1000fea6
    uint32_t v8 = *v7; // 0x1000fea6
    *v7 = v8 - 0x17ec0c3;
    __asm_out_7(70, (char)a1 & -55);
    int32_t v9; // 0x1000fe89
    int32_t v10 = v9 - 1; // 0x1000feb2
    return a1 & -0x7bdbff37 | 256 * (128 * (int32_t)(v10 < 0) | 64 * (int32_t)(v10 == 0) | 16 * (int32_t)((v9 & 15) > 16) | 4 * (int32_t)((llvm_ctpop_i8((char)v10) & 1) == 0) | (int32_t)(v8 < 0x17ec0c3)) | 512;
}

// Address range: 0x1000feb9 - 0x1000ff68
int32_t function_1000feb9(int32_t a1, uint32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t v1 = a5;
    int32_t v2; // 0x1000feb9
    uint32_t v3 = v2 + 1; // 0x1000feb9
    int32_t v4; // 0x1000feb9
    int32_t v5; // 0x1000feb9
    char v6 = *(char *)(v4 - 0x5828584 + 4 * v5); // 0x1000fec8
    int32_t v7; // 0x1000feb9
    *(char *)(v7 + 71) = v6 + (char)v3;
    char * v8 = (char *)v7; // 0x1000fed3
    *v8 = (char)(v3 / 256);
    int32_t v9; // 0x1000feb9
    __asm_out_6((int16_t)v7, (char)v9);
    *v8 = (char)v7;
    __readgsdword((v9 ^ 19) + 0x48059ba9);
    uint32_t v10 = v1; // 0x1000fef0
    char * v11; // 0x1000feb9
    char v12 = *(char *)(4 * a3 + 0x70520179 + (int32_t)v11); // 0x1000fef1
    int32_t v13 = 256 * (int32_t)(v12 + (char)(v10 / 256)) | v10 & -0xff01; // 0x1000fef1
    char * v14 = (char *)v13; // 0x1000fef8
    unsigned char v15 = *v14; // 0x1000fef8
    *v14 = v15 / 128 | 2 * v15;
    int32_t v16 = v10 & 179 | v13 & -256 | 76; // 0x1000feff
    int32_t v17 = a4 & -256 | (int32_t)((char)a4 - *(char *)(v16 + 16)); // 0x1000ff02
    *(char *)0xa90db05 = *(char *)0xa90db05 & (char)a3;
    float80_t v18; // 0x1000feb9
    *(float64_t *)(v16 + 1 + 2 * v17) = (float64_t)v18;
    uint16_t v19; // 0x1000feb9
    *(char *)(int32_t)v19 = *v11;
    char v20 = *(char *)-0x66cbaf57; // 0x1000ff18
    int32_t v21; // bp+22, 0x1000feb9
    v1 = &v21;
    char * v22 = (char *)(a3 + 43); // 0x1000ff1e
    unsigned char v23 = *v22; // 0x1000ff1e
    unsigned char v24 = (char)(a2 / 256); // 0x1000ff1e
    *v22 = v23 - v24;
    uint32_t v25 = v16 + 0x68a15219 & -256 | (int32_t)(v20 + 108 + (char)(v23 < v24)); // 0x1000ff22
    if (v25 <= 0x7d7aae7f) {
        // 0x1000ff31
        return v25 - 0x7d7aae80;
    }
    char * v26 = (char *)(v25 - 0x2b23fee3); // 0x1000ff3d
    unsigned char v27 = *v26; // 0x1000ff3d
    unsigned char v28 = (char)a2; // 0x1000ff3d
    *v26 = v27 - v28;
    int32_t v29; // 0x1000feb9
    int16_t v30 = *(int16_t *)((int32_t)&v1 - 1 + v29);
    int16_t v31 = v30; // bp+16, 0x1000ff46
    int32_t v32 = v27 < v28 ? -0x1d8ffa7d : -0x1d8ffa7e; // 0x1000ff47
    *(int32_t *)-0x6303f4fb = *(int32_t *)-0x6303f4fb - v32;
    int32_t * v33 = (int32_t *)(a3 + 1); // 0x1000ff51
    uint32_t v34 = *v33; // 0x1000ff51
    *v33 = v34 / 0x80000 | 0x2000 * v34;
    *(char *)-0xf0eff80 = *(char *)-0xf0eff80 - v28;
    return function_86ea5e3b(&v31, v30);
}

// Address range: 0x1000fff4 - 0x10010000
int32_t function_1000fff4(void) {
    // 0x1000fff4
    int32_t result; // 0x1000fff4
    return result;
}

// Address range: 0x1001000c - 0x1001000f
int32_t function_1001000c(void) {
    // 0x1001000c
    int32_t result; // 0x1001000c
    return result;
}

// Address range: 0x3577b9d2 - 0x3577b9d3
int32_t function_3577b9d2(void) {
    // 0x3577b9d2
    int32_t result; // 0x3577b9d2
    return result;
}

// Address range: 0x35be468b - 0x35be468c
int32_t function_35be468b(void) {
    // 0x35be468b
    int32_t result; // 0x35be468b
    return result;
}

// Address range: 0x3e81841d - 0x3e81841e
int32_t function_3e81841d(int32_t a1) {
    // 0x3e81841d
    int32_t result; // 0x3e81841d
    return result;
}

// Address range: 0x455ec90c - 0x455ec90d
int32_t function_455ec90c(void) {
    // 0x455ec90c
    int32_t result; // 0x455ec90c
    return result;
}

// Address range: 0x468a5bdf - 0x468a5be0
int32_t function_468a5bdf(void) {
    // 0x468a5bdf
    int32_t result; // 0x468a5bdf
    return result;
}

// Address range: 0x4756a85f - 0x4756a860
int32_t function_4756a85f(void) {
    // 0x4756a85f
    int32_t result; // 0x4756a85f
    return result;
}

// Address range: 0x49e96b98 - 0x49e96b99
int32_t function_49e96b98(void) {
    // 0x49e96b98
    int32_t result; // 0x49e96b98
    return result;
}

// Address range: 0x4a0580fa - 0x4a0580fb
int32_t function_4a0580fa(void) {
    // 0x4a0580fa
    int32_t result; // 0x4a0580fa
    return result;
}

// Address range: 0x50bcab7a - 0x50bcab7b
int32_t function_50bcab7a(void) {
    // 0x50bcab7a
    int32_t result; // 0x50bcab7a
    return result;
}

// Address range: 0x51e098b1 - 0x51e098b2
int32_t function_51e098b1(void) {
    // 0x51e098b1
    int32_t result; // 0x51e098b1
    return result;
}

// Address range: 0x5460c537 - 0x5460c538
int32_t function_5460c537(void) {
    // 0x5460c537
    int32_t result; // 0x5460c537
    return result;
}

// Address range: 0x54699785 - 0x54699786
int32_t function_54699785(void) {
    // 0x54699785
    int32_t result; // 0x54699785
    return result;
}

// Address range: 0x568d38a9 - 0x568d38aa
int32_t function_568d38a9(void) {
    // 0x568d38a9
    int32_t result; // 0x568d38a9
    return result;
}

// Address range: 0x5788a8a9 - 0x5788a8aa
int32_t function_5788a8a9(void) {
    // 0x5788a8a9
    int32_t result; // 0x5788a8a9
    return result;
}

// Address range: 0x598634dc - 0x598634dd
int32_t function_598634dc(int32_t a1) {
    // 0x598634dc
    int32_t result; // 0x598634dc
    return result;
}

// Address range: 0x5a4a141c - 0x5a4a141d
int32_t function_5a4a141c(void) {
    // 0x5a4a141c
    int32_t result; // 0x5a4a141c
    return result;
}

// Address range: 0x5b05bc21 - 0x5b05bc22
int32_t function_5b05bc21(void) {
    // 0x5b05bc21
    int32_t result; // 0x5b05bc21
    return result;
}

// Address range: 0x5d69d1f9 - 0x5d69d1fa
int32_t function_5d69d1f9(void) {
    // 0x5d69d1f9
    int32_t result; // 0x5d69d1f9
    return result;
}

// Address range: 0x5f4a09dc - 0x5f4a09dd
int32_t function_5f4a09dc(void) {
    // 0x5f4a09dc
    int32_t result; // 0x5f4a09dc
    return result;
}

// Address range: 0x5f88bee1 - 0x5f88bee2
int32_t function_5f88bee1(void) {
    // 0x5f88bee1
    int32_t result; // 0x5f88bee1
    return result;
}

// Address range: 0x5fb0edc8 - 0x5fb0edc9
int32_t function_5fb0edc8(void) {
    // 0x5fb0edc8
    int32_t result; // 0x5fb0edc8
    return result;
}

// Address range: 0x5fd80b7c - 0x5fd80b7d
int32_t function_5fd80b7c(void) {
    // 0x5fd80b7c
    int32_t result; // 0x5fd80b7c
    return result;
}

// Address range: 0x607bc505 - 0x607bc506
int32_t function_607bc505(void) {
    // 0x607bc505
    int32_t result; // 0x607bc505
    return result;
}

// Address range: 0x62f859a1 - 0x62f859a2
int32_t function_62f859a1(void) {
    // 0x62f859a1
    int32_t result; // 0x62f859a1
    return result;
}

// Address range: 0x63f45647 - 0x63f45648
int32_t function_63f45647(int32_t * a1, int32_t a2) {
    // 0x63f45647
    int32_t result; // 0x63f45647
    return result;
}

// Address range: 0x678e9999 - 0x678e999a
int32_t function_678e9999(void) {
    // 0x678e9999
    int32_t result; // 0x678e9999
    return result;
}

// Address range: 0x68140a05 - 0x68140a06
int32_t function_68140a05(void) {
    // 0x68140a05
    int32_t result; // 0x68140a05
    return result;
}

// Address range: 0x69a25772 - 0x69a25773
int32_t function_69a25772(void) {
    // 0x69a25772
    int32_t result; // 0x69a25772
    return result;
}

// Address range: 0x6f00ea5c - 0x6f00ea5d
int32_t function_6f00ea5c(void) {
    // 0x6f00ea5c
    int32_t result; // 0x6f00ea5c
    return result;
}

// Address range: 0x70f65d9d - 0x70f65d9e
int32_t function_70f65d9d(void) {
    // 0x70f65d9d
    int32_t result; // 0x70f65d9d
    return result;
}

// Address range: 0x7483ff02 - 0x7483ff03
int32_t function_7483ff02(void) {
    // 0x7483ff02
    int32_t result; // 0x7483ff02
    return result;
}

// Address range: 0x74942760 - 0x74942761
int32_t function_74942760(void) {
    // 0x74942760
    int32_t result; // 0x74942760
    return result;
}

// Address range: 0x78bcab7a - 0x78bcab7b
int32_t function_78bcab7a(void) {
    // 0x78bcab7a
    int32_t result; // 0x78bcab7a
    return result;
}

// Address range: 0x7c6d2021 - 0x7c6d2022
int32_t function_7c6d2021(void) {
    // 0x7c6d2021
    int32_t result; // 0x7c6d2021
    return result;
}

// Address range: 0x7f484ade - 0x7f484adf
int32_t function_7f484ade(void) {
    // 0x7f484ade
    int32_t result; // 0x7f484ade
    return result;
}

// Address range: 0x7f83f8d6 - 0x7f83f8d7
int32_t function_7f83f8d6(void) {
    // 0x7f83f8d6
    int32_t result; // 0x7f83f8d6
    return result;
}

// Address range: 0x80642ee6 - 0x80642ee7
int32_t function_80642ee6(void) {
    // 0x80642ee6
    int32_t result; // 0x80642ee6
    return result;
}

// Address range: 0x82065723 - 0x82065724
int32_t function_82065723(void) {
    // 0x82065723
    int32_t result; // 0x82065723
    return result;
}

// Address range: 0x83cc5381 - 0x83cc5382
int32_t function_83cc5381(void) {
    // 0x83cc5381
    int32_t result; // 0x83cc5381
    return result;
}

// Address range: 0x84221700 - 0x84221701
int32_t function_84221700(void) {
    // 0x84221700
    int32_t result; // 0x84221700
    return result;
}

// Address range: 0x8456585f - 0x84565860
int32_t function_8456585f(void) {
    // 0x8456585f
    int32_t result; // 0x8456585f
    return result;
}

// Address range: 0x854fda12 - 0x854fda13
int32_t function_854fda12(void) {
    // 0x854fda12
    int32_t result; // 0x854fda12
    return result;
}

// Address range: 0x855604d5 - 0x855604d6
int32_t function_855604d5(void) {
    // 0x855604d5
    int32_t result; // 0x855604d5
    return result;
}

// Address range: 0x86ea5e3b - 0x86ea5e3c
int32_t function_86ea5e3b(int16_t * a1, int16_t a2) {
    // 0x86ea5e3b
    int32_t result; // 0x86ea5e3b
    return result;
}

// Address range: 0x8a10c8c9 - 0x8a10c8ca
int32_t function_8a10c8c9(void) {
    // 0x8a10c8c9
    int32_t result; // 0x8a10c8c9
    return result;
}

// Address range: 0x8ceb7173 - 0x8ceb7174
int32_t function_8ceb7173(void) {
    // 0x8ceb7173
    int32_t result; // 0x8ceb7173
    return result;
}

// Address range: 0x90cf608f - 0x90cf6090
int32_t function_90cf608f(void) {
    // 0x90cf608f
    int32_t result; // 0x90cf608f
    return result;
}

// Address range: 0x91df9ff5 - 0x91df9ff6
int32_t function_91df9ff5(void) {
    // 0x91df9ff5
    int32_t result; // 0x91df9ff5
    return result;
}

// Address range: 0x92f83f53 - 0x92f83f54
int32_t function_92f83f53(void) {
    // 0x92f83f53
    int32_t result; // 0x92f83f53
    return result;
}

// Address range: 0x9305d229 - 0x9305d22a
int32_t function_9305d229(void) {
    // 0x9305d229
    int32_t result; // 0x9305d229
    return result;
}

// Address range: 0x968cfd5e - 0x968cfd5f
int32_t function_968cfd5e(int32_t a1) {
    // 0x968cfd5e
    int32_t result; // 0x968cfd5e
    return result;
}

// Address range: 0x96dcdc97 - 0x96dcdc98
int32_t function_96dcdc97(void) {
    // 0x96dcdc97
    int32_t result; // 0x96dcdc97
    return result;
}

// Address range: 0x9d2aaa2b - 0x9d2aaa2c
int32_t function_9d2aaa2b(int16_t a1) {
    // 0x9d2aaa2b
    int32_t result; // 0x9d2aaa2b
    return result;
}

// Address range: 0x9e0ab321 - 0x9e0ab322
int32_t function_9e0ab321(int32_t * a1) {
    // 0x9e0ab321
    int32_t result; // 0x9e0ab321
    return result;
}

// Address range: 0x9e0b0681 - 0x9e0b0682
int32_t function_9e0b0681(int32_t a1) {
    // 0x9e0b0681
    int32_t result; // 0x9e0b0681
    return result;
}

// Address range: 0xa4361ed4 - 0xa4361ed5
int32_t function_a4361ed4(void) {
    // 0xa4361ed4
    int32_t result; // 0xa4361ed4
    return result;
}

// Address range: 0xa55b2c5b - 0xa55b2c5c
int32_t function_a55b2c5b(void) {
    // 0xa55b2c5b
    int32_t result; // 0xa55b2c5b
    return result;
}

// Address range: 0xa68faf16 - 0xa68faf17
int32_t function_a68faf16(void) {
    // 0xa68faf16
    int32_t result; // 0xa68faf16
    return result;
}

// Address range: 0xa8140a07 - 0xa8140a08
int32_t function_a8140a07(void) {
    // 0xa8140a07
    int32_t result; // 0xa8140a07
    return result;
}

// Address range: 0xae1d200c - 0xae1d200d
int32_t function_ae1d200c(void) {
    // 0xae1d200c
    int32_t result; // 0xae1d200c
    return result;
}

// Address range: 0xafe33235 - 0xafe33236
int32_t function_afe33235(void) {
    // 0xafe33235
    int32_t result; // 0xafe33235
    return result;
}

// Address range: 0xb2c580fa - 0xb2c580fb
int32_t function_b2c580fa(void) {
    // 0xb2c580fa
    int32_t result; // 0xb2c580fa
    return result;
}

// Address range: 0xb8bcab7a - 0xb8bcab7b
int32_t function_b8bcab7a(void) {
    // 0xb8bcab7a
    int32_t result; // 0xb8bcab7a
    return result;
}

// Address range: 0xba7519a7 - 0xba7519a8
int32_t function_ba7519a7(void) {
    // 0xba7519a7
    int32_t result; // 0xba7519a7
    return result;
}

// Address range: 0xbaecd97a - 0xbaecd97b
int32_t function_baecd97a(void) {
    // 0xbaecd97a
    int32_t result; // 0xbaecd97a
    return result;
}

// Address range: 0xbdfaf95e - 0xbdfaf95f
int32_t function_bdfaf95e(void) {
    // 0xbdfaf95e
    int32_t result; // 0xbdfaf95e
    return result;
}

// Address range: 0xbfd7ff92 - 0xbfd7ff93
int32_t function_bfd7ff92(void) {
    // 0xbfd7ff92
    int32_t result; // 0xbfd7ff92
    return result;
}

// Address range: 0xbfd8188e - 0xbfd8188f
int32_t function_bfd8188e(void) {
    // 0xbfd8188e
    int32_t result; // 0xbfd8188e
    return result;
}

// Address range: 0xc0bb3cda - 0xc0bb3cdb
int32_t function_c0bb3cda(int16_t a1) {
    // 0xc0bb3cda
    int32_t result; // 0xc0bb3cda
    return result;
}

// Address range: 0xc48b5f2f - 0xc48b5f30
int32_t function_c48b5f2f(void) {
    // 0xc48b5f2f
    int32_t result; // 0xc48b5f2f
    return result;
}

// Address range: 0xc7b50a15 - 0xc7b50a16
int32_t function_c7b50a15(void) {
    // 0xc7b50a15
    int32_t result; // 0xc7b50a15
    return result;
}

// Address range: 0xcad7dd8e - 0xcad7dd8f
int32_t function_cad7dd8e(int32_t a1) {
    // 0xcad7dd8e
    int32_t result; // 0xcad7dd8e
    return result;
}

// Address range: 0xcd8ecc31 - 0xcd8ecc32
int32_t function_cd8ecc31(void) {
    // 0xcd8ecc31
    int32_t result; // 0xcd8ecc31
    return result;
}

// Address range: 0xd3e9c169 - 0xd3e9c16a
int32_t function_d3e9c169(int32_t a1, int32_t a2) {
    // 0xd3e9c169
    int32_t result; // 0xd3e9c169
    return result;
}

// Address range: 0xd3e9f723 - 0xd3e9f724
int32_t function_d3e9f723(int32_t a1, int32_t a2) {
    // 0xd3e9f723
    int32_t result; // 0xd3e9f723
    return result;
}

// Address range: 0xd85802ab - 0xd85802ac
int32_t function_d85802ab(void) {
    // 0xd85802ab
    int32_t result; // 0xd85802ab
    return result;
}

// Address range: 0xda3716f9 - 0xda3716fa
int32_t function_da3716f9(void) {
    // 0xda3716f9
    int32_t result; // 0xda3716f9
    return result;
}

// Address range: 0xdbd72018 - 0xdbd72019
int32_t function_dbd72018(void) {
    // 0xdbd72018
    int32_t result; // 0xdbd72018
    return result;
}

// Address range: 0xde2cd9d5 - 0xde2cd9d6
int32_t function_de2cd9d5(void) {
    // 0xde2cd9d5
    int32_t result; // 0xde2cd9d5
    return result;
}

// Address range: 0xdfa93e7a - 0xdfa93e7b
int32_t function_dfa93e7a(void) {
    // 0xdfa93e7a
    int32_t result; // 0xdfa93e7a
    return result;
}

// Address range: 0xdff00dd5 - 0xdff00dd6
int32_t function_dff00dd5(void) {
    // 0xdff00dd5
    int32_t result; // 0xdff00dd5
    return result;
}

// Address range: 0xe1d9ec21 - 0xe1d9ec22
int32_t function_e1d9ec21(void) {
    // 0xe1d9ec21
    int32_t result; // 0xe1d9ec21
    return result;
}

// Address range: 0xe34b5cb9 - 0xe34b5cba
int32_t function_e34b5cb9(void) {
    // 0xe34b5cb9
    int32_t result; // 0xe34b5cb9
    return result;
}

// Address range: 0xe4bddbce - 0xe4bddbcf
int32_t function_e4bddbce(int32_t a1, int32_t a2) {
    // 0xe4bddbce
    int32_t result; // 0xe4bddbce
    return result;
}

// Address range: 0xe625bc2e - 0xe625bc2f
int32_t function_e625bc2e(int32_t a1, int32_t a2) {
    // 0xe625bc2e
    int32_t result; // 0xe625bc2e
    return result;
}

// Address range: 0xe8c9cae1 - 0xe8c9cae2
int32_t function_e8c9cae1(int32_t * a1, int32_t a2, int32_t a3, int32_t a4, int16_t * a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9) {
    // 0xe8c9cae1
    int32_t result; // 0xe8c9cae1
    return result;
}

// Address range: 0xe9515fcc - 0xe9515fcd
int32_t function_e9515fcc(int32_t a1) {
    // 0xe9515fcc
    int32_t result; // 0xe9515fcc
    return result;
}

// Address range: 0xe9555466 - 0xe9555467
int32_t function_e9555466(void) {
    // 0xe9555466
    int32_t result; // 0xe9555466
    return result;
}

// Address range: 0xe99dab7a - 0xe99dab7b
int32_t function_e99dab7a(void) {
    // 0xe99dab7a
    int32_t result; // 0xe99dab7a
    return result;
}

// Address range: 0xeb3de332 - 0xeb3de333
int32_t function_eb3de332(int32_t a1, int32_t a2, int32_t a3) {
    // 0xeb3de332
    int32_t result; // 0xeb3de332
    return result;
}

// Address range: 0xeda590a9 - 0xeda590aa
int32_t function_eda590a9(void) {
    // 0xeda590a9
    int32_t result; // 0xeda590a9
    return result;
}

// Address range: 0xf236a6bf - 0xf236a6c0
int32_t function_f236a6bf(void) {
    // 0xf236a6bf
    int32_t result; // 0xf236a6bf
    return result;
}

// Address range: 0xf2583fc2 - 0xf2583fc3
int32_t function_f2583fc2(void) {
    // 0xf2583fc2
    int32_t result; // 0xf2583fc2
    return result;
}

// Address range: 0xf52bc664 - 0xf52bc665
int32_t function_f52bc664(int32_t a1) {
    // 0xf52bc664
    int32_t result; // 0xf52bc664
    return result;
}

// Address range: 0xf9f51bf8 - 0xf9f51bf9
int32_t function_f9f51bf8(void) {
    // 0xf9f51bf8
    int32_t result; // 0xf9f51bf8
    return result;
}

// Address range: 0xfb9f6d74 - 0xfb9f6d75
int32_t function_fb9f6d74(void) {
    // 0xfb9f6d74
    int32_t result; // 0xfb9f6d74
    return result;
}

// Address range: 0xfd89f9cb - 0xfd89f9cc
int32_t function_fd89f9cb(void) {
    // 0xfd89f9cb
    int32_t result; // 0xfd89f9cb
    return result;
}

// Address range: 0xfde8fc74 - 0xfde8fc75
int32_t function_fde8fc74(void) {
    // 0xfde8fc74
    int32_t result; // 0xfde8fc74
    return result;
}

// Address range: 0xfffff147 - 0xfffff148
int32_t function_fffff147(void) {
    // 0xfffff147
    int32_t result; // 0xfffff147
    return result;
}

// Address range: 0xfffff552 - 0xfffff553
int32_t function_fffff552(void) {
    // 0xfffff552
    int32_t result; // 0xfffff552
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: microsoft linker (7.1)
// Detected functions: 220
